// <auto-generated />

#nullable enable

using AVFoundation;
using CoreGraphics;
using Foundation;
using ObjCBindings;
using ObjCRuntime;
using System;
using System.Runtime.Versioning;

namespace TestNamespace;

public partial class EventTests
{
	[Register]
	internal class _RgenNSKeyedArchiverDelegate: NSObject, IRgenNSKeyedArchiverDelegate
	{
		public _RgenNSKeyedArchiverDelegate () { IsDirectBinding = false; }

		internal global::System.EventHandler<global::Foundation.NSObject>? encodedObject;
		[Preserve (Conditional = true)]
		[Export<Method> ("archiver:didEncodeObject:")]
		public void EncodedObject (global::Foundation.NSKeyedArchiver archiver, global::Foundation.NSObject obj)
		{
			var handler = encodedObject;
			if (handler is not null) {
				global::Foundation.NSObject args = new (obj);
				handler (archiver, args);
			}
		}

		internal global::System.EventHandler<global::Foundation.NSObject>? encodedObject2;
		[Preserve (Conditional = true)]
		[Export<Method> ("archiver:didEncodeObject:")]
		public void EncodedObject2 (global::Foundation.NSKeyedArchiver archiver, global::Foundation.NSObject obj)
		{
			var handler = encodedObject2;
			if (handler is not null) {
				global::Foundation.NSObject args = new (obj);
				handler (archiver, args);
			}
		}

		internal global::System.EventHandler? finished;
		[Preserve (Conditional = true)]
		[Export<Method> ("archiverDidFinish:")]
		public void Finished (global::Foundation.NSKeyedArchiver archiver)
		{
			var handler = finished;
			if (handler is not null) {
				handler (archiver, global::System.EventHandler.Empty);
			}
		}

		internal global::System.EventHandler<global::Foundation.NSObject>? willEncode;
		[Preserve (Conditional = true)]
		[Export<Method> ("archiverDidFinish:")]
		public void WillEncode (global::Foundation.NSKeyedArchiver archiver, global::Foundation.NSObject obj)
		{
			var handler = willEncode;
			if (handler is not null) {
				global::Foundation.NSObject args = new (obj);
				handler (archiver, args);
			}
		}

		internal global::System.EventHandler? finishing;
		[Preserve (Conditional = true)]
		[Export<Method> ("archiverWillFinish:")]
		public void Finishing (global::Foundation.NSKeyedArchiver archiver)
		{
			var handler = finishing;
			if (handler is not null) {
				handler (archiver, global::System.EventHandler.Empty);
			}
		}

		internal global::System.EventHandler<NSArchiveReplaceEventArgs>? replacingObject;
		[Preserve (Conditional = true)]
		[Export<Method> ("archiver:willReplaceObject:withObject:")]
		public void ReplacingObject (global::Foundation.NSKeyedArchiver archiver, global::Foundation.NSObject oldObject, global::Foundation.NSObject newObject)
		{
			var handler = replacingObject;
			if (handler is not null) {
				NSArchiveReplaceEventArgs args = new (oldObject, newObject);
				handler (archiver, args);
			}
		}

		internal global::System.EventHandler<(global::Foundation.NSObject OldObject, global::Foundation.NSObject NewObject)>? replacingObject2;
		[Preserve (Conditional = true)]
		[Export<Method> ("archiver:willReplaceObject:withObject:")]
		public void ReplacingObject2 (global::Foundation.NSKeyedArchiver archiver, global::Foundation.NSObject oldObject, global::Foundation.NSObject newObject)
		{
			var handler = replacingObject2;
			if (handler is not null) {
				var args = (oldObject, newObject);
				handler (archiver, args);
			}
		}

		internal global::System.EventHandler<(global::Foundation.NSObject Item1, global::Foundation.NSObject Item2)>? replacingObject3;
		[Preserve (Conditional = true)]
		[Export<Method> ("archiver:willReplaceObject:withObject:")]
		public void ReplacingObject3 (global::Foundation.NSKeyedArchiver archiver, global::Foundation.NSObject oldObject, global::Foundation.NSObject newObject)
		{
			var handler = replacingObject3;
			if (handler is not null) {
				var args = (oldObject, newObject);
				handler (archiver, args);
			}
		}

		internal global::System.EventHandler<(global::Foundation.NSObject, global::Foundation.NSObject)>? replacingObject4;
		[Preserve (Conditional = true)]
		[Export<Method> ("archiver:willReplaceObject:withObject:")]
		public void ReplacingObject4 (global::Foundation.NSKeyedArchiver archiver, global::Foundation.NSObject oldObject, global::Foundation.NSObject newObject)
		{
			var handler = replacingObject4;
			if (handler is not null) {
				var args = (oldObject, newObject);
				handler (archiver, args);
			}
		}

	}
}
