// <auto-generated />

#nullable enable

using AVFoundation;
using CoreGraphics;
using Foundation;
using ObjCBindings;
using ObjCRuntime;
using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Drawing;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;

namespace TestNamespace;

public partial class OuterClass
{
	public partial class InnerClass
	{
		[Register ("NestedClasses", true)]
		public partial class NestedClasses
		{
			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			const string selValueForKey_X = "valueForKey:";
			static readonly global::ObjCRuntime.NativeHandle selValueForKey_XHandle = global::ObjCRuntime.Selector.GetHandle ("valueForKey:");

			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			const string selSetValue_ForKey_X = "setValue:forKey:";
			static readonly global::ObjCRuntime.NativeHandle selSetValue_ForKey_XHandle = global::ObjCRuntime.Selector.GetHandle ("setValue:forKey:");

			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			const string selWriteToFile_Atomically_X = "writeToFile:atomically:";
			static readonly global::ObjCRuntime.NativeHandle selWriteToFile_Atomically_XHandle = global::ObjCRuntime.Selector.GetHandle ("writeToFile:atomically:");

			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			const string selArrayWithContentsOfFile_X = "arrayWithContentsOfFile:";
			static readonly global::ObjCRuntime.NativeHandle selArrayWithContentsOfFile_XHandle = global::ObjCRuntime.Selector.GetHandle ("arrayWithContentsOfFile:");

			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			const string selSortedArrayUsingComparator_X = "sortedArrayUsingComparator:";
			static readonly global::ObjCRuntime.NativeHandle selSortedArrayUsingComparator_XHandle = global::ObjCRuntime.Selector.GetHandle ("sortedArrayUsingComparator:");

			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			const string selCountX = "count";
			static readonly global::ObjCRuntime.NativeHandle selCountXHandle = global::ObjCRuntime.Selector.GetHandle ("count");

			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			const string selSetCount_X = "setCount:";
			static readonly global::ObjCRuntime.NativeHandle selSetCount_XHandle = global::ObjCRuntime.Selector.GetHandle ("setCount:");

			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			const string selLineSpacingX = "lineSpacing";
			static readonly global::ObjCRuntime.NativeHandle selLineSpacingXHandle = global::ObjCRuntime.Selector.GetHandle ("lineSpacing");

			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			const string selSetLineSpacing_X = "setLineSpacing:";
			static readonly global::ObjCRuntime.NativeHandle selSetLineSpacing_XHandle = global::ObjCRuntime.Selector.GetHandle ("setLineSpacing:");

			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			const string selSizesX = "sizes";
			static readonly global::ObjCRuntime.NativeHandle selSizesXHandle = global::ObjCRuntime.Selector.GetHandle ("sizes");

			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			const string selSetSizes_X = "setSizes:";
			static readonly global::ObjCRuntime.NativeHandle selSetSizes_XHandle = global::ObjCRuntime.Selector.GetHandle ("setSizes:");

			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			const string selContainsAttachmentsX = "containsAttachments";
			static readonly global::ObjCRuntime.NativeHandle selContainsAttachmentsXHandle = global::ObjCRuntime.Selector.GetHandle ("containsAttachments");

			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			const string selSetContainsAttachments_X = "setContainsAttachments:";
			static readonly global::ObjCRuntime.NativeHandle selSetContainsAttachments_XHandle = global::ObjCRuntime.Selector.GetHandle ("setContainsAttachments:");

			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			static readonly global::ObjCRuntime.NativeHandle class_ptr = global::ObjCRuntime.Class.GetHandle ("NestedClasses");

			/// <summary>The Objective-C class handle for this class.</summary>
			/// <value>The pointer to the Objective-C class.</value>
			/// <remarks>
			///     Each managed class mirrors an unmanaged Objective-C class.
			///     This value contains the pointer to the Objective-C class.
			///     It is similar to calling the managed <see cref=\"ObjCRuntime.Class.GetHandle(string)\" /> or the native <see href=\"https://developer.apple.com/documentation/objectivec/1418952-objc_getclass\">objc_getClass</see> method with the type name.
			/// </remarks>
			public override global::ObjCRuntime.NativeHandle ClassHandle => class_ptr;

			/// <summary>Creates a new <see cref="NestedClasses" /> with default values.</summary>
			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			[DesignatedInitializer]
			[Export ("init")]
			public NestedClasses () : base (global::Foundation.NSObjectFlag.Empty)
			{
				if (IsDirectBinding)
					InitializeHandle (global::ObjCRuntime.Messaging.IntPtr_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("init")), "init");
				else
					InitializeHandle (global::ObjCRuntime.Messaging.IntPtr_objc_msgSendSuper (this.SuperHandle, global::ObjCRuntime.Selector.GetHandle ("init")), "init");
			}

			/// <summary>Constructor to call on derived classes to skip initialization and merely allocate the object.</summary>
			/// <param name="t">Unused sentinel value, pass NSObjectFlag.Empty.</param>
			/// <remarks>
			///     <para>
			///         This constructor should be called by derived classes when they completely construct the object in managed code and merely want the runtime to allocate and initialize the <see cref="Foundation.NSObject" />.
			///         This is required to implement the two-step initialization process that Objective-C uses, the first step is to perform the object allocation, the second step is to initialize the object.
			///         When developers invoke this constructor, they take advantage of a direct path that goes all the way up to <see cref="Foundation.NSObject" /> to merely allocate the object's memory and bind the Objective-C and C# objects together.
			///         The actual initialization of the object is up to the developer.
			///     </para>
			///     <para>
			///         This constructor is typically used by the binding generator to allocate the object, but prevent the actual initialization to take place.
			///         Once the allocation has taken place, the constructor has to initialize the object.
			///         With constructors generated by the binding generator this means that it manually invokes one of the "init" methods to initialize the object.
			///     </para>
			///     <para>It is the developer's responsibility to completely initialize the object if they chain up using this constructor chain.</para>
			///     <para>
			///         In general, if the developer's constructor invokes the corresponding base implementation, then it should also call an Objective-C init method.
			///         If this is not the case, developers should instead chain to the proper constructor in their class.
			///     </para>
			///     <para>
			///         The argument value is ignored and merely ensures that the only code that is executed is the construction phase is the basic <see cref="Foundation.NSObject" /> allocation and runtime type registration.
			///         Typically the chaining would look like this:
			///     </para>
			///     <example>
			///             <code lang="csharp lang-csharp"><![CDATA[
			/// //
			/// // The NSObjectFlag constructor merely allocates the object and registers the C# class with the Objective-C runtime if necessary.
			/// // No actual initXxx method is invoked, that is done later in the constructor
			/// //
			/// // This is taken from the iOS SDK's source code for the UIView class:
			/// //
			/// [Export ("initWithFrame:")]
			/// public UIView (System.Drawing.RectangleF frame) : base (NSObjectFlag.Empty)
			/// {
			///     // Invoke the init method now.
			///     var initWithFrame = new Selector ("initWithFrame:").Handle;
			///     if (IsDirectBinding) {
			///         Handle = ObjCRuntime.Messaging.IntPtr_objc_msgSend_CGRect (this.Handle, initWithFrame, frame);
			///     } else {
			///         Handle = ObjCRuntime.Messaging.IntPtr_objc_msgSendSuper_CGRect (this.SuperHandle, initWithFrame, frame);
			///     }
			/// }
			/// ]]></code>
			///     </example>
			/// </remarks>
			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			[EditorBrowsable (EditorBrowsableState.Advanced)]
			protected NestedClasses (global::Foundation.NSObjectFlag t) : base (t) {}

			/// <summary>A constructor used when creating managed representations of unmanaged objects. Called by the runtime.</summary>
			/// <param name="handle">Pointer (handle) to the unmanaged object.</param>
			/// <remarks>
			///     <para>
			///         This constructor is invoked by the runtime infrastructure (<see cref="ObjCRuntime.Runtime.GetNSObject(System.IntPtr)" />) to create a new managed representation for a pointer to an unmanaged Objective-C object.
			///         Developers should not invoke this method directly, instead they should call <see cref="ObjCRuntime.Runtime.GetNSObject(System.IntPtr)" /> as it will prevent two instances of a managed object pointing to the same native object.
			///     </para>
			/// </remarks>
			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			[EditorBrowsable (EditorBrowsableState.Advanced)]
			protected internal NestedClasses (global::ObjCRuntime.NativeHandle handle) : base (handle) {}

			[SupportedOSPlatform ("macos")]
			[SupportedOSPlatform ("ios")]
			[SupportedOSPlatform ("tvos")]
			[SupportedOSPlatform ("maccatalyst13.1")]
			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			public virtual partial bool ContainsAttachments
			{
				[SupportedOSPlatform ("macos")]
				[SupportedOSPlatform ("ios")]
				[SupportedOSPlatform ("tvos")]
				[SupportedOSPlatform ("maccatalyst13.1")]
				get
				{
					bool ret;
					if (IsDirectBinding) {
						ret = global::ObjCRuntime.Messaging.bool_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("containsAttachments")) != 0;
					} else {
						ret = global::ObjCRuntime.Messaging.bool_objc_msgSendSuper (this.SuperHandle, global::ObjCRuntime.Selector.GetHandle ("containsAttachments")) != 0;
					}
					global::System.GC.KeepAlive (this);
					return ret;
				}

				[SupportedOSPlatform ("macos")]
				[SupportedOSPlatform ("ios")]
				[SupportedOSPlatform ("tvos")]
				[SupportedOSPlatform ("maccatalyst13.1")]
				set
				{
					if (IsDirectBinding) {
						global::ObjCRuntime.Messaging.void_objc_msgSend_bool (this.Handle, global::ObjCRuntime.Selector.GetHandle ("setContainsAttachments:"), value ? (byte) 1 : (byte) 0);
					} else {
						global::ObjCRuntime.Messaging.void_objc_msgSendSuper_bool (this.SuperHandle, global::ObjCRuntime.Selector.GetHandle ("setContainsAttachments:"), value ? (byte) 1 : (byte) 0);
					}
					global::System.GC.KeepAlive (this);
				}
			}

			[SupportedOSPlatform ("macos")]
			[SupportedOSPlatform ("ios")]
			[SupportedOSPlatform ("tvos")]
			[SupportedOSPlatform ("maccatalyst13.1")]
			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			public virtual partial global::System.UIntPtr Count
			{
				[SupportedOSPlatform ("macos")]
				[SupportedOSPlatform ("ios")]
				[SupportedOSPlatform ("tvos")]
				[SupportedOSPlatform ("maccatalyst13.1")]
				get
				{
					global::System.UIntPtr ret;
					if (IsDirectBinding) {
						ret = global::ObjCRuntime.Messaging.UIntPtr_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("count"));
					} else {
						ret = global::ObjCRuntime.Messaging.UIntPtr_objc_msgSendSuper (this.SuperHandle, global::ObjCRuntime.Selector.GetHandle ("count"));
					}
					global::System.GC.KeepAlive (this);
					return ret;
				}

				[SupportedOSPlatform ("macos")]
				[SupportedOSPlatform ("ios")]
				[SupportedOSPlatform ("tvos")]
				[SupportedOSPlatform ("maccatalyst13.1")]
				set
				{
					if (IsDirectBinding) {
						global::ObjCRuntime.Messaging.void_objc_msgSend_UIntPtr (this.Handle, global::ObjCRuntime.Selector.GetHandle ("setCount:"), value);
					} else {
						global::ObjCRuntime.Messaging.void_objc_msgSendSuper_UIntPtr (this.SuperHandle, global::ObjCRuntime.Selector.GetHandle ("setCount:"), value);
					}
					global::System.GC.KeepAlive (this);
				}
			}

			[SupportedOSPlatform ("macos")]
			[SupportedOSPlatform ("ios")]
			[SupportedOSPlatform ("tvos")]
			[SupportedOSPlatform ("maccatalyst13.1")]
			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			public virtual partial global::System.Runtime.InteropServices.NFloat LineSpacing
			{
				[SupportedOSPlatform ("macos")]
				[SupportedOSPlatform ("ios")]
				[SupportedOSPlatform ("tvos")]
				[SupportedOSPlatform ("maccatalyst13.1")]
				get
				{
					global::System.Runtime.InteropServices.NFloat ret;
					if (IsDirectBinding) {
						ret = global::ObjCRuntime.Messaging.nfloat_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("lineSpacing"));
					} else {
						ret = global::ObjCRuntime.Messaging.nfloat_objc_msgSendSuper (this.SuperHandle, global::ObjCRuntime.Selector.GetHandle ("lineSpacing"));
					}
					global::System.GC.KeepAlive (this);
					return ret;
				}

				[SupportedOSPlatform ("macos")]
				[SupportedOSPlatform ("ios")]
				[SupportedOSPlatform ("tvos")]
				[SupportedOSPlatform ("maccatalyst13.1")]
				set
				{
					if (IsDirectBinding) {
						global::ObjCRuntime.Messaging.void_objc_msgSend_nfloat (this.Handle, global::ObjCRuntime.Selector.GetHandle ("setLineSpacing:"), value);
					} else {
						global::ObjCRuntime.Messaging.void_objc_msgSendSuper_nfloat (this.SuperHandle, global::ObjCRuntime.Selector.GetHandle ("setLineSpacing:"), value);
					}
					global::System.GC.KeepAlive (this);
				}
			}

			[SupportedOSPlatform ("macos")]
			[SupportedOSPlatform ("ios")]
			[SupportedOSPlatform ("tvos")]
			[SupportedOSPlatform ("maccatalyst13.1")]
			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			public virtual partial global::System.UIntPtr[] Sizes
			{
				[SupportedOSPlatform ("macos")]
				[SupportedOSPlatform ("ios")]
				[SupportedOSPlatform ("tvos")]
				[SupportedOSPlatform ("maccatalyst13.1")]
				get
				{
					global::System.UIntPtr[] ret;
					if (IsDirectBinding) {
						ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("sizes"));
					} else {
						ret = global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper (this.SuperHandle, global::ObjCRuntime.Selector.GetHandle ("sizes"));
					}
					global::System.GC.KeepAlive (this);
					return ret;
				}

				[SupportedOSPlatform ("macos")]
				[SupportedOSPlatform ("ios")]
				[SupportedOSPlatform ("tvos")]
				[SupportedOSPlatform ("maccatalyst13.1")]
				set
				{
					if (value is null)
						global::ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (value));
					if (IsDirectBinding) {
						global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle (this.Handle, global::ObjCRuntime.Selector.GetHandle ("setSizes:"), value);
					} else {
						global::ObjCRuntime.Messaging.void_objc_msgSendSuper_NativeHandle (this.SuperHandle, global::ObjCRuntime.Selector.GetHandle ("setSizes:"), value);
					}
					global::System.GC.KeepAlive (this);
				}
			}

			[SupportedOSPlatform ("macos")]
			[SupportedOSPlatform ("ios")]
			[SupportedOSPlatform ("tvos")]
			[SupportedOSPlatform ("maccatalyst13.1")]
			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			public virtual unsafe partial static global::Foundation.NSArray FromFile (string path)
			{
				if (path is null)
					global::ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (path));
				var nspath = global::CoreFoundation.CFString.CreateNative (path);
				global::Foundation.NSArray ret;
				if (IsDirectBinding) {
					ret = global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSArray> (global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend_NativeHandle (this.Handle, global::ObjCRuntime.Selector.GetHandle ("arrayWithContentsOfFile:"), nspath))!;
				} else {
					ret = global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSArray> (global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper_NativeHandle (this.SuperHandle, global::ObjCRuntime.Selector.GetHandle ("arrayWithContentsOfFile:"), nspath))!;
				}
				global::System.GC.KeepAlive (this);
				global::CoreFoundation.CFString.ReleaseNative (nspath);
				return ret;
			}

			[SupportedOSPlatform ("macos")]
			[SupportedOSPlatform ("ios")]
			[SupportedOSPlatform ("tvos")]
			[SupportedOSPlatform ("maccatalyst13.1")]
			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			public virtual unsafe partial void SetValueForKey (global::Foundation.NSObject value, global::Foundation.NSString key)
			{
				var value__handle__ = value!.GetNonNullHandle (nameof (value));
				var key__handle__ = key!.GetNonNullHandle (nameof (key));
				if (IsDirectBinding) {
					global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle_NativeHandle (this.Handle, global::ObjCRuntime.Selector.GetHandle ("setValue:forKey:"), value__handle__, key__handle__);
				} else {
					global::ObjCRuntime.Messaging.void_objc_msgSendSuper_NativeHandle_NativeHandle (this.SuperHandle, global::ObjCRuntime.Selector.GetHandle ("setValue:forKey:"), value__handle__, key__handle__);
				}
				global::System.GC.KeepAlive (this);
				global::System.GC.KeepAlive (value);
				global::System.GC.KeepAlive (key);
			}

			[SupportedOSPlatform ("macos")]
			[SupportedOSPlatform ("ios")]
			[SupportedOSPlatform ("tvos")]
			[SupportedOSPlatform ("maccatalyst13.1")]
			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			public virtual unsafe partial global::Foundation.NSArray Sort (global::Foundation.NSComparator cmptr)
			{
				if (cmptr is null)
					global::ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (cmptr));
				using var block_cmptr = global::ObjCRuntime.Trampolines.SDNSComparator.CreateNullableBlock (cmptr);
				global::ObjCRuntime.BlockLiteral* block_ptr_cmptr = cmptr is not null ? &block_cmptr : null;
				global::Foundation.NSArray ret;
				if (IsDirectBinding) {
					ret = global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSArray> (global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend_NativeHandle (this.Handle, global::ObjCRuntime.Selector.GetHandle ("sortedArrayUsingComparator:"), (global::ObjCRuntime.NativeHandle) block_ptr_cmptr))!;
				} else {
					ret = global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSArray> (global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper_NativeHandle (this.SuperHandle, global::ObjCRuntime.Selector.GetHandle ("sortedArrayUsingComparator:"), (global::ObjCRuntime.NativeHandle) block_ptr_cmptr))!;
				}
				global::System.GC.KeepAlive (this);
				return ret;
			}

			[SupportedOSPlatform ("macos")]
			[SupportedOSPlatform ("ios")]
			[SupportedOSPlatform ("tvos")]
			[SupportedOSPlatform ("maccatalyst13.1")]
			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			public virtual unsafe partial global::Foundation.NSObject ValueForKey (global::Foundation.NSString key)
			{
				var key__handle__ = key!.GetNonNullHandle (nameof (key));
				global::Foundation.NSObject ret;
				if (IsDirectBinding) {
					ret = global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSObject> (global::ObjCRuntime.Messaging.xamarin_NativeHandle_objc_msgSend_NativeHandle_exception (this.Handle, global::ObjCRuntime.Selector.GetHandle ("valueForKey:"), key__handle__))!;
				} else {
					ret = global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSObject> (global::ObjCRuntime.Messaging.xamarin_NativeHandle_objc_msgSendSuper_NativeHandle_exception (this.SuperHandle, global::ObjCRuntime.Selector.GetHandle ("valueForKey:"), key__handle__))!;
				}
				global::System.GC.KeepAlive (this);
				global::System.GC.KeepAlive (key);
				return ret;
			}

			[SupportedOSPlatform ("macos")]
			[SupportedOSPlatform ("ios")]
			[SupportedOSPlatform ("tvos")]
			[SupportedOSPlatform ("maccatalyst13.1")]
			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			public virtual unsafe partial bool WriteToFile (string path, bool useAuxiliaryFile)
			{
				if (path is null)
					global::ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (path));
				var nspath = global::CoreFoundation.CFString.CreateNative (path);
				bool ret;
				if (IsDirectBinding) {
					ret = global::ObjCRuntime.Messaging.bool_objc_msgSend_NativeHandle_bool (this.Handle, global::ObjCRuntime.Selector.GetHandle ("writeToFile:atomically:"), nspath, useAuxiliaryFile ? (byte) 1 : (byte) 0) != 0;
				} else {
					ret = global::ObjCRuntime.Messaging.bool_objc_msgSendSuper_NativeHandle_bool (this.SuperHandle, global::ObjCRuntime.Selector.GetHandle ("writeToFile:atomically:"), nspath, useAuxiliaryFile ? (byte) 1 : (byte) 0) != 0;
				}
				global::System.GC.KeepAlive (this);
				global::CoreFoundation.CFString.ReleaseNative (nspath);
				return ret;
			}

		}
	}
}
