// <auto-generated />

#nullable enable

using AVFoundation;
using CoreGraphics;
using Foundation;
using ObjCBindings;
using ObjCRuntime;
using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Drawing;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;
using System.Threading.Tasks;

namespace TestNamespace;

[SupportedOSPlatform ("macos")]
[SupportedOSPlatform ("ios")]
[SupportedOSPlatform ("tvos")]
[SupportedOSPlatform ("maccatalyst13.1")]
[Register ("MethodTests", true)]
public partial class MethodTests
{
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selValueForKey_X = "valueForKey:";
	static readonly global::ObjCRuntime.NativeHandle selValueForKey_XHandle = global::ObjCRuntime.Selector.GetHandle ("valueForKey:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSetValue_ForKey_X = "setValue:forKey:";
	static readonly global::ObjCRuntime.NativeHandle selSetValue_ForKey_XHandle = global::ObjCRuntime.Selector.GetHandle ("setValue:forKey:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selWriteToFile_Atomically_X = "writeToFile:atomically:";
	static readonly global::ObjCRuntime.NativeHandle selWriteToFile_Atomically_XHandle = global::ObjCRuntime.Selector.GetHandle ("writeToFile:atomically:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selArrayWithContentsOfFile_X = "arrayWithContentsOfFile:";
	static readonly global::ObjCRuntime.NativeHandle selArrayWithContentsOfFile_XHandle = global::ObjCRuntime.Selector.GetHandle ("arrayWithContentsOfFile:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selSortedArrayUsingComparator_X = "sortedArrayUsingComparator:";
	static readonly global::ObjCRuntime.NativeHandle selSortedArrayUsingComparator_XHandle = global::ObjCRuntime.Selector.GetHandle ("sortedArrayUsingComparator:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selFilteredArrayUsingPredicate_X = "filteredArrayUsingPredicate:";
	static readonly global::ObjCRuntime.NativeHandle selFilteredArrayUsingPredicate_XHandle = global::ObjCRuntime.Selector.GetHandle ("filteredArrayUsingPredicate:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selFilteredArrayUsingStrings_X = "filteredArrayUsingStrings:";
	static readonly global::ObjCRuntime.NativeHandle selFilteredArrayUsingStrings_XHandle = global::ObjCRuntime.Selector.GetHandle ("filteredArrayUsingStrings:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selLoadFromHTMLWithRequest_Options_CompletionHandler_X = "loadFromHTMLWithRequest:options:completionHandler:";
	static readonly global::ObjCRuntime.NativeHandle selLoadFromHTMLWithRequest_Options_CompletionHandler_XHandle = global::ObjCRuntime.Selector.GetHandle ("loadFromHTMLWithRequest:options:completionHandler:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selCompleteRequestReturningItems_CompletionHandler_X = "completeRequestReturningItems:completionHandler:";
	static readonly global::ObjCRuntime.NativeHandle selCompleteRequestReturningItems_CompletionHandler_XHandle = global::ObjCRuntime.Selector.GetHandle ("completeRequestReturningItems:completionHandler:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selBookmarkDataWithContentsOfURL_Error_X = "bookmarkDataWithContentsOfURL:error:";
	static readonly global::ObjCRuntime.NativeHandle selBookmarkDataWithContentsOfURL_Error_XHandle = global::ObjCRuntime.Selector.GetHandle ("bookmarkDataWithContentsOfURL:error:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	const string selBookmarkDataWithContentsOfURL_Subdomain_Error_X = "bookmarkDataWithContentsOfURL:subdomain:error:";
	static readonly global::ObjCRuntime.NativeHandle selBookmarkDataWithContentsOfURL_Subdomain_Error_XHandle = global::ObjCRuntime.Selector.GetHandle ("bookmarkDataWithContentsOfURL:subdomain:error:");

	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	static readonly global::ObjCRuntime.NativeHandle class_ptr = global::ObjCRuntime.Class.GetHandle ("MethodTests");

	/// <summary>The Objective-C class handle for this class.</summary>
	/// <value>The pointer to the Objective-C class.</value>
	/// <remarks>
	///     Each managed class mirrors an unmanaged Objective-C class.
	///     This value contains the pointer to the Objective-C class.
	///     It is similar to calling the managed <see cref=\"ObjCRuntime.Class.GetHandle(string)\" /> or the native <see href=\"https://developer.apple.com/documentation/objectivec/1418952-objc_getclass\">objc_getClass</see> method with the type name.
	/// </remarks>
	public override global::ObjCRuntime.NativeHandle ClassHandle => class_ptr;

	/// <summary>Creates a new <see cref="MethodTests" /> with default values.</summary>
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[DesignatedInitializer]
	[Export ("init")]
	public MethodTests () : base (global::Foundation.NSObjectFlag.Empty)
	{
		if (IsDirectBinding)
			InitializeHandle (global::ObjCRuntime.Messaging.IntPtr_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("init")), "init");
		else
			InitializeHandle (global::ObjCRuntime.Messaging.IntPtr_objc_msgSendSuper (this.SuperHandle, global::ObjCRuntime.Selector.GetHandle ("init")), "init");
	}

	/// <summary>Constructor to call on derived classes to skip initialization and merely allocate the object.</summary>
	/// <param name="t">Unused sentinel value, pass NSObjectFlag.Empty.</param>
	/// <remarks>
	///     <para>
	///         This constructor should be called by derived classes when they completely construct the object in managed code and merely want the runtime to allocate and initialize the <see cref="Foundation.NSObject" />.
	///         This is required to implement the two-step initialization process that Objective-C uses, the first step is to perform the object allocation, the second step is to initialize the object.
	///         When developers invoke this constructor, they take advantage of a direct path that goes all the way up to <see cref="Foundation.NSObject" /> to merely allocate the object's memory and bind the Objective-C and C# objects together.
	///         The actual initialization of the object is up to the developer.
	///     </para>
	///     <para>
	///         This constructor is typically used by the binding generator to allocate the object, but prevent the actual initialization to take place.
	///         Once the allocation has taken place, the constructor has to initialize the object.
	///         With constructors generated by the binding generator this means that it manually invokes one of the "init" methods to initialize the object.
	///     </para>
	///     <para>It is the developer's responsibility to completely initialize the object if they chain up using this constructor chain.</para>
	///     <para>
	///         In general, if the developer's constructor invokes the corresponding base implementation, then it should also call an Objective-C init method.
	///         If this is not the case, developers should instead chain to the proper constructor in their class.
	///     </para>
	///     <para>
	///         The argument value is ignored and merely ensures that the only code that is executed is the construction phase is the basic <see cref="Foundation.NSObject" /> allocation and runtime type registration.
	///         Typically the chaining would look like this:
	///     </para>
	///     <example>
	///             <code lang="csharp lang-csharp"><![CDATA[
	/// //
	/// // The NSObjectFlag constructor merely allocates the object and registers the C# class with the Objective-C runtime if necessary.
	/// // No actual initXxx method is invoked, that is done later in the constructor
	/// //
	/// // This is taken from the iOS SDK's source code for the UIView class:
	/// //
	/// [Export ("initWithFrame:")]
	/// public UIView (System.Drawing.RectangleF frame) : base (NSObjectFlag.Empty)
	/// {
	///     // Invoke the init method now.
	///     var initWithFrame = new Selector ("initWithFrame:").Handle;
	///     if (IsDirectBinding) {
	///         Handle = ObjCRuntime.Messaging.IntPtr_objc_msgSend_CGRect (this.Handle, initWithFrame, frame);
	///     } else {
	///         Handle = ObjCRuntime.Messaging.IntPtr_objc_msgSendSuper_CGRect (this.SuperHandle, initWithFrame, frame);
	///     }
	/// }
	/// ]]></code>
	///     </example>
	/// </remarks>
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[EditorBrowsable (EditorBrowsableState.Advanced)]
	protected MethodTests (global::Foundation.NSObjectFlag t) : base (t) {}

	/// <summary>A constructor used when creating managed representations of unmanaged objects. Called by the runtime.</summary>
	/// <param name="handle">Pointer (handle) to the unmanaged object.</param>
	/// <remarks>
	///     <para>
	///         This constructor is invoked by the runtime infrastructure (<see cref="ObjCRuntime.Runtime.GetNSObject(System.IntPtr)" />) to create a new managed representation for a pointer to an unmanaged Objective-C object.
	///         Developers should not invoke this method directly, instead they should call <see cref="ObjCRuntime.Runtime.GetNSObject(System.IntPtr)" /> as it will prevent two instances of a managed object pointing to the same native object.
	///     </para>
	/// </remarks>
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[EditorBrowsable (EditorBrowsableState.Advanced)]
	protected internal MethodTests (global::ObjCRuntime.NativeHandle handle) : base (handle) {}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public virtual unsafe partial void CompleteRequest (global::Foundation.NSExtensionItem[] returningItems, global::System.Action<bool>? completionHandler)
	{
		if (returningItems is null)
			global::ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (returningItems));
		using var nsa_returningItems = global::Foundation.NSArray.FromNSObjects (returningItems);
		using var block_completionHandler = global::ObjCRuntime.Trampolines.SDActionArity1bool.CreateNullableBlock (completionHandler);
		global::ObjCRuntime.BlockLiteral* block_ptr_completionHandler = completionHandler is not null ? &block_completionHandler : null;
		if (IsDirectBinding) {
			global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle_NativeHandle (this.Handle, global::ObjCRuntime.Selector.GetHandle ("completeRequestReturningItems:completionHandler:"), nsa_returningItems.Handle, (global::ObjCRuntime.NativeHandle) block_ptr_completionHandler);
		} else {
			global::ObjCRuntime.Messaging.void_objc_msgSendSuper_NativeHandle_NativeHandle (this.SuperHandle, global::ObjCRuntime.Selector.GetHandle ("completeRequestReturningItems:completionHandler:"), nsa_returningItems.Handle, (global::ObjCRuntime.NativeHandle) block_ptr_completionHandler);
		}
		global::System.GC.KeepAlive (this);
		global::System.GC.KeepAlive (nsa_returningItems);
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public virtual global::System.Threading.Tasks.Task<bool> CompleteRequestAsync (global::Foundation.NSExtensionItem[] returningItems)
	{
		global::System.Threading.Tasks.TaskCompletionSource<bool> _tcs = new ();
		CompleteRequest (returningItems, (_cbobj) => {
			_tcs.SetResult (_cbobj);
		});
		return _tcs.Task;
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public virtual unsafe partial void CompleteRequest (global::Foundation.NSExtensionItem[] returningItems, global::System.Action<bool, string?>? completionHandler)
	{
		if (returningItems is null)
			global::ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (returningItems));
		using var nsa_returningItems = global::Foundation.NSArray.FromNSObjects (returningItems);
		using var block_completionHandler = global::ObjCRuntime.Trampolines.SDActionArity2boolstring?.CreateNullableBlock (completionHandler);
		global::ObjCRuntime.BlockLiteral* block_ptr_completionHandler = completionHandler is not null ? &block_completionHandler : null;
		if (IsDirectBinding) {
			global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle_NativeHandle (this.Handle, global::ObjCRuntime.Selector.GetHandle ("completeRequestReturningItems:completionHandler:"), nsa_returningItems.Handle, (global::ObjCRuntime.NativeHandle) block_ptr_completionHandler);
		} else {
			global::ObjCRuntime.Messaging.void_objc_msgSendSuper_NativeHandle_NativeHandle (this.SuperHandle, global::ObjCRuntime.Selector.GetHandle ("completeRequestReturningItems:completionHandler:"), nsa_returningItems.Handle, (global::ObjCRuntime.NativeHandle) block_ptr_completionHandler);
		}
		global::System.GC.KeepAlive (this);
		global::System.GC.KeepAlive (nsa_returningItems);
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public virtual global::System.Threading.Tasks.Task<(bool, string?)> CompleteRequestAsync (global::Foundation.NSExtensionItem[] returningItems)
	{
		global::System.Threading.Tasks.TaskCompletionSource<(bool, string?)> _tcs = new ();
		CompleteRequest (returningItems, (_cbarg1, _cbarg2) => {
			_tcs.SetResult (new (_cbarg1, _cbarg2));
		});
		return _tcs.Task;
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public virtual unsafe partial void CompleteRequest (global::Foundation.NSExtensionItem[] returningItems, global::System.Action<bool, string, string?>? completionHandler)
	{
		if (returningItems is null)
			global::ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (returningItems));
		using var nsa_returningItems = global::Foundation.NSArray.FromNSObjects (returningItems);
		using var block_completionHandler = global::ObjCRuntime.Trampolines.SDActionArity3boolstringstring?.CreateNullableBlock (completionHandler);
		global::ObjCRuntime.BlockLiteral* block_ptr_completionHandler = completionHandler is not null ? &block_completionHandler : null;
		if (IsDirectBinding) {
			global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle_NativeHandle (this.Handle, global::ObjCRuntime.Selector.GetHandle ("completeRequestReturningItems:completionHandler:"), nsa_returningItems.Handle, (global::ObjCRuntime.NativeHandle) block_ptr_completionHandler);
		} else {
			global::ObjCRuntime.Messaging.void_objc_msgSendSuper_NativeHandle_NativeHandle (this.SuperHandle, global::ObjCRuntime.Selector.GetHandle ("completeRequestReturningItems:completionHandler:"), nsa_returningItems.Handle, (global::ObjCRuntime.NativeHandle) block_ptr_completionHandler);
		}
		global::System.GC.KeepAlive (this);
		global::System.GC.KeepAlive (nsa_returningItems);
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public virtual global::System.Threading.Tasks.Task<(bool Success, string Name, string? Surname)> CompleteRequestAsync (global::Foundation.NSExtensionItem[] returningItems)
	{
		global::System.Threading.Tasks.TaskCompletionSource<(bool Success, string Name, string? Surname)> _tcs = new ();
		CompleteRequest (returningItems, (_cbarg1, _cbarg2, _cbarg3) => {
			_tcs.SetResult (new (_cbarg1, _cbarg2, _cbarg3));
		});
		return _tcs.Task;
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public virtual unsafe partial global::Foundation.NSArray Filter (global::Foundation.NSPredicate predicate)
	{
		var predicate__handle__ = predicate!.GetNonNullHandle (nameof (predicate));
		global::Foundation.NSArray ret;
		if (IsDirectBinding) {
			ret = global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSArray> (global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend_NativeHandle (this.Handle, global::ObjCRuntime.Selector.GetHandle ("filteredArrayUsingPredicate:"), predicate__handle__))!;
		} else {
			ret = global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSArray> (global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper_NativeHandle (this.SuperHandle, global::ObjCRuntime.Selector.GetHandle ("filteredArrayUsingPredicate:"), predicate__handle__))!;
		}
		global::System.GC.KeepAlive (this);
		global::System.GC.KeepAlive (predicate);
		return ret;
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public virtual unsafe partial global::Foundation.NSArray FilterStrings (string[] predicate)
	{
		if (predicate is null)
			global::ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (predicate));
		using var nsa_predicate = global::Foundation.NSArray.FromStrings (predicate);
		global::Foundation.NSArray ret;
		if (IsDirectBinding) {
			ret = global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSArray> (global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend_NativeHandle (this.Handle, global::ObjCRuntime.Selector.GetHandle ("filteredArrayUsingStrings:"), nsa_predicate.Handle))!;
		} else {
			ret = global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSArray> (global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper_NativeHandle (this.SuperHandle, global::ObjCRuntime.Selector.GetHandle ("filteredArrayUsingStrings:"), nsa_predicate.Handle))!;
		}
		global::System.GC.KeepAlive (this);
		global::System.GC.KeepAlive (nsa_predicate);
		return ret;
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public virtual unsafe partial static global::Foundation.NSArray FromFile (string path)
	{
		if (path is null)
			global::ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (path));
		var nspath = global::CoreFoundation.CFString.CreateNative (path);
		global::Foundation.NSArray ret;
		if (IsDirectBinding) {
			ret = global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSArray> (global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend_NativeHandle (this.Handle, global::ObjCRuntime.Selector.GetHandle ("arrayWithContentsOfFile:"), nspath))!;
		} else {
			ret = global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSArray> (global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper_NativeHandle (this.SuperHandle, global::ObjCRuntime.Selector.GetHandle ("arrayWithContentsOfFile:"), nspath))!;
		}
		global::System.GC.KeepAlive (this);
		global::CoreFoundation.CFString.ReleaseNative (nspath);
		return ret;
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public static unsafe partial global::Foundation.NSData GetBookmarkData (global::Foundation.NSUrl bookmarkFileUrl, out global::Foundation.NSError? error)
	{
		var bookmarkFileUrl__handle__ = bookmarkFileUrl!.GetNonNullHandle (nameof (bookmarkFileUrl));
		global::ObjCRuntime.NativeHandle error__handle__;
		global::Foundation.NSData ret;
		if (IsDirectBinding) {
			ret = global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSData> (global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend_NativeHandle_NativeHandle (this.Handle, global::ObjCRuntime.Selector.GetHandle ("bookmarkDataWithContentsOfURL:error:"), bookmarkFileUrl__handle__, &error__handle__))!;
		} else {
			ret = global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSData> (global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper_NativeHandle_NativeHandle (this.SuperHandle, global::ObjCRuntime.Selector.GetHandle ("bookmarkDataWithContentsOfURL:error:"), bookmarkFileUrl__handle__, &error__handle__))!;
		}
		global::System.GC.KeepAlive (this);
		global::System.GC.KeepAlive (bookmarkFileUrl);
		error = global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSError> (error__handle__);
		return ret;
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public static unsafe partial global::Foundation.NSData GetBookmarkData (global::Foundation.NSUrl bookmarkFileUrl, string subdomain, out global::Foundation.NSError? error)
	{
		if (subdomain is null)
			global::ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (subdomain));
		var bookmarkFileUrl__handle__ = bookmarkFileUrl!.GetNonNullHandle (nameof (bookmarkFileUrl));
		var nssubdomain = global::CoreFoundation.CFString.CreateNative (subdomain);
		global::ObjCRuntime.NativeHandle error__handle__;
		global::Foundation.NSData ret;
		if (IsDirectBinding) {
			ret = global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSData> (global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend_NativeHandle_NativeHandle_NativeHandle (this.Handle, global::ObjCRuntime.Selector.GetHandle ("bookmarkDataWithContentsOfURL:subdomain:error:"), bookmarkFileUrl__handle__, nssubdomain, &error__handle__))!;
		} else {
			ret = global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSData> (global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper_NativeHandle_NativeHandle_NativeHandle (this.SuperHandle, global::ObjCRuntime.Selector.GetHandle ("bookmarkDataWithContentsOfURL:subdomain:error:"), bookmarkFileUrl__handle__, nssubdomain, &error__handle__))!;
		}
		global::System.GC.KeepAlive (this);
		global::System.GC.KeepAlive (bookmarkFileUrl);
		global::CoreFoundation.CFString.ReleaseNative (nssubdomain);
		error = global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSError> (error__handle__);
		return ret;
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[UnsupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial static void LoadFromHtml (global::Foundation.NSUrlRequest request, global::Foundation.NSDictionary options, global::Foundation.NSAttributedStringCompletionHandler completionHandler)
	{
		if (completionHandler is null)
			global::ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (completionHandler));
		var request__handle__ = request!.GetNonNullHandle (nameof (request));
		var options__handle__ = options!.GetNonNullHandle (nameof (options));
		using var block_completionHandler = global::ObjCRuntime.Trampolines.SDNSAttributedStringCompletionHandler.CreateNullableBlock (completionHandler);
		global::ObjCRuntime.BlockLiteral* block_ptr_completionHandler = completionHandler is not null ? &block_completionHandler : null;
		if (IsDirectBinding) {
			global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle_NativeHandle_NativeHandle (this.Handle, global::ObjCRuntime.Selector.GetHandle ("loadFromHTMLWithRequest:options:completionHandler:"), request__handle__, options__handle__, (global::ObjCRuntime.NativeHandle) block_ptr_completionHandler);
		} else {
			global::ObjCRuntime.Messaging.void_objc_msgSendSuper_NativeHandle_NativeHandle_NativeHandle (this.SuperHandle, global::ObjCRuntime.Selector.GetHandle ("loadFromHTMLWithRequest:options:completionHandler:"), request__handle__, options__handle__, (global::ObjCRuntime.NativeHandle) block_ptr_completionHandler);
		}
		global::System.GC.KeepAlive (this);
		global::System.GC.KeepAlive (request);
		global::System.GC.KeepAlive (options);
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[UnsupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public static global::System.Threading.Tasks.Task<NSLoadFromHtmlResult> LoadFromHtmlAsync (global::Foundation.NSUrlRequest request, global::Foundation.NSDictionary options)
	{
		global::System.Threading.Tasks.TaskCompletionSource<NSLoadFromHtmlResult> _tcs = new ();
		LoadFromHtml (request, options, (_cbattributedString, _cbattributes, _cberror) => {
			if (_cberror is not null)
				_tcs.SetException (new global::Foundation.NSErrorException (_cberror));
			else
				_tcs.SetResult (new (_cbattributedString, _cbattributes));
		});
		return _tcs.Task;
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[UnsupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public partial static void LoadFromHtmlNoName (global::Foundation.NSUrlRequest request, global::Foundation.NSDictionary options, global::Foundation.NSAttributedStringCompletionHandler completionHandler)
	{
		if (completionHandler is null)
			global::ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (completionHandler));
		var request__handle__ = request!.GetNonNullHandle (nameof (request));
		var options__handle__ = options!.GetNonNullHandle (nameof (options));
		using var block_completionHandler = global::ObjCRuntime.Trampolines.SDNSAttributedStringCompletionHandler.CreateNullableBlock (completionHandler);
		global::ObjCRuntime.BlockLiteral* block_ptr_completionHandler = completionHandler is not null ? &block_completionHandler : null;
		if (IsDirectBinding) {
			global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle_NativeHandle_NativeHandle (this.Handle, global::ObjCRuntime.Selector.GetHandle ("loadFromHTMLWithRequest:options:completionHandler:"), request__handle__, options__handle__, (global::ObjCRuntime.NativeHandle) block_ptr_completionHandler);
		} else {
			global::ObjCRuntime.Messaging.void_objc_msgSendSuper_NativeHandle_NativeHandle_NativeHandle (this.SuperHandle, global::ObjCRuntime.Selector.GetHandle ("loadFromHTMLWithRequest:options:completionHandler:"), request__handle__, options__handle__, (global::ObjCRuntime.NativeHandle) block_ptr_completionHandler);
		}
		global::System.GC.KeepAlive (this);
		global::System.GC.KeepAlive (request);
		global::System.GC.KeepAlive (options);
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[UnsupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public static global::System.Threading.Tasks.Task<(global::Foundation.NSAttributedString? AttributedString, global::Foundation.NSDictionary<global::Foundation.NSString, global::Foundation.NSObject>? Attributes)> LoadFromHtmlNoNameAsync (global::Foundation.NSUrlRequest request, global::Foundation.NSDictionary options)
	{
		global::System.Threading.Tasks.TaskCompletionSource<(global::Foundation.NSAttributedString? AttributedString, global::Foundation.NSDictionary<global::Foundation.NSString, global::Foundation.NSObject>? Attributes)> _tcs = new ();
		LoadFromHtmlNoName (request, options, (_cbattributedString, _cbattributes, _cberror) => {
			if (_cberror is not null)
				_tcs.SetException (new global::Foundation.NSErrorException (_cberror));
			else
				_tcs.SetResult (new (_cbattributedString, _cbattributes));
		});
		return _tcs.Task;
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public virtual unsafe partial void SetValueForKey (global::Foundation.NSObject value, global::Foundation.NSString key)
	{
		var value__handle__ = value!.GetNonNullHandle (nameof (value));
		var key__handle__ = key!.GetNonNullHandle (nameof (key));
		if (IsDirectBinding) {
			global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle_NativeHandle (this.Handle, global::ObjCRuntime.Selector.GetHandle ("setValue:forKey:"), value__handle__, key__handle__);
		} else {
			global::ObjCRuntime.Messaging.void_objc_msgSendSuper_NativeHandle_NativeHandle (this.SuperHandle, global::ObjCRuntime.Selector.GetHandle ("setValue:forKey:"), value__handle__, key__handle__);
		}
		global::System.GC.KeepAlive (this);
		global::System.GC.KeepAlive (value);
		global::System.GC.KeepAlive (key);
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public virtual unsafe partial global::Foundation.NSArray Sort (global::Foundation.NSComparator cmptr)
	{
		if (cmptr is null)
			global::ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (cmptr));
		using var block_cmptr = global::ObjCRuntime.Trampolines.SDNSComparator.CreateNullableBlock (cmptr);
		global::ObjCRuntime.BlockLiteral* block_ptr_cmptr = cmptr is not null ? &block_cmptr : null;
		global::Foundation.NSArray ret;
		if (IsDirectBinding) {
			ret = global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSArray> (global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend_NativeHandle (this.Handle, global::ObjCRuntime.Selector.GetHandle ("sortedArrayUsingComparator:"), (global::ObjCRuntime.NativeHandle) block_ptr_cmptr))!;
		} else {
			ret = global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSArray> (global::ObjCRuntime.Messaging.NativeHandle_objc_msgSendSuper_NativeHandle (this.SuperHandle, global::ObjCRuntime.Selector.GetHandle ("sortedArrayUsingComparator:"), (global::ObjCRuntime.NativeHandle) block_ptr_cmptr))!;
		}
		global::System.GC.KeepAlive (this);
		return ret;
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public virtual unsafe partial global::Foundation.NSObject ValueForKey (global::Foundation.NSString key)
	{
		var key__handle__ = key!.GetNonNullHandle (nameof (key));
		global::Foundation.NSObject ret;
		if (IsDirectBinding) {
			ret = global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSObject> (global::ObjCRuntime.Messaging.xamarin_NativeHandle_objc_msgSend_NativeHandle_exception (this.Handle, global::ObjCRuntime.Selector.GetHandle ("valueForKey:"), key__handle__))!;
		} else {
			ret = global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSObject> (global::ObjCRuntime.Messaging.xamarin_NativeHandle_objc_msgSendSuper_NativeHandle_exception (this.SuperHandle, global::ObjCRuntime.Selector.GetHandle ("valueForKey:"), key__handle__))!;
		}
		global::System.GC.KeepAlive (this);
		global::System.GC.KeepAlive (key);
		return ret;
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public virtual unsafe partial bool WriteToFile (string path, bool useAuxiliaryFile)
	{
		if (path is null)
			global::ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (path));
		var nspath = global::CoreFoundation.CFString.CreateNative (path);
		bool ret;
		if (IsDirectBinding) {
			ret = global::ObjCRuntime.Messaging.bool_objc_msgSend_NativeHandle_bool (this.Handle, global::ObjCRuntime.Selector.GetHandle ("writeToFile:atomically:"), nspath, useAuxiliaryFile ? (byte) 1 : (byte) 0) != 0;
		} else {
			ret = global::ObjCRuntime.Messaging.bool_objc_msgSendSuper_NativeHandle_bool (this.SuperHandle, global::ObjCRuntime.Selector.GetHandle ("writeToFile:atomically:"), nspath, useAuxiliaryFile ? (byte) 1 : (byte) 0) != 0;
		}
		global::System.GC.KeepAlive (this);
		global::CoreFoundation.CFString.ReleaseNative (nspath);
		return ret;
	}
}
