// <auto-generated />

#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Foundation;

namespace TestNamespace;

public partial class NSLoadFromHtmlResult
{

	public global::Foundation.NSAttributedString? AttributedString { get; set; }

	public global::Foundation.NSDictionary<global::Foundation.NSString, global::Foundation.NSObject>? Attributes { get; set; }

	partial void Initialize ();

	public NSLoadFromHtmlResult (global::Foundation.NSAttributedString? attributedString, global::Foundation.NSDictionary<global::Foundation.NSString, global::Foundation.NSObject>? attributes)
	{
		this.AttributedString = attributedString;
		this.Attributes = attributes;
		Initialize ();
	}
}
