// <auto-generated />

#nullable enable

using Foundation;

namespace TestNamespace;

public partial class NSArchiveReplaceEventArgs
{
	public global::Foundation.NSObject OldObject { get; set; }

	public global::Foundation.NSObject NewObject { get; set; }

	public NSArchiveReplaceEventArgs (global::Foundation.NSObject oldObject, global::Foundation.NSObject newObject)
	{
		this.OldObject = oldObject;
		this.NewObject = newObject;
	}
}
