// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

using System.Linq;

using Mono.Cecil;
using Mono.Linker;
using Registrar;
using Xamarin.Bundler;

#nullable enable

namespace Xamarin.Linker.Steps {

	// This class marks APIs referenced by the native code generated by the static registrar.
	public class MarkForStaticRegistrarStep : AssemblyModifierStep {
		protected override string Name { get => "Mark For Static Registrar"; }

		protected override int ErrorCode { get => 2460; }

		protected override bool IsActiveFor (AssemblyDefinition assembly)
		{
			if (Configuration.Application.Optimizations.OptimizeBlockLiteralSetupBlock != true)
				return false;

			if (Configuration.Application.Registrar != RegistrarMode.Static)
				return false;

			return Annotations.GetAction (assembly) == AssemblyAction.Link;
		}

		protected override void TryProcess ()
		{
			DerivedLinkContext.DidRunMarkForStaticRegistrarStep = true;
			base.TryProcess ();
		}

		protected override bool ProcessType (TypeDefinition type)
		{
			return base.ProcessMethods (type);
		}

		protected override bool ProcessMethod (MethodDefinition method)
		{
			return ProcessDelegateProxyAttribute (method);
		}

		// Mark the Invoke method in the type pointed to by the DelegateProxy attribute,
		// because it may only be referenced from native code when using the static registrar.
		bool ProcessDelegateProxyAttribute (MethodDefinition method)
		{
			if (!StaticRegistrar.IsDelegate (method.ReturnType.Resolve ()))
				return false;

			var getDelegateProxyType = DerivedLinkContext.StaticRegistrar.GetDelegateProxyType (method);
			if (getDelegateProxyType is null)
				return false;

			var invokeMethod = getDelegateProxyType.Methods.SingleOrDefault (m => m.Name == "Invoke");
			if (invokeMethod is null)
				return false;

			return abr.AddDynamicDependencyAttribute (method, invokeMethod);
		}
	}
}
