# Xamarin
# Build samples

trigger:
  - sample-tester

jobs:
- job: macOS
  displayName: xamarin macios
  timeoutInMinutes: 360

  pool:
    vmImage: 'macOS-10.13'

  steps:
  - bash: |
      set -x
      set -e
      uname -a
      ls -la /Library/Frameworks/Xamarin.iOS.framework/Versions || true
      ls -la /Library/Frameworks/Xamarin.Mac.framework/Versions || true
      mono --version || true
      env | sort
    displayName: System Info

  - task: xamops.azdevex.provisionator-task.provisionator@1
    displayName: Provision dependencies
    inputs:
      provisioning_script: $(System.DefaultWorkingDirectory)/devops/build-samples.csx

  - bash: |
      set -x
      set -e
      make -C tests test-system.config
      make -C tests/sampletester TESTS_USE_SYSTEM=1
    displayName: Run tests

  - task: PublishTestResults@2
    displayName: Publish test results
    condition: 'always()'
    testResultsFormat: NUnit
    testResultsFiles: '**/TestResult*.xml'
    testRunTitle: Sample tests (build)
    publishRunAttachments: true
