# Xamarin
# Build samples

trigger:
  - sample-tester

jobs:
- job: macOS
  displayName: Build samples
  timeoutInMinutes: 360
  strategy:
    matrix:
      Debug|iPhone:
        TEST_PLATFORM_FILTER_EXPRESSION: '^iPhone$'
        TEST_CONFIG_FILTER_EXPRESSION: '^.*Debug.*$'
      Debug|iPhoneSimulator:
        TEST_PLATFORM_FILTER_EXPRESSION: '^iPhoneSimulator$'
        TEST_CONFIG_FILTER_EXPRESSION: '^.*Debug.*$'
      Release|iPhone:
        TEST_PLATFORM_FILTER_EXPRESSION: '^iPhone$'
        TEST_CONFIG_FILTER_EXPRESSION: '^.*Release.*$'
      Release|iPhoneSimulator:
        TEST_PLATFORM_FILTER_EXPRESSION: '^iPhoneSimulator$'
        TEST_CONFIG_FILTER_EXPRESSION: '^.*Release.*$'
      Debug|Mac:
        TEST_PLATFORM_FILTER_EXPRESSION: '^$'
        TEST_CONFIG_FILTER_EXPRESSION: '^.*Debug.*$'
      Release|Mac:
        TEST_PLATFORM_FILTER_EXPRESSION: '^$'
        TEST_CONFIG_FILTER_EXPRESSION: '^.*Release.*$'

  pool:
    vmImage: 'macOS-10.13'

  steps:
  - bash: |
      set -x
      set -e
      uname -a
      ls -la /Library/Frameworks/Xamarin.iOS.framework/Versions || true
      ls -la /Library/Frameworks/Xamarin.Mac.framework/Versions || true
      ls -lad /Applications/Xcode*
      xcode-select -p
      mono --version || true
      env | sort
    displayName: System Info

  # FIXME: this should figure out the exact Xcode version from on PROVISION_FROM_COMMIT.
  - bash: sudo xcode-select -s /Applications/Xcode_10.1.app
    displayName: Select Xcode 10.1

  - task: xamops.azdevex.provisionator-task.provisionator@1
    displayName: Provision dependencies
    inputs:
      provisioning_script: $(System.DefaultWorkingDirectory)/devops/build-samples.csx

  - bash: |
      set -x
      set -e
      make -C tests test-system.config
      make -C tests/sampletester TESTS_USE_SYSTEM=1
    displayName: Run tests

  - task: PublishTestResults@2
    displayName: Publish test results
    condition: always()
    inputs:
      testResultsFormat: NUnit
      testResultsFiles: '**/TestResult*.xml'
      testRunTitle: Sample tests (build)
      publishRunAttachments: true
      mergeTestResults: true
