//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sharpie.Bind {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sharpie.Bind.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The error message for code {0} could not be found. Please report this missing message on GitHub at https://github.com/dotnet/macios/issues/new.
        /// </summary>
        public static string ErrorMessageNotFound {
            get {
                return ResourceManager.GetString("ErrorMessageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred: {0}. Please fill a bug report at https://github.com/dotnet/macios/issues..
        /// </summary>
        public static string SHARPIE0000 {
            get {
                return ResourceManager.GetString("SHARPIE0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported construct: {0}. Generated bindings may be incomplete. Please file an issue at https://github.com/dotnet/macios/issues..
        /// </summary>
        public static string SHARPIE0001 {
            get {
                return ResourceManager.GetString("SHARPIE0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output directory must be specified..
        /// </summary>
        public static string SHARPIE0002 {
            get {
                return ResourceManager.GetString("SHARPIE0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse translation unit (error: {0})..
        /// </summary>
        public static string SHARPIE0003 {
            get {
                return ResourceManager.GetString("SHARPIE0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create translation unit for unknown reasons. Please file an issue at https://github.com/dotnet/macios/issues..
        /// </summary>
        public static string SHARPIE0004 {
            get {
                return ResourceManager.GetString("SHARPIE0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation failed with error: {0}.
        /// </summary>
        public static string SHARPIE0005 {
            get {
                return ResourceManager.GetString("SHARPIE0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to compute platform assembly location for the platform {0}: {1}.
        /// </summary>
        public static string SHARPIE0006 {
            get {
                return ResourceManager.GetString("SHARPIE0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computed platform assembly path does not exist for the platform {0}: {1}.
        /// </summary>
        public static string SHARPIE0007 {
            get {
                return ResourceManager.GetString("SHARPIE0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to compute the toolchain path for the platform &apos;{0}&apos;: {1}.
        /// </summary>
        public static string SHARPIE0008 {
            get {
                return ResourceManager.GetString("SHARPIE0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to the SDK path (&apos;xcrun --show-sdk-path&apos; failed): {0}.
        /// </summary>
        public static string SHARPIE0009 {
            get {
                return ResourceManager.GetString("SHARPIE0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to clang&apos;s resource directory is required..
        /// </summary>
        public static string SHARPIE0010 {
            get {
                return ResourceManager.GetString("SHARPIE0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified clang resource directory does not exist: {0}.
        /// </summary>
        public static string SHARPIE0011 {
            get {
                return ResourceManager.GetString("SHARPIE0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the clang resource directory, because it doesn&apos;t look like we&apos;re executing from inside a NuGet..
        /// </summary>
        public static string SHARPIE0012 {
            get {
                return ResourceManager.GetString("SHARPIE0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the clang resource directory, because the directory {0} doesn&apos;t exist..
        /// </summary>
        public static string SHARPIE0013 {
            get {
                return ResourceManager.GetString("SHARPIE0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The framework &apos;{0}&apos; was specified in the excluded frameworks list but was not found in the SDK..
        /// </summary>
        public static string SHARPIE0014 {
            get {
                return ResourceManager.GetString("SHARPIE0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown argument: {0}.
        /// </summary>
        public static string SHARPIE0015 {
            get {
                return ResourceManager.GetString("SHARPIE0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot specify both a source framework and a source file..
        /// </summary>
        public static string SHARPIE0016 {
            get {
                return ResourceManager.GetString("SHARPIE0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The framework &apos;{0}&apos; doesn&apos;t exist..
        /// </summary>
        public static string SHARPIE0017 {
            get {
                return ResourceManager.GetString("SHARPIE0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The framework &apos;{0}&apos; does not have an umbrella header or module map..
        /// </summary>
        public static string SHARPIE0018 {
            get {
                return ResourceManager.GetString("SHARPIE0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal error: {0}. Please file an issue at https://github.com/dotnet/macios/issues..
        /// </summary>
        public static string SHARPIE0099 {
            get {
                return ResourceManager.GetString("SHARPIE0099", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A warning occurred during compilation: {0}.
        /// </summary>
        public static string SHARPIE1000 {
            get {
                return ResourceManager.GetString("SHARPIE1000", resourceCulture);
            }
        }
    }
}
