
#if PREFIX == 1
	#define theUltimateAnswer object_theUltimateAnswer
	#define useZLib           object_useZLib
	#define ObjCRegistrarTest object_ObjCRegistrarTest
	#define ObjCBlockTester   object_ObjCBlockTester
	#define FreedNotifier     object_FreedNotifier
	#define EvilDeallocator   object_EvilDeallocator
	#define MainThreadDeallocator object_MainThreadDeallocator
	#define FakeType2         object_FakeType2
	#define UltimateMachine   object_UltimateMachine
	#define FrameworkTest     object_FrameworkTest
	#define RefOutParameters  object_RefOutParameters
	#define TypeProvidingProtocolConstructors objecct_TypeProvidingProtocolConstructors
	#define Sc                object_Sc
	#define Scc               object_Scc
	#define Sccc              object_Sccc
	#define Sd                object_Sd
	#define Sdd               object_Sdd
	#define Sddd              object_Sddd
	#define Sdddd             object_Sdddd
	#define Sddddd            object_Sddddd
	#define Si                object_Si
	#define Sii               object_Sii
	#define Siii              object_Siii
	#define Siiii             object_Siiii
	#define Siiiii            object_Siiiii
	#define Sid               object_Sid
	#define Sdi               object_Sdi
	#define Sidi              object_Sidi
	#define Sidid             object_Sidid
	#define Siid              object_Siid
	#define Sddi              object_Sddi
	#define Sdidi             object_Sdidi
	#define Sl                object_Sl
	#define Sll               object_Sll
	#define Slll              object_Slll
	#define Sllll             object_Sllll
	#define Slllll            object_Slllll
	#define Sldld             object_Sldld
	#define Sdldl             object_Sdldl
	#define Scccc             object_Scccc
	#define Sffff             object_Sffff
	#define Sif               object_Sif
	#define Sifif             object_Sifif
	#define Sf                object_Sf
	#define Sff               object_Sff
	#define Sfff              object_Sfff
	#define Sffff             object_Sffff
	#define Sfffff            object_Sfffff
	#define Siff              object_Siff
	#define Siiff             object_Siiff
	#define Sfi               object_Sfi
	#define Sfifi             object_Sfifi
	#define Ss                object_Ss
	#define Sss               object_Sss
	#define Ssss              object_Ssss
	#define Sssss             object_Sssss
	#define CtorChaining1     object_CtorChaining1
	#define ObjCExceptionTest object_ObjCExceptionTest
	#define ObjCProtocolClassTest object_ObjCProtocolClassTest
	#define ProtocolAssigner      object_ProtocolAssigner
	#define ObjCProtocolTestImpl  object_ObjCProtocolTestImpl
	#define x_mdltransform_get_rotation_matrix object_x_mdltransform_get_rotation_matrix
	#define x_mdltransformcomponent_get_local_transform object_x_mdltransformcomponent_get_local_transform
	#define x_mdltransform_create_global_transform object_x_mdltransform_create_global_transform
	#define x_get_matrix_float4x4 object_x_get_matrix_float4x4
	#define x_get_matrix_float4x3 object_x_get_matrix_float4x3
	#define x_get_matrix_float3x3 object_x_get_matrix_float3x3
	#define x_get_matrix_float2x2 object_x_get_matrix_float2x2
	#define x_call_block          object_x_call_block
	#define x_call_func_3         object_x_call_func_3
	#define x_SCNMatrix4MakeTranslation object_x_SCNMatrix4MakeTranslation
	#define x_SCNMatrix4MakeScale       object_x_SCNMatrix4MakeScale
	#define x_SCNMatrix4Translate       object_x_SCNMatrix4Translate
	#define x_GlobalString				object_x_GlobalString
	#define x_native_field				object_x_native_field
	#define StrongDictionarySByteField                   object_StrongDictionarySByteField
	#define StrongDictionaryInt16Field                   object_StrongDictionaryInt16Field
	#define StrongDictionaryInt32Field                   object_StrongDictionaryInt32Field
	#define StrongDictionaryInt64Field                   object_StrongDictionaryInt64Field
	#define StrongDictionaryByteField                    object_StrongDictionaryByteField
	#define StrongDictionaryUInt16Field                  object_StrongDictionaryUInt16Field
	#define StrongDictionaryUInt32Field                  object_StrongDictionaryUInt32Field
	#define StrongDictionaryUInt64Field                  object_StrongDictionaryUInt64Field
	#define StrongDictionaryNIntField                    object_StrongDictionaryNIntField
	#define StrongDictionaryNUIntField                   object_StrongDictionaryNUIntField
	#define StrongDictionarySingleField                  object_StrongDictionarySingleField
	#define StrongDictionaryDoubleField                  object_StrongDictionaryDoubleField
	#define StrongDictionaryNFloatField                  object_StrongDictionaryNFloatField
	#define StrongDictionaryNSObjectField                object_StrongDictionaryNSObjectField
	#define StrongDictionaryBooleanField                 object_StrongDictionaryBooleanField
	#define StrongDictionaryNSStringField                object_StrongDictionaryNSStringField
	#define StrongDictionaryNSDateField                  object_StrongDictionaryNSDateField
	#define StrongDictionaryNSDictionaryField            object_StrongDictionaryNSDictionaryField
	#define StrongDictionaryStrongDictionaryField        object_StrongDictionaryStrongDictionaryField
	#define StrongDictionaryArrayOfSByteField            object_StrongDictionaryArrayOfSByteField
	#define StrongDictionaryArrayOfInt16Field            object_StrongDictionaryArrayOfInt16Field
	#define StrongDictionaryArrayOfInt32Field            object_StrongDictionaryArrayOfInt32Field
	#define StrongDictionaryArrayOfInt64Field            object_StrongDictionaryArrayOfInt64Field
	#define StrongDictionaryArrayOfByteField             object_StrongDictionaryArrayOfByteField
	#define StrongDictionaryArrayOfUInt16Field           object_StrongDictionaryArrayOfUInt16Field
	#define StrongDictionaryArrayOfUInt32Field           object_StrongDictionaryArrayOfUInt32Field
	#define StrongDictionaryArrayOfUInt64Field           object_StrongDictionaryArrayOfUInt64Field
	#define StrongDictionaryArrayOfNIntField             object_StrongDictionaryArrayOfNIntField
	#define StrongDictionaryArrayOfNUIntField            object_StrongDictionaryArrayOfNUIntField
	#define StrongDictionaryArrayOfSingleField           object_StrongDictionaryArrayOfSingleField
	#define StrongDictionaryArrayOfDoubleField           object_StrongDictionaryArrayOfDoubleField
	#define StrongDictionaryArrayOfNFloatField           object_StrongDictionaryArrayOfNFloatField
	#define StrongDictionaryArrayOfNSObjectField         object_StrongDictionaryArrayOfNSObjectField
	#define StrongDictionaryArrayOfBooleanField          object_StrongDictionaryArrayOfBooleanField
	#define StrongDictionaryArrayOfNSStringField         object_StrongDictionaryArrayOfNSStringField
	#define StrongDictionaryArrayOfNSDateField           object_StrongDictionaryArrayOfNSDateField
	#define StrongDictionaryArrayOfNSDictionaryField     object_StrongDictionaryArrayOfNSDictionaryField
	#define StrongDictionaryArrayOfStrongDictionaryField object_StrongDictionaryArrayOfStrongDictionaryField
	#define StrongDictionaryStringField                  object_StrongDictionaryStringField
	#define StrongDictionaryDateField                    object_StrongDictionaryDateField
	#define StrongDictionaryGenericNSDictionaryField     object_StrongDictionaryGenericNSDictionaryField
	#define StrongDictionaryArrayOfStringField           object_StrongDictionaryArrayOfStringField
	#define StrongDictionaryNSDataField                  object_StrongDictionaryNSDataField
	#define StrongDictionaryNSDataAsMatrix3Field         object_StrongDictionaryNSDataAsMatrix3Field
	#define StrongDictionaryCGRectField                  object_StrongDictionaryCGRectField
	#define StrongDictionaryCGSizeField                  object_StrongDictionaryCGSizeField
	#define StrongDictionaryCGPointField                 object_StrongDictionaryCGPointField
	#define StrongDictionaryCMTimeField                  object_StrongDictionaryCMTimeField
	#define StrongDictionaryUIEdgeInsetsField            object_StrongDictionaryUIEdgeInsetsField
#elif PREFIX == 2
	#define theUltimateAnswer ar_theUltimateAnswer
	#define useZLib           ar_useZLib
	#define ObjCRegistrarTest ar_ObjCRegistrarTest
	#define ObjCBlockTester   ar_ObjCBlockTester
	#define FreedNotifier     ar_FreedNotifier
	#define EvilDeallocator   ar_EvilDeallocator
	#define MainThreadDeallocator ar_MainThreadDeallocator
	#define FakeType2         ar_FakeType2
	#define UltimateMachine   ar_UltimateMachine
	#define FrameworkTest     ar_FrameworkTest
	#define RefOutParameters  ar_RefOutParameters
	#define TypeProvidingProtocolConstructors ar_TypeProvidingProtocolConstructors
	#define Sc                ar_Sc
	#define Scc               ar_Scc
	#define Sccc              ar_Sccc
	#define Sd                ar_Sd
	#define Sdd               ar_Sdd
	#define Sddd              ar_Sddd
	#define Sdddd             ar_Sdddd
	#define Sddddd            ar_Sddddd
	#define Si                ar_Si
	#define Sii               ar_Sii
	#define Siii              ar_Siii
	#define Siiii             ar_Siiii
	#define Siiiii            ar_Siiiii
	#define Sid               ar_Sid
	#define Sdi               ar_Sdi
	#define Sidi              ar_Sidi
	#define Sidid             ar_Sidid
	#define Siid              ar_Siid
	#define Sddi              ar_Sddi
	#define Sdidi             ar_Sdidi
	#define Sl                ar_Sl
	#define Sll               ar_Sll
	#define Slll              ar_Slll
	#define Sllll             ar_Sllll
	#define Slllll            ar_Slllll
	#define Sldld             ar_Sldld
	#define Sdldl             ar_Sdldl
	#define Scccc             ar_Scccc
	#define Sffff             ar_Sffff
	#define Sif               ar_Sif
	#define Sifif             ar_Sifif
	#define Sf                ar_Sf
	#define Sff               ar_Sff
	#define Sfff              ar_Sfff
	#define Sffff             ar_Sffff
	#define Sfffff            ar_Sfffff
	#define Siff              ar_Siff
	#define Siiff             ar_Siiff
	#define Sfi               ar_Sfi
	#define Sfifi             ar_Sfifi
	#define Ss                ar_Ss
	#define Sss               ar_Sss
	#define Ssss              ar_Ssss
	#define Sssss             ar_Sssss
	#define CtorChaining1     ar_CtorChaining1
	#define ObjCExceptionTest ar_ObjCExceptionTest
	#define ObjCProtocolClassTest ar_ObjCProtocolClassTest
	#define ProtocolAssigner      ar_ProtocolAssigner
	#define ObjCProtocolTestImpl  ar_ObjCProtocolTestImpl
	#define x_mdltransform_get_rotation_matrix ar_x_mdltransform_get_rotation_matrix
	#define x_mdltransformcomponent_get_local_transform ar_x_mdltransformcomponent_get_local_transform
	#define x_mdltransform_create_global_transform ar_x_mdltransform_create_global_transform
	#define x_get_matrix_float4x4 ar_x_get_matrix_float4x4
	#define x_get_matrix_float4x3 ar_x_get_matrix_float4x3
	#define x_get_matrix_float3x3 ar_x_get_matrix_float3x3
	#define x_get_matrix_float2x2 ar_x_get_matrix_float2x2
	#define x_call_block          ar_x_call_block
	#define x_call_func_3         ar_x_call_func_3
	#define x_SCNMatrix4MakeTranslation ar_x_SCNMatrix4MakeTranslation
	#define x_SCNMatrix4MakeScale       ar_x_SCNMatrix4MakeScale
	#define x_SCNMatrix4Translate       ar_x_SCNMatrix4Translate
	#define x_GlobalString					ar_x_GlobalString
	#define x_native_field				ar_x_native_field
	#define StrongDictionarySByteField                   ar_StrongDictionarySByteField
	#define StrongDictionaryInt16Field                   ar_StrongDictionaryInt16Field
	#define StrongDictionaryInt32Field                   ar_StrongDictionaryInt32Field
	#define StrongDictionaryInt64Field                   ar_StrongDictionaryInt64Field
	#define StrongDictionaryByteField                    ar_StrongDictionaryByteField
	#define StrongDictionaryUInt16Field                  ar_StrongDictionaryUInt16Field
	#define StrongDictionaryUInt32Field                  ar_StrongDictionaryUInt32Field
	#define StrongDictionaryUInt64Field                  ar_StrongDictionaryUInt64Field
	#define StrongDictionaryNIntField                    ar_StrongDictionaryNIntField
	#define StrongDictionaryNUIntField                   ar_StrongDictionaryNUIntField
	#define StrongDictionarySingleField                  ar_StrongDictionarySingleField
	#define StrongDictionaryDoubleField                  ar_StrongDictionaryDoubleField
	#define StrongDictionaryNFloatField                  ar_StrongDictionaryNFloatField
	#define StrongDictionaryNSObjectField                ar_StrongDictionaryNSObjectField
	#define StrongDictionaryBooleanField                 ar_StrongDictionaryBooleanField
	#define StrongDictionaryNSStringField                ar_StrongDictionaryNSStringField
	#define StrongDictionaryNSDateField                  ar_StrongDictionaryNSDateField
	#define StrongDictionaryNSDictionaryField            ar_StrongDictionaryNSDictionaryField
	#define StrongDictionaryStrongDictionaryField        ar_StrongDictionaryStrongDictionaryField
	#define StrongDictionaryArrayOfSByteField            ar_StrongDictionaryArrayOfSByteField
	#define StrongDictionaryArrayOfInt16Field            ar_StrongDictionaryArrayOfInt16Field
	#define StrongDictionaryArrayOfInt32Field            ar_StrongDictionaryArrayOfInt32Field
	#define StrongDictionaryArrayOfInt64Field            ar_StrongDictionaryArrayOfInt64Field
	#define StrongDictionaryArrayOfByteField             ar_StrongDictionaryArrayOfByteField
	#define StrongDictionaryArrayOfUInt16Field           ar_StrongDictionaryArrayOfUInt16Field
	#define StrongDictionaryArrayOfUInt32Field           ar_StrongDictionaryArrayOfUInt32Field
	#define StrongDictionaryArrayOfUInt64Field           ar_StrongDictionaryArrayOfUInt64Field
	#define StrongDictionaryArrayOfNIntField             ar_StrongDictionaryArrayOfNIntField
	#define StrongDictionaryArrayOfNUIntField            ar_StrongDictionaryArrayOfNUIntField
	#define StrongDictionaryArrayOfSingleField           ar_StrongDictionaryArrayOfSingleField
	#define StrongDictionaryArrayOfDoubleField           ar_StrongDictionaryArrayOfDoubleField
	#define StrongDictionaryArrayOfNFloatField           ar_StrongDictionaryArrayOfNFloatField
	#define StrongDictionaryArrayOfNSObjectField         ar_StrongDictionaryArrayOfNSObjectField
	#define StrongDictionaryArrayOfBooleanField          ar_StrongDictionaryArrayOfBooleanField
	#define StrongDictionaryArrayOfNSStringField         ar_StrongDictionaryArrayOfNSStringField
	#define StrongDictionaryArrayOfNSDateField           ar_StrongDictionaryArrayOfNSDateField
	#define StrongDictionaryArrayOfNSDictionaryField     ar_StrongDictionaryArrayOfNSDictionaryField
	#define StrongDictionaryArrayOfStrongDictionaryField ar_StrongDictionaryArrayOfStrongDictionaryField
	#define StrongDictionaryStringField                  ar_StrongDictionaryStringField
	#define StrongDictionaryDateField                    ar_StrongDictionaryDateField
	#define StrongDictionaryGenericNSDictionaryField     ar_StrongDictionaryGenericNSDictionaryField
	#define StrongDictionaryArrayOfStringField           ar_StrongDictionaryArrayOfStringField
	#define StrongDictionaryNSDataField                  ar_StrongDictionaryNSDataField
	#define StrongDictionaryNSDataAsMatrix3Field         ar_StrongDictionaryNSDataAsMatrix3Field
	#define StrongDictionaryCGRectField                  ar_StrongDictionaryCGRectField
	#define StrongDictionaryCGSizeField                  ar_StrongDictionaryCGSizeField
	#define StrongDictionaryCGPointField                 ar_StrongDictionaryCGPointField
	#define StrongDictionaryCMTimeField                  ar_StrongDictionaryCMTimeField
	#define StrongDictionaryUIEdgeInsetsField            ar_StrongDictionaryUIEdgeInsetsField
#else
// keep original names
#endif
