// <auto-generated />

#nullable enable

using AVFoundation;
using CoreGraphics;
using Foundation;
using ObjCBindings;
using ObjCRuntime;
using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Drawing;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;
using System.Threading.Tasks;

namespace TestNamespace;

public partial class OuterClass
{
	public partial class InnerClass
	{
		[SupportedOSPlatform ("macos")]
		[SupportedOSPlatform ("ios")]
		[SupportedOSPlatform ("tvos")]
		[SupportedOSPlatform ("maccatalyst13.1")]
		public static partial class NestedCategory
		{
			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			const string selValueForKey_X = "valueForKey:";
			static readonly global::ObjCRuntime.NativeHandle selValueForKey_XHandle = global::ObjCRuntime.Selector.GetHandle ("valueForKey:");

			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			const string selSetValue_ForKey_X = "setValue:forKey:";
			static readonly global::ObjCRuntime.NativeHandle selSetValue_ForKey_XHandle = global::ObjCRuntime.Selector.GetHandle ("setValue:forKey:");

			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			const string selWriteToFile_Atomically_X = "writeToFile:atomically:";
			static readonly global::ObjCRuntime.NativeHandle selWriteToFile_Atomically_XHandle = global::ObjCRuntime.Selector.GetHandle ("writeToFile:atomically:");

			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			const string selArrayWithContentsOfFile_X = "arrayWithContentsOfFile:";
			static readonly global::ObjCRuntime.NativeHandle selArrayWithContentsOfFile_XHandle = global::ObjCRuntime.Selector.GetHandle ("arrayWithContentsOfFile:");

			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			const string selSortedArrayUsingComparator_X = "sortedArrayUsingComparator:";
			static readonly global::ObjCRuntime.NativeHandle selSortedArrayUsingComparator_XHandle = global::ObjCRuntime.Selector.GetHandle ("sortedArrayUsingComparator:");

			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			const string selFilteredArrayUsingPredicate_X = "filteredArrayUsingPredicate:";
			static readonly global::ObjCRuntime.NativeHandle selFilteredArrayUsingPredicate_XHandle = global::ObjCRuntime.Selector.GetHandle ("filteredArrayUsingPredicate:");

			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			const string selFilteredArrayUsingStrings_X = "filteredArrayUsingStrings:";
			static readonly global::ObjCRuntime.NativeHandle selFilteredArrayUsingStrings_XHandle = global::ObjCRuntime.Selector.GetHandle ("filteredArrayUsingStrings:");

			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			const string selCompleteRequestReturningItems_CompletionHandler_X = "completeRequestReturningItems:completionHandler:";
			static readonly global::ObjCRuntime.NativeHandle selCompleteRequestReturningItems_CompletionHandler_XHandle = global::ObjCRuntime.Selector.GetHandle ("completeRequestReturningItems:completionHandler:");

			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			const string selBookmarkDataWithContentsOfURL_Error_X = "bookmarkDataWithContentsOfURL:error:";
			static readonly global::ObjCRuntime.NativeHandle selBookmarkDataWithContentsOfURL_Error_XHandle = global::ObjCRuntime.Selector.GetHandle ("bookmarkDataWithContentsOfURL:error:");

			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			const string selBookmarkDataWithContentsOfURL_Subdomain_Error_X = "bookmarkDataWithContentsOfURL:subdomain:error:";
			static readonly global::ObjCRuntime.NativeHandle selBookmarkDataWithContentsOfURL_Subdomain_Error_XHandle = global::ObjCRuntime.Selector.GetHandle ("bookmarkDataWithContentsOfURL:subdomain:error:");

			static readonly global::ObjCRuntime.NativeHandle class_ptr = global::ObjCRuntime.Class.GetHandle ("NSObject");

			[SupportedOSPlatform ("macos")]
			[SupportedOSPlatform ("ios")]
			[SupportedOSPlatform ("tvos")]
			[SupportedOSPlatform ("maccatalyst13.1")]
			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			public static unsafe partial void CompleteRequest (this global::Foundation.NSObject self, global::Foundation.NSExtensionItem[] returningItems, global::System.Action<bool>? completionHandler)
			{
				if (returningItems is null)
					global::ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (returningItems));
				using var nsa_returningItems = global::Foundation.NSArray.FromNSObjects (returningItems);
				using var block_completionHandler = global::ObjCRuntime.Trampolines.SDActionArity1bool.CreateNullableBlock (completionHandler);
				global::ObjCRuntime.BlockLiteral* block_ptr_completionHandler = completionHandler is not null ? &block_completionHandler : null;
				global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle_NativeHandle (self.Handle, global::ObjCRuntime.Selector.GetHandle ("completeRequestReturningItems:completionHandler:"), nsa_returningItems.Handle, (global::ObjCRuntime.NativeHandle) block_ptr_completionHandler);
				global::System.GC.KeepAlive (self);
				global::System.GC.KeepAlive (nsa_returningItems);
			}

			[SupportedOSPlatform ("macos")]
			[SupportedOSPlatform ("ios")]
			[SupportedOSPlatform ("tvos")]
			[SupportedOSPlatform ("maccatalyst13.1")]
			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			public static global::System.Threading.Tasks.Task<bool> CompleteRequestAsync (this global::Foundation.NSObject self, global::Foundation.NSExtensionItem[] returningItems)
			{
				global::System.Threading.Tasks.TaskCompletionSource<bool> _tcs = new ();
				CompleteRequest (self, returningItems, (_cbobj) => {
					_tcs.SetResult (_cbobj);
				});
				return _tcs.Task;
			}

			[SupportedOSPlatform ("macos")]
			[SupportedOSPlatform ("ios")]
			[SupportedOSPlatform ("tvos")]
			[SupportedOSPlatform ("maccatalyst13.1")]
			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			public static unsafe partial void CompleteRequest (this global::Foundation.NSObject self, global::Foundation.NSExtensionItem[] returningItems, global::System.Action<bool, string?>? completionHandler)
			{
				if (returningItems is null)
					global::ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (returningItems));
				using var nsa_returningItems = global::Foundation.NSArray.FromNSObjects (returningItems);
				using var block_completionHandler = global::ObjCRuntime.Trampolines.SDActionArity2boolstring?.CreateNullableBlock (completionHandler);
				global::ObjCRuntime.BlockLiteral* block_ptr_completionHandler = completionHandler is not null ? &block_completionHandler : null;
				global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle_NativeHandle (self.Handle, global::ObjCRuntime.Selector.GetHandle ("completeRequestReturningItems:completionHandler:"), nsa_returningItems.Handle, (global::ObjCRuntime.NativeHandle) block_ptr_completionHandler);
				global::System.GC.KeepAlive (self);
				global::System.GC.KeepAlive (nsa_returningItems);
			}

			[SupportedOSPlatform ("macos")]
			[SupportedOSPlatform ("ios")]
			[SupportedOSPlatform ("tvos")]
			[SupportedOSPlatform ("maccatalyst13.1")]
			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			public static global::System.Threading.Tasks.Task<(bool, string?)> CompleteRequestAsync (this global::Foundation.NSObject self, global::Foundation.NSExtensionItem[] returningItems)
			{
				global::System.Threading.Tasks.TaskCompletionSource<(bool, string?)> _tcs = new ();
				CompleteRequest (self, returningItems, (_cbarg1, _cbarg2) => {
					_tcs.SetResult (new (_cbarg1, _cbarg2));
				});
				return _tcs.Task;
			}

			[SupportedOSPlatform ("macos")]
			[SupportedOSPlatform ("ios")]
			[SupportedOSPlatform ("tvos")]
			[SupportedOSPlatform ("maccatalyst13.1")]
			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			public static unsafe partial void CompleteRequest (this global::Foundation.NSObject self, global::Foundation.NSExtensionItem[] returningItems, global::System.Action<bool, string, string?>? completionHandler)
			{
				if (returningItems is null)
					global::ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (returningItems));
				using var nsa_returningItems = global::Foundation.NSArray.FromNSObjects (returningItems);
				using var block_completionHandler = global::ObjCRuntime.Trampolines.SDActionArity3boolstringstring?.CreateNullableBlock (completionHandler);
				global::ObjCRuntime.BlockLiteral* block_ptr_completionHandler = completionHandler is not null ? &block_completionHandler : null;
				global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle_NativeHandle (self.Handle, global::ObjCRuntime.Selector.GetHandle ("completeRequestReturningItems:completionHandler:"), nsa_returningItems.Handle, (global::ObjCRuntime.NativeHandle) block_ptr_completionHandler);
				global::System.GC.KeepAlive (self);
				global::System.GC.KeepAlive (nsa_returningItems);
			}

			[SupportedOSPlatform ("macos")]
			[SupportedOSPlatform ("ios")]
			[SupportedOSPlatform ("tvos")]
			[SupportedOSPlatform ("maccatalyst13.1")]
			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			public static global::System.Threading.Tasks.Task<(bool Success, string Name, string? Surname)> CompleteRequestAsync (this global::Foundation.NSObject self, global::Foundation.NSExtensionItem[] returningItems)
			{
				global::System.Threading.Tasks.TaskCompletionSource<(bool Success, string Name, string? Surname)> _tcs = new ();
				CompleteRequest (self, returningItems, (_cbarg1, _cbarg2, _cbarg3) => {
					_tcs.SetResult (new (_cbarg1, _cbarg2, _cbarg3));
				});
				return _tcs.Task;
			}

			[SupportedOSPlatform ("macos")]
			[SupportedOSPlatform ("ios")]
			[SupportedOSPlatform ("tvos")]
			[SupportedOSPlatform ("maccatalyst13.1")]
			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			public static unsafe partial global::Foundation.NSArray Filter (this global::Foundation.NSObject self, global::Foundation.NSPredicate predicate)
			{
				var predicate__handle__ = predicate!.GetNonNullHandle (nameof (predicate));
				global::Foundation.NSArray ret;
				ret = global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSArray> (global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend_NativeHandle (self.Handle, global::ObjCRuntime.Selector.GetHandle ("filteredArrayUsingPredicate:"), predicate__handle__))!;
				global::System.GC.KeepAlive (self);
				global::System.GC.KeepAlive (predicate);
				return ret;
			}

			[SupportedOSPlatform ("macos")]
			[SupportedOSPlatform ("ios")]
			[SupportedOSPlatform ("tvos")]
			[SupportedOSPlatform ("maccatalyst13.1")]
			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			public static unsafe partial global::Foundation.NSArray FilterStrings (this global::Foundation.NSObject self, string[] predicate)
			{
				if (predicate is null)
					global::ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (predicate));
				using var nsa_predicate = global::Foundation.NSArray.FromStrings (predicate);
				global::Foundation.NSArray ret;
				ret = global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSArray> (global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend_NativeHandle (self.Handle, global::ObjCRuntime.Selector.GetHandle ("filteredArrayUsingStrings:"), nsa_predicate.Handle))!;
				global::System.GC.KeepAlive (self);
				global::System.GC.KeepAlive (nsa_predicate);
				return ret;
			}

			[SupportedOSPlatform ("macos")]
			[SupportedOSPlatform ("ios")]
			[SupportedOSPlatform ("tvos")]
			[SupportedOSPlatform ("maccatalyst13.1")]
			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			public static unsafe partial static global::Foundation.NSArray FromFile (this global::Foundation.NSObject self, string path)
			{
				if (path is null)
					global::ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (path));
				var nspath = global::CoreFoundation.CFString.CreateNative (path);
				global::Foundation.NSArray ret;
				ret = global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSArray> (global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend_NativeHandle (self.Handle, global::ObjCRuntime.Selector.GetHandle ("arrayWithContentsOfFile:"), nspath))!;
				global::System.GC.KeepAlive (self);
				global::CoreFoundation.CFString.ReleaseNative (nspath);
				return ret;
			}

			[SupportedOSPlatform ("macos")]
			[SupportedOSPlatform ("ios")]
			[SupportedOSPlatform ("tvos")]
			[SupportedOSPlatform ("maccatalyst13.1")]
			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			public static unsafe partial global::Foundation.NSData GetBookmarkData (this global::Foundation.NSObject self, global::Foundation.NSUrl bookmarkFileUrl, out global::Foundation.NSError? error)
			{
				var bookmarkFileUrl__handle__ = bookmarkFileUrl!.GetNonNullHandle (nameof (bookmarkFileUrl));
				global::ObjCRuntime.NativeHandle error__handle__;
				global::Foundation.NSData ret;
				ret = global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSData> (global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend_NativeHandle_NativeHandle (self.Handle, global::ObjCRuntime.Selector.GetHandle ("bookmarkDataWithContentsOfURL:error:"), bookmarkFileUrl__handle__, &error__handle__))!;
				global::System.GC.KeepAlive (self);
				global::System.GC.KeepAlive (bookmarkFileUrl);
				error = global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSError> (error__handle__);
				return ret;
			}

			[SupportedOSPlatform ("macos")]
			[SupportedOSPlatform ("ios")]
			[SupportedOSPlatform ("tvos")]
			[SupportedOSPlatform ("maccatalyst13.1")]
			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			public static unsafe partial global::Foundation.NSData GetBookmarkData (this global::Foundation.NSObject self, global::Foundation.NSUrl bookmarkFileUrl, string subdomain, out global::Foundation.NSError? error)
			{
				if (subdomain is null)
					global::ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (subdomain));
				var bookmarkFileUrl__handle__ = bookmarkFileUrl!.GetNonNullHandle (nameof (bookmarkFileUrl));
				var nssubdomain = global::CoreFoundation.CFString.CreateNative (subdomain);
				global::ObjCRuntime.NativeHandle error__handle__;
				global::Foundation.NSData ret;
				ret = global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSData> (global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend_NativeHandle_NativeHandle_NativeHandle (self.Handle, global::ObjCRuntime.Selector.GetHandle ("bookmarkDataWithContentsOfURL:subdomain:error:"), bookmarkFileUrl__handle__, nssubdomain, &error__handle__))!;
				global::System.GC.KeepAlive (self);
				global::System.GC.KeepAlive (bookmarkFileUrl);
				global::CoreFoundation.CFString.ReleaseNative (nssubdomain);
				error = global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSError> (error__handle__);
				return ret;
			}

			[SupportedOSPlatform ("macos")]
			[SupportedOSPlatform ("ios")]
			[SupportedOSPlatform ("tvos")]
			[SupportedOSPlatform ("maccatalyst13.1")]
			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			public static unsafe partial void SetValueForKey (this global::Foundation.NSObject self, global::Foundation.NSObject value, global::Foundation.NSString key)
			{
				var value__handle__ = value!.GetNonNullHandle (nameof (value));
				var key__handle__ = key!.GetNonNullHandle (nameof (key));
				global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle_NativeHandle (self.Handle, global::ObjCRuntime.Selector.GetHandle ("setValue:forKey:"), value__handle__, key__handle__);
				global::System.GC.KeepAlive (self);
				global::System.GC.KeepAlive (value);
				global::System.GC.KeepAlive (key);
			}

			[SupportedOSPlatform ("macos")]
			[SupportedOSPlatform ("ios")]
			[SupportedOSPlatform ("tvos")]
			[SupportedOSPlatform ("maccatalyst13.1")]
			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			public static unsafe partial global::Foundation.NSArray Sort (this global::Foundation.NSObject self, global::Foundation.NSComparator cmptr)
			{
				if (cmptr is null)
					global::ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (cmptr));
				using var block_cmptr = global::ObjCRuntime.Trampolines.SDNSComparator.CreateNullableBlock (cmptr);
				global::ObjCRuntime.BlockLiteral* block_ptr_cmptr = cmptr is not null ? &block_cmptr : null;
				global::Foundation.NSArray ret;
				ret = global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSArray> (global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend_NativeHandle (self.Handle, global::ObjCRuntime.Selector.GetHandle ("sortedArrayUsingComparator:"), (global::ObjCRuntime.NativeHandle) block_ptr_cmptr))!;
				global::System.GC.KeepAlive (self);
				return ret;
			}

			[SupportedOSPlatform ("macos")]
			[SupportedOSPlatform ("ios")]
			[SupportedOSPlatform ("tvos")]
			[SupportedOSPlatform ("maccatalyst13.1")]
			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			public static unsafe partial global::Foundation.NSObject ValueForKey (this global::Foundation.NSObject self, global::Foundation.NSString key)
			{
				var key__handle__ = key!.GetNonNullHandle (nameof (key));
				global::Foundation.NSObject ret;
				ret = global::ObjCRuntime.Runtime.GetNSObject<global::Foundation.NSObject> (global::ObjCRuntime.Messaging.xamarin_NativeHandle_objc_msgSend_NativeHandle_exception (self.Handle, global::ObjCRuntime.Selector.GetHandle ("valueForKey:"), key__handle__))!;
				global::System.GC.KeepAlive (self);
				global::System.GC.KeepAlive (key);
				return ret;
			}

			[SupportedOSPlatform ("macos")]
			[SupportedOSPlatform ("ios")]
			[SupportedOSPlatform ("tvos")]
			[SupportedOSPlatform ("maccatalyst13.1")]
			[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
			public static unsafe partial bool WriteToFile (this global::Foundation.NSObject self, string path, bool useAuxiliaryFile)
			{
				if (path is null)
					global::ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (path));
				var nspath = global::CoreFoundation.CFString.CreateNative (path);
				bool ret;
				ret = global::ObjCRuntime.Messaging.bool_objc_msgSend_NativeHandle_bool (self.Handle, global::ObjCRuntime.Selector.GetHandle ("writeToFile:atomically:"), nspath, useAuxiliaryFile ? (byte) 1 : (byte) 0) != 0;
				global::System.GC.KeepAlive (self);
				global::CoreFoundation.CFString.ReleaseNative (nspath);
				return ret;
			}
		}
	}
}
