// <auto-generated />

#nullable enable

#if !XAMCORE_5_0

namespace TestNamespace;

[Obsolete ("Use 'CARendererOptions.Keys' class instead.", false)]
[SupportedOSPlatform ("macos")]
[SupportedOSPlatform ("ios")]
[SupportedOSPlatform ("tvos")]
[SupportedOSPlatform ("maccatalyst13.1")]
public static partial class CARendererOptionKeys
{

	static global::Foundation.NSString? _ColorSpace;

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public static partial global::Foundation.NSString ColorSpace
	{
		[SupportedOSPlatform ("macos")]
		[SupportedOSPlatform ("ios")]
		[SupportedOSPlatform ("tvos")]
		[SupportedOSPlatform ("maccatalyst13.1")]
		get
		{
			if (_ColorSpace is null)
				_ColorSpace = global::ObjCRuntime.Dlfcn.GetStringConstant (global::ObjCRuntime.Libraries.TestNamespace.Handle, "AVCaptureDeviceTypeBuiltInTelephotoCamera")!;
			return _ColorSpace;
		}
	}

	static global::Foundation.NSString? _MetalCommandQueue;

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	public static partial global::Foundation.NSString MetalCommandQueue
	{
		[SupportedOSPlatform ("macos")]
		[SupportedOSPlatform ("ios")]
		[SupportedOSPlatform ("tvos")]
		[SupportedOSPlatform ("maccatalyst13.1")]
		get
		{
			if (_MetalCommandQueue is null)
				_MetalCommandQueue = global::ObjCRuntime.Dlfcn.GetStringConstant (global::ObjCRuntime.Libraries.TestNamespace.Handle, "kCARendererMetalCommandQueue")!;
			return _MetalCommandQueue;
		}
	}
}
#endif
