// <auto-generated />

#nullable enable

using CoreGraphics;
using Foundation;
using Metal;
using ObjCBindings;
using System;
using System.Runtime.Versioning;

namespace TestNamespace;

public partial class OuterClass
{
	public partial class InnerClass
	{
		[SupportedOSPlatform ("macos")]
		[SupportedOSPlatform ("ios")]
		[SupportedOSPlatform ("tvos")]
		[SupportedOSPlatform ("maccatalyst13.1")]
		public partial class NestedStrongDictionary : DictionaryContainer
		{

			/// <summary>Creates a new <see cref="NestedStrongDictionary" /> with default (empty) values.</summary>
			[Preserve (Conditional = true)]
			public NestedStrongDictionary () : base (new global::Foundation.NSMutableDictionary ()) {}

			/// <summary>Creates a new <see cref="NestedStrongDictionary" /> from the values that are specified in <paramref name="dictionary" />.</summary>
			/// <param name="dictionary">The dictionary to use to populate the properties of this type.</param>
			[Preserve (Conditional = true)]
			public NestedStrongDictionary (global::Foundation.NSDictionary? dictionary) : base (dictionary) {}

			[SupportedOSPlatform ("macos")]
			[SupportedOSPlatform ("ios")]
			[SupportedOSPlatform ("tvos")]
			[SupportedOSPlatform ("maccatalyst13.1")]
			public partial global::CoreGraphics.CGColorSpace? ColorSpace
			{
				[SupportedOSPlatform ("macos")]
				[SupportedOSPlatform ("ios")]
				[SupportedOSPlatform ("tvos")]
				[SupportedOSPlatform ("maccatalyst13.1")]
				get
				{
					return GetNativeValue<global::CoreGraphics.CGColorSpace> (TestNamespace.OuterClass.InnerClass.NestedStrongDictionary.Keys.ColorSpace);
				}

				[SupportedOSPlatform ("macos")]
				[SupportedOSPlatform ("ios")]
				[SupportedOSPlatform ("tvos")]
				[SupportedOSPlatform ("maccatalyst13.1")]
				set
				{
					SetNativeValue (TestNamespace.OuterClass.InnerClass.NestedStrongDictionary.Keys.ColorSpace, value);
				}
			}

			[SupportedOSPlatform ("macos")]
			[SupportedOSPlatform ("ios")]
			[SupportedOSPlatform ("tvos")]
			[SupportedOSPlatform ("maccatalyst13.1")]
			public partial global::Metal.IMTLCommandQueue? MetalCommandQueue
			{
				[SupportedOSPlatform ("macos")]
				[SupportedOSPlatform ("ios")]
				[SupportedOSPlatform ("tvos")]
				[SupportedOSPlatform ("maccatalyst13.1")]
				get
				{
					return Dictionary [TestNamespace.OuterClass.InnerClass.NestedStrongDictionary.Keys.MetalCommandQueue] as global::Metal.IMTLCommandQueue;
				}

				[SupportedOSPlatform ("macos")]
				[SupportedOSPlatform ("ios")]
				[SupportedOSPlatform ("tvos")]
				[SupportedOSPlatform ("maccatalyst13.1")]
				set
				{
					SetNativeValue (TestNamespace.OuterClass.InnerClass.NestedStrongDictionary.Keys.MetalCommandQueue, value);
				}
			}
		}
	}
}
