// <auto-generated />

#nullable enable

using CoreGraphics;
using Foundation;
using Metal;
using ObjCBindings;
using System;
using System.Runtime.Versioning;

namespace TestNamespace;

public partial class CARendererOptions
{
	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	public static partial class Keys
	{

		static global::Foundation.NSString? _ColorSpace;

		[SupportedOSPlatform ("macos")]
		[SupportedOSPlatform ("ios")]
		[SupportedOSPlatform ("tvos")]
		[SupportedOSPlatform ("maccatalyst13.1")]
		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		public static partial global::Foundation.NSString ColorSpace
		{
			[SupportedOSPlatform ("macos")]
			[SupportedOSPlatform ("ios")]
			[SupportedOSPlatform ("tvos")]
			[SupportedOSPlatform ("maccatalyst13.1")]
			get
			{
				if (_ColorSpace is null)
					_ColorSpace = global::ObjCRuntime.Dlfcn.GetStringConstant (global::ObjCRuntime.Libraries.TestNamespace.Handle, "AVCaptureDeviceTypeBuiltInTelephotoCamera")!;
				return _ColorSpace;
			}
		}

		static global::Foundation.NSString? _MetalCommandQueue;

		[SupportedOSPlatform ("macos")]
		[SupportedOSPlatform ("ios")]
		[SupportedOSPlatform ("tvos")]
		[SupportedOSPlatform ("maccatalyst13.1")]
		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		public static partial global::Foundation.NSString MetalCommandQueue
		{
			[SupportedOSPlatform ("macos")]
			[SupportedOSPlatform ("ios")]
			[SupportedOSPlatform ("tvos")]
			[SupportedOSPlatform ("maccatalyst13.1")]
			get
			{
				if (_MetalCommandQueue is null)
					_MetalCommandQueue = global::ObjCRuntime.Dlfcn.GetStringConstant (global::ObjCRuntime.Libraries.TestNamespace.Handle, "kCARendererMetalCommandQueue")!;
				return _MetalCommandQueue;
			}
		}
	}
}
