<Project>
  <Import Project="../targets/Microsoft.$(_PlatformName).Sdk.Versions.props" />

  <PropertyGroup>
    <TargetFramework>net$(BundledNETCoreAppTargetFrameworkVersion)</TargetFramework>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <PackageType Condition="'$(PackageType)'==''">DotnetPlatform</PackageType>
    <PackageVersion>$(_PackageVersion)</PackageVersion>
    <RepositoryUrl>https://github.com/dotnet/macios</RepositoryUrl>
    <RepositoryBranch>$(CurrentBranch)</RepositoryBranch>
    <RepositoryCommit>$(CurrentHash)</RepositoryCommit>
    <Authors>Microsoft</Authors>
    <Copyright>© Microsoft Corporation. All rights reserved.</Copyright>
    <PackageProjectUrl>https://dot.net</PackageProjectUrl>
    <Owners>microsoft,dotnetframework</Owners>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageIcon>Icon.png</PackageIcon>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <!-- Remove the `<group targetFramework=".NETStandard2.0" />` entry from the .nuspec. -->
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <!-- Ignore TargetFramework reference group related warnings, these are workload packs not functional NuGets. -->
    <!-- NU5105: The package version '#.#.#-alpha.##+hash' uses SemVer 2.0.0 or components of SemVer 1.0.0 that are not supported on legacy clients. Change the package version to a SemVer 1.0.0 string. If the version contains a release label it must start with a letter. This message can be ignored if the package is not intended for older clients. -->
    <NoWarn>$(NoWarn);NU5105;NU5128;NU5131</NoWarn>
    <!-- Properties to control ref, runtime, and tool pack creation managed by https://github.com/dotnet/arcade/blob/2b1931c05dd6ceb89120131a8b39eaa81735179a/src/Microsoft.DotNet.SharedFramework.Sdk/targets/sharedfx.targets -->
    <SharedFrameworkName>Microsoft.$(_PlatformName)</SharedFrameworkName>
    <SharedFrameworkFriendlyName>.NET $(BundledNETCoreAppTargetFrameworkVersion) - $(SharedFrameworkName)</SharedFrameworkFriendlyName>
    <SkipInstallerBuild>true</SkipInstallerBuild>
    <SkipValidatePackage>true</SkipValidatePackage>
    <PermitDllAndExeFilesLackingFileVersion>true</PermitDllAndExeFilesLackingFileVersion>
  </PropertyGroup>

  <PropertyGroup>
    <_RepositoryPath>$(MSBuildThisFileDirectory)../..</_RepositoryPath>
    <_buildPath>$(_RepositoryPath)/_build</_buildPath>
    <_packagePath Condition="'$(_packagePath)' == ''">$(_buildPath)\$(PackageId)\</_packagePath>
    <NupkgPath Condition=" '$(NupkgPath)' == '' ">$([MSBuild]::NormalizeDirectory ('$(_buildPath)\nupkgs\'))</NupkgPath>
    <BarManifestOutputPath Condition=" '$(BarManifestOutputPath)' == '' ">$(NupkgPath)\bar-manifests\$(_PlatformName)</BarManifestOutputPath>
    <_AssemblyInfix Condition="'$(_PlatformName)' == 'iOS'">iOS</_AssemblyInfix>
    <_AssemblyInfix Condition="'$(_PlatformName)' == 'tvOS'">tvOS</_AssemblyInfix>
    <_AssemblyInfix Condition="'$(_PlatformName)' == 'macOS'">macOS</_AssemblyInfix>
    <_AssemblyInfix Condition="'$(_PlatformName)' == 'MacCatalyst'">MacCatalyst</_AssemblyInfix>
    <LicenseFile>$(_RepositoryPath)/$(PackageLicenseFile)</LicenseFile>
  </PropertyGroup>

  <ItemGroup Condition=" '$(PlatformPackageType)' == '' ">
    <None Include="$(_RepositoryPath)/LICENSE" Pack="true" PackagePath="/" />
    <None Include="$(MSBuildThisFileDirectory)Icon.png" Pack="true" PackagePath="/" />
    <Content Include="$(_packagePath)**" Pack="true" PackagePath="/" />
  </ItemGroup>

  <!-- Always include symbols files, otherwise set %(FilesToPackage.IsSymbolFile) to true to only include in symbols.nupkg files -->
  <ItemGroup Condition=" '$(PlatformPackageType)' == 'RuntimePack' or '$(PlatformPackageType)' == 'ToolPack' ">
    <Content Include="$(_packagePath)**/*.pdb" Pack="true" PackagePath="/" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.DotNet.Build.Tasks.Feed" Version="$(MicrosoftDotNetBuildTasksFeedPackageVersion)" PrivateAssets="all" />
    <PackageReference Include="Microsoft.DotNet.Arcade.Sdk" Version="$(MicrosoftDotNetBuildTasksFeedPackageVersion)" PrivateAssets="all" GeneratePathProperty="true" />
  </ItemGroup>

  <!-- Remove the KnownFrameworkReference declared in ../targets/Microsoft.$(_PlatformName).Sdk.Versions.props so that we do not attempt to restore/include the ref/runtime packs that we are trying to build -->
  <Target Name="_RemoveThisFrameworkReference"
      BeforeTargets="ProcessFrameworkReferences" >
    <ItemGroup>
      <KnownFrameworkReference Remove="Microsoft.$(_PlatformName)" />
      <KnownFrameworkReference Remove="Microsoft.$(_PlatformName).Runtimes" />
    </ItemGroup>
  </Target>

  <Target Name="_IncludePlatformPackageContent"
      Condition=" '$(PlatformPackageType)' != '' "
      BeforeTargets="GetFilesToPackage" >
    <PropertyGroup Condition=" '$(PlatformPackageType)' == 'TargetingPack' ">
      <_PackTargetPath>ref/net$(BundledNETCoreAppTargetFrameworkVersion)</_PackTargetPath>
      <_PackNativePath>runtimes/$(_RuntimeIdentifier)/native</_PackNativePath>
    </PropertyGroup>
    <PropertyGroup Condition=" '$(PlatformPackageType)' == 'RuntimePack' ">
      <_PackTargetPath>runtimes/$(_RuntimeIdentifier)/lib/net$(BundledNETCoreAppTargetFrameworkVersion)</_PackTargetPath>
      <_PackNativePath>runtimes/$(_RuntimeIdentifier)/native</_PackNativePath>
    </PropertyGroup>
    <ItemGroup Condition=" '$(PlatformPackageType)' == 'TargetingPack' or '$(PlatformPackageType)' == 'RuntimePack' " >
      <_FxAssembliesToPackage Include="$(_packagePath)$(_PackTargetPath)/*.dll" />
      <FilesToPackage Include="@(_FxAssembliesToPackage)" TargetPath="$(_PackTargetPath)" />
      <_RuntimeHeadersToPackage Include="$(_packagePath)$(_PackNativePath)/**/*.h" Condition=" '$(PlatformPackageType)' == 'RuntimePack' " />
      <FilesToPackage Include="@(_RuntimeHeadersToPackage)" TargetPath="$(_PackNativePath)/%(RecursiveDir)" />
      <NativeRuntimeAsset Include="$(_packagePath)$(_PackNativePath)/*.a" />
      <NativeRuntimeAsset Include="$(_packagePath)$(_PackNativePath)/*.dylib" />
      <FrameworkListFileClass Include="@(_FxAssembliesToPackage->'%(Filename)%(Extension)')" Profile="$(_PlatformName)" />
      <FrameworkListFileClass Include="@(NativeRuntimeAsset->'%(Filename)%(Extension)')" Profile="$(_PlatformName)" />
    </ItemGroup>
    <ItemGroup Condition=" '$(PlatformPackageType)' == 'ToolPack' " >
      <_ToolsFilesToPackage Include="$(_packagePath)**" />
      <FilesToPackage Include="@(_ToolsFilesToPackage)" TargetPath="%(RecursiveDir)" />
    </ItemGroup>
    <ItemGroup>
      <FilesToPackage Include="$(MSBuildThisFileDirectory)Icon.png" TargetPath="\" />
    </ItemGroup>
  </Target>

  <Target Name="_CopyFileLists"
      Condition=" '$(PlatformPackageType)' == 'TargetingPack' or '$(PlatformPackageType)' == 'RuntimePack' "
      AfterTargets="_GenerateFrameworkList" >
    <PropertyGroup>
     <_FrameworkListFileName Condition=" '$(PlatformPackageType)' == 'TargetingPack' ">FrameworkList.xml</_FrameworkListFileName>
     <_FrameworkListFileName Condition=" '$(PlatformPackageType)' == 'RuntimePack' ">RuntimeList.xml</_FrameworkListFileName>
    </PropertyGroup>
    <Copy
        SourceFiles="$(IntermediateOutputPath)$(_FrameworkListFileName)"
        DestinationFiles="$(_packagePath)data/$(_FrameworkListFileName)"
    />
  </Target>


  <!-- https://github.com/dotnet/arcade/blob/00d6decc59f5030c2399a64fd3e4f6e8e11bacca/Documentation/DependencyFlowOnboardingWithoutArcade.md -->
  <Target Name="PushManifestToBuildAssetRegistry" >
    <PropertyGroup>
      <ArtifactsLogDir>$(BarManifestOutputPath)</ArtifactsLogDir>
      <AssetManifestFileName>Assets.xml</AssetManifestFileName>
      <AssetManifestPath>$(ArtifactsLogDir)AssetManifest\$(AssetManifestFileName)</AssetManifestPath>
      <IsStableBuild Condition=" '$(PrereleaseIdentifier)' == '' ">true</IsStableBuild>
      <IsStableBuild Condition=" '$(PrereleaseIdentifier)' != '' ">false</IsStableBuild>
    </PropertyGroup>

    <Error Condition="Exists($(AssetManifestPath))" Text="The manifest file '$(AssetManifestPath)' already exists." />

    <ItemGroup>
      <ItemsToPush Include="$(NupkgPath)\*.nupkg" Kind="Package" />
      <WorkloadArtifacts Include="$(NupkgPath)\*.zip" />
      <ItemsToPush Include="@(WorkloadArtifacts)" PublishFlatContainer="true" RelativeBlobPath="macios/$(_PackageVersion)/%(Filename)%(Extension)" Kind="Blob" />
    </ItemGroup>

    <Error Condition="'@(ItemsToPush)' == ''" Text="No packages to push." />

    <Message Text="Publishing %(ItemsToPush.Identity)" Importance="normal" />

    <ItemGroup>
      <ManifestBuildData Include="InitialAssetsLocation=" />
      <ManifestBuildData Include="AzureDevOpsBuildId=$(BUILD_BUILDID)" />
      <ManifestBuildData Include="AzureDevOpsBuildDefinitionId=$(SYSTEM_DEFINITIONID)" />
      <ManifestBuildData Include="AzureDevOpsProject=$(SYSTEM_TEAMPROJECT)" />
      <ManifestBuildData Include="AzureDevOpsBuildNumber=$(BUILD_BUILDNUMBER)" />
      <ManifestBuildData Include="AzureDevOpsRepository=$(BUILD_REPOSITORY_URI)" />
      <ManifestBuildData Include="AzureDevOpsBranch=$(BUILD_SOURCEBRANCH)" />
    </ItemGroup>

    <PushToBuildStorage
        ItemsToPush="@(ItemsToPush)"
        IsStableBuild="$(IsStableBuild)"
        ManifestBuildData="@(ManifestBuildData)"
        ManifestRepoUri="$(BUILD_REPOSITORY_NAME)"
        ManifestBranch="$(BUILD_SOURCEBRANCH)"
        ManifestBuildId="$(BUILD_BUILDNUMBER)"
        ManifestCommit="$(BUILD_SOURCEVERSION)"
        AssetManifestPath="$(AssetManifestPath)"
        PublishingVersion="3" />

    <MSBuild
        Targets="Restore"
        Projects="$(PkgMicrosoft_DotNet_Arcade_Sdk)\toolset\PublishBuildAssets.proj"
        Properties="Configuration=$(Configuration);RepoRoot=$(_RepositoryPath);VersionPrefix=$(_PackageVersion);NuGetPackageRoot=$(_RepositoryPath)\packages\"
    />

    <MSBuild
        Projects="$(PkgMicrosoft_DotNet_Arcade_Sdk)\toolset\PublishBuildAssets.proj"
        Properties="Configuration=$(Configuration);RepoRoot=$(_RepositoryPath);VersionPrefix=$(_PackageVersion);ManifestsPath=$(ArtifactsLogDir)AssetManifest;MaestroApiEndpoint=https://maestro.dot.net;NuGetPackageRoot=$(_RepositoryPath)\packages\"
    />
  </Target>

</Project>
