<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<Import Project="$(MSBuildThisFileDirectory)../Directory.Build.props" />
	<Import Project="$(MSBuildThisFileDirectory)../eng/Versions.props" />
	<PropertyGroup>
		<RootTestsDirectory>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))</RootTestsDirectory>

		<!-- Setting TargetsCurrent=true is necessary until we get https://github.com/dotnet/sdk/pull/52031 -->
		<!-- Ref: https://github.com/dotnet/macios/issues/24418 -->
		<TargetsCurrent>true</TargetsCurrent>
	</PropertyGroup>
</Project>
