parameters:

- name: keyringPass
  type: string

- name: enableDotnet
  type: boolean
  default: false

- name: skipESRP
  type: boolean
  default: false # only to be used when testing the CI and we do not need a signed pkg

- name: signingSetupSteps
  type: stepList
  default: []

- name: isPR
  type: boolean

- name: packages
  type: object
  default: []

jobs:
- job: configure
  displayName: 'Configure build'
  pool:
    vmImage: windows-latest

  variables:
    isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
    isScheduled: $[eq(variables['Build.Reason'], 'Schedule')]

  steps:
  - template: ../common/configure.yml

- ${{ each pkg in parameters.packages }}:
  - job: ${{ pkg.job }}
    dependsOn:
    - configure
    displayName: 'Sign & Notarize ${{ pkg.name }}'
    condition: ne(dependencies.configure.outputs['configure_platforms.${{ pkg.conditionVariable }}'],'')
    timeoutInMinutes: 1000
    pool:
      vmImage: internal-macos-11
    workspace:
      clean: all

    steps:
    - template: sign-and-notarized.yml
      parameters:
        isPR: ${{ parameters.isPR }}
        signingSetupSteps: ${{ parameters.signingSetupSteps }}
        keyringPass: ${{ parameters.keyringPass }}
        skipESRP: ${{ parameters.skipESRP }}
        packageName: ${{ pkg.name }}
        packagePattern: ${{ pkg.pattern }}
