parameters:

- name: provisionatorChannel
  type: string
  default: 'latest'

- name: runTests
  type: boolean
  default: true

- name: runWindowsIntegration
  type: boolean
  default: true

- name: isPR
  type: boolean

- name: repositoryAlias
  type: string
  default: self

- name: commit
  type: string
  default: HEAD

- name: xcodeChannel
  type: string

- name: macOSName
  type: string

- name: macTestsConfigurations
  displayName: macOS test configurations to run
  type: object
  default: [
    {
      stageName: 'mac_12_m1',
      displayName: 'M1 - Mac Monterey (12)',
      label: 'mac_monterey',
      macPool: 'VSEng-VSMac-Xamarin-Shared',
      useImage: false,
      statusContext: 'M1 - Mac Monterey (12)',
      demands: [
        "Agent.OS -equals Darwin",
        "macOS.Name -equals Monterey",
        "macOS.Architecture -equals arm64",
        "Agent.HasDevices -equals False",
        "Agent.IsPaired -equals False"
      ]
    },
    {
      stageName: 'mac_13_m1',
      displayName: 'M1 - Mac Ventura (13)',
      label: 'mac_ventura',
      macPool: 'VSEng-VSMac-Xamarin-Shared',
      useImage: false,
      statusContext: 'M1 - Mac Ventura (13)',
      demands: [
        "Agent.OS -equals Darwin",
        "macOS.Name -equals Ventura",
        "macOS.Architecture -equals arm64",
        "Agent.HasDevices -equals False",
        "Agent.IsPaired -equals False"
      ]
    },
    {
      stageName: 'mac_14_x64',
      displayName: 'X64 - Mac Sonoma (14)',
      label: 'mac_sonoma',
      macPool: 'VSEng-VSMac-Xamarin-Shared',
      useImage: false,
      statusContext: 'X64 - Mac Sonoma (14)',
      demands: [
        "Agent.OS -equals Darwin",
        "macOS.Name -equals Sonoma",
        "macOS.Architecture -equals x64",
        "Agent.HasDevices -equals False",
        "Agent.IsPaired -equals False"
      ]
    },
    {
      stageName: 'mac_15_arm64',
      displayName: 'arm64 - Mac Sequoia (15)',
      label: 'mac_sequoia',
      macPool: 'VSEng-VSMac-Xamarin-Shared',
      useImage: false,
      statusContext: 'arm64 - Mac Sequoia (15)',
      demands: [
        "Agent.OS -equals Darwin",
        "macOS.Name -equals Sequoia",
        "macOS.Architecture -equals arm64",
        "Agent.HasDevices -equals False",
        "Agent.IsPaired -equals False"
      ]
    },
    {
      stageName: 'mac_26_arm64',
      displayName: 'arm64 - Mac Tahoe (26)',
      label: 'mac_tahoe',
      macPool: 'VSEng-VSMac-Xamarin-Shared',
      useImage: false,
      statusContext: 'arm64 - Mac Tahoe (26)',
      demands: [
        "Agent.OS -equals Darwin",
        "macOS.Name -equals Tahoe",
        "macOS.Architecture -equals arm64",
        "Agent.HasDevices -equals False",
        "Agent.IsPaired -equals False"
      ]
    }]

- name: stageDisplayNamePrefix
  type: string
  default: ''

- name: dependsOn
  type: string
  default: ''

- name: dependsOnResult
  type: string
  default: ''

- name: buildPackages
  type: boolean
  default: false

stages:

- template: ./build/linux-build-verification.yml
  parameters:
    isPR: ${{ parameters.isPR }}
    repositoryAlias: ${{ parameters.repositoryAlias }}
    commit: ${{ parameters.commit }}
    stageDisplayNamePrefix: ${{ parameters.stageDisplayNamePrefix }}

- stage: configure_build
  displayName: '${{ parameters.stageDisplayNamePrefix }}Configure'
  dependsOn: ${{ parameters.dependsOn }}
  ${{ if and(ne(parameters.dependsOn, ''), ne(parameters.dependsOnResult, '')) }}:
    condition: eq(dependencies.${{ parameters.dependsOn }}.result, '${{ parameters.dependsOnResult }}')
  jobs:
  
  - job: configure
    displayName: 'Configure build'
    pool:
      vmImage: windows-latest

    variables:
      isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
      isScheduled: $[eq(variables['Build.Reason'], 'Schedule')]
      BRANCH_NAME: $[ replace(variables['Build.SourceBranch'], 'refs/heads/', '') ]

    steps:
    - ${{ if eq(parameters.buildPackages, true) }}:
      # When building packages in this pipeline, generate configuration from scratch
      - template: common/configure.yml
        parameters:
          repositoryAlias: ${{ parameters.repositoryAlias }}
          commit: ${{ parameters.commit }}
          statusContext: 'VSTS: simulator tests'
          uploadArtifacts: true
          use1ES: false
          isPR: ${{ parameters.isPR }}
    - ${{ else }}:
      # When using pre-built packages from a pipeline resource, load existing configuration
      - template: common/load_configuration.yml
        parameters: 
          repositoryAlias: ${{ parameters.repositoryAlias }}
          commit: ${{ parameters.commit }}
          statusContext: 'VSTS: simulator tests' 
          uploadArtifacts: true
          use1ES: false

# When buildPackages is true, build packages as part of this pipeline
- ${{ if eq(parameters.buildPackages, true) }}:
  - stage: build_packages
    displayName: '${{ parameters.stageDisplayNamePrefix }}Build'
    dependsOn: [configure_build]
    jobs:
    - job: build
      displayName: 'Build packages'
      timeoutInMinutes: 1000
      variables:
        DOTNET_PLATFORMS: $[ stageDependencies.configure_build.configure.outputs['configure_platforms.DOTNET_PLATFORMS'] ]
        INCLUDE_DOTNET_IOS: $[ stageDependencies.configure_build.configure.outputs['configure_platforms.INCLUDE_DOTNET_IOS'] ]
        INCLUDE_DOTNET_MACCATALYST: $[ stageDependencies.configure_build.configure.outputs['configure_platforms.INCLUDE_DOTNET_MACCATALYST'] ]
        INCLUDE_DOTNET_MACOS: $[ stageDependencies.configure_build.configure.outputs['configure_platforms.INCLUDE_DOTNET_MACOS'] ]
        INCLUDE_DOTNET_TVOS: $[ stageDependencies.configure_build.configure.outputs['configure_platforms.INCLUDE_DOTNET_TVOS'] ]
        BuildPackage: $[ stageDependencies.configure_build.configure.outputs['labels.build_package'] ]
        SkipPackages: $[ stageDependencies.configure_build.configure.outputs['labels.skip_packages'] ]
        SkipNugets: $[ stageDependencies.configure_build.configure.outputs['labels.skip_nugets'] ]
        SkipSigning: $[ stageDependencies.configure_build.configure.outputs['labels.skip_signing'] ]
        SkipApiComparison: $[ stageDependencies.configure_build.configure.outputs['labels.skip_api_comparison'] ]
        PR_ID: $[ stageDependencies.configure_build.configure.outputs['labels.pr_number'] ]
        BRANCH_NAME: $[ replace(variables['Build.SourceBranch'], 'refs/heads/', '') ]
        XHARNESS_LABELS: $[ stageDependencies.configure_build.configure.outputs['labels.xharness_labels'] ]
        RUN_MAC_TESTS: $[ stageDependencies.configure_build.configure.outputs['decisions.RUN_MAC_TESTS'] ]
      pool:
        name: $(PRBuildPool)
        demands:
        - Agent.OS -equals Darwin
        - Agent.OSVersion -gtVersion $(minimumMacOSVersion)
        - macOS.Name -equals ${{ parameters.macOSName }}
        - XcodeChannel -equals ${{ parameters.xcodeChannel }}
      steps:
      - template: build/build-pkgs.yml
        parameters:
          isPR: ${{ parameters.isPR }}
          repositoryAlias: ${{ parameters.repositoryAlias }}
          commit: ${{ parameters.commit }}
          vsdropsPrefix: ${{ variables.vsdropsPrefix }}
          keyringPass: $(pass--lab--mac--builder--keychain)
          gitHubToken: $(Github.Token)
          xqaCertPass: $(xqa--certificates--password)
          use1ES: false
          xcodeChannel: ${{ parameters.xcodeChannel }}

# always run simulator tests
- template: ./tests/stage.yml
  parameters:
    xcodeChannel: ${{ parameters.xcodeChannel }}
    macOSName: ${{ parameters.macOSName }}
    isPR: ${{ parameters.isPR }}
    repositoryAlias: ${{ parameters.repositoryAlias }}
    commit: ${{ parameters.commit }}
    stageName: 'simulator_tests'
    displayName: '${{ parameters.stageDisplayNamePrefix }}Simulator tests'
    testPool: $(PRBuildPool)
    statusContext: 'VSTS: simulator tests'
    vsdropsPrefix: ${{ variables.vsdropsPrefix }}
    keyringPass: $(pass--lab--mac--builder--keychain)
    gitHubToken: $(Github.Token)
    xqaCertPass: $(xqa--certificates--password)
    condition: ${{ parameters.runTests }}
    postPipeline: ${{ not(parameters.buildPackages) }}

- template: ./tests/publish-results.yml
  parameters:
    displayName: '${{ parameters.stageDisplayNamePrefix }}Publish Test Results'
    stageName: 'publish_test_results'
    statusContext: 'VSTS: test results'
    vsdropsPrefix: ${{ variables.vsdropsPrefix }}
    condition: ${{ parameters.runTests }}
    isPR: ${{ parameters.isPR }}
    repositoryAlias: ${{ parameters.repositoryAlias }}
    commit: ${{ parameters.commit }}
    postPipeline: ${{ not(parameters.buildPackages) }}
    macTestsConfigurations: ${{ parameters.macTestsConfigurations }}

- ${{ if eq(parameters.runWindowsIntegration, true) }}:
  - template: ./windows/stage.yml
    parameters:
      isPR: ${{ parameters.isPR }}
      repositoryAlias: ${{ parameters.repositoryAlias }}
      commit: ${{ parameters.commit }}
      stageName: windows_integration
      displayName: '${{ parameters.stageDisplayNamePrefix }}Windows Integration Tests'
      pool: 'VSEng-Xamarin-Mac-Devices' # currently ignored until the VS team provides a real one
      statusContext: 'Windows Integration Tests'
      gitHubToken: $(Github.Token)
      xqaCertPass: $(xqa--certificates--password)
      postPipeline: ${{ not(parameters.buildPackages) }}

- stage: build_macos_tests
  displayName: '${{ parameters.stageDisplayNamePrefix }}Build macOS tests'
  dependsOn:
  - configure_build
  - ${{ if eq(parameters.buildPackages, true) }}:
    - build_packages
  condition: and(succeeded(), ne(dependencies.configure_build.outputs['configure.configure_platforms.DOTNET_PLATFORMS'], ''))
  jobs:
  - template: ./build/build-mac-tests-stage.yml
    parameters:
      xcodeChannel: ${{ parameters.xcodeChannel }}
      macOSName: ${{ parameters.macOSName }}
      isPR: ${{ parameters.isPR }}
      repositoryAlias: ${{ parameters.repositoryAlias }}
      commit: ${{ parameters.commit }}
      vsdropsPrefix: ${{ variables.vsdropsPrefix }}
      keyringPass: $(pass--lab--mac--builder--keychain)
      gitHubToken: $(Github.Token)
      xqaCertPass: $(xqa--certificates--password)
      pool: $(PRBuildPool)

- ${{ each config in parameters.macTestsConfigurations }}:
  - template: ./mac/stage.yml
    parameters:
      isPR: ${{ parameters.isPR }}
      repositoryAlias: ${{ parameters.repositoryAlias }}
      commit: ${{ parameters.commit }}
      stageName: ${{ config.stageName }}
      displayName: ' ${{ parameters.stageDisplayNamePrefix }}${{ config.displayName }}'
      macPool: ${{ config.macPool }}
      useImage: ${{ config.useImage }}
      statusContext: ${{ config.statusContext }}
      keyringPass: $(pass--lab--mac--builder--keychain)
      demands: ${{ config.demands }}
      xqaCertPass: $(xqa--certificates--password)
      postPipeline: ${{ not(parameters.buildPackages) }}
      label: ${{ config.label }}
