parameters:

- name: statusContext
  type: string 
  default: 'Windows Integration Tests'

steps:

- template: ../common/checkout.yml

- pwsh : |
    gci env: | format-table -autosize -wrap
  displayName: 'Dump Environment'
