parameters:

- name: statusContext
  type: string 
  default: 'Windows Integration Tests'

- name: isPR
  type: boolean

- name: repositoryAlias
  type: string
  default: self

- name: commit
  type: string
  default: HEAD

steps:

- template: ../common/checkout.yml
  parameters:
    isPR: ${{ parameters.isPR }}
    repositoryAlias: ${{ parameters.repositoryAlias }}
    commit: ${{ parameters.commit }}

- pwsh: |
    gci env: | format-table -autosize -wrap
  displayName: 'Dump Environment'

- task: DownloadPipelineArtifact@2
  displayName: Download artifacts
  inputs:
    allowFailedBuilds: true
    path: $(Build.SourcesDirectory)/artifacts

# FIXME: parameterize platforms
# FIXME: SOURCES?

- pwsh: |
    & dotnet workload install --from-rollback-file "$(Build.SourcesDirectory)/artifacts/WorkloadRollback/WorkloadRollback.json" --source "$(Build.SourcesDirectory)/artifacts/not-signed-package" --verbosity diag ios tvos macos maccatalyst
  displayName: 'Install workloads'
  continueOnError: true

- pwsh: |
    & dotnet --version
    & dotnet --info
    & dotnet workload list
  displayName: 'Show .NET info'
  continueOnError: true

- pwsh: |
    & dotnet build "$(Build.SourcesDirectory)/xamarin-macios/tools/devops/automation/templates/windows/DotNet.csproj" --verbosity diag -bl -p:RestoreFallbackFolders=clear
  displayName: 'Install custom .NET'
  continueOnError: true

- pwsh: |
    & dotnet build "$(Build.SourcesDirectory)/xamarin-macios/tools/devops/automation/templates/windows/DotNet.csproj" --verbosity diag -bl -p:RestoreFallbackFolders=clear -t:Install
  displayName: 'Install workloads'
  continueOnError: true

- pwsh: |
    Write-Host "Trying to ssh to the mac bot..."
    & ssh builder@$($Env:MAC_AGENT_IP) 'ls -la'
  displayName: Diagnostics with pwsh 1
  continueOnError: true
  timeoutInMinutes: 1

- pwsh: |
    Write-Host "Trying to ssh to the mac bot..."
    (Get-Command New-PSSession).ParameterSets.Name
    $session = New-PSSession -HostName builder@$($Env:MAC_AGENT_IP)
    $session
    Invoke-Command $session -ScriptBlock { Get-Process powershell }
  displayName: Diagnostics with pwsh 2
  continueOnError: true
  timeoutInMinutes: 1

- pwsh: |
    Write-Host "Sending ping to $($Env:MAC_AGENT_IP)..."
    Test-Connection -TargetName "$($Env:MAC_AGENT_IP)" -Count 3
  displayName: "Diagnostics with pwsh - ping"
  continueOnError: true
  timeoutInMinutes: 1

- pwsh: |
    Write-Host "Run windows tests."
    Write-Host "Mac agent to be used:"
    Write-Host "Mac agent pool: $Env:MAC_AGENT_POOL"
    Write-Host "Mac agent name: $Env:MAC_AGENT_NAME"
    Write-Host "Mac agent IP: $Env:MAC_AGENT_IP"
  displayName: Run tests

# Upload all the binlogs
# Copy all the binlogs to a separate directory, keeping directory structure.
- pwsh: |
    $sourceDir = '$(Build.SourcesDirectory)/xamarin-macios'
    $targetDir = ' $(Build.ArtifactStagingDirectory)/all-binlogs'

    Get-ChildItem $sourceDir -filter "*.binlog" -recurse | `
        foreach{
            $targetFile = $targetDir + $_.FullName.SubString($sourceDir.Length);
            New-Item -ItemType File -Path $targetFile -Force;
            Copy-Item $_.FullName -destination $targetFile
        }
  displayName: Copy all binlogs
  continueOnError: true
  condition: succeededOrFailed()

# Publish all the binlogs we collected in the previous step
- task: PublishPipelineArtifact@1
  displayName: 'Publish Artifact: Windows binlogs'
  inputs:
    targetPath: $(Build.ArtifactStagingDirectory)/windows-binlogs
    artifactName: windows-binlogs-test-$(Build.BuildId)-$(System.JobAttempt)
  continueOnError: true
  condition: succeededOrFailed()

- pwsh: |
    Import-Module $Env:SYSTEM_DEFAULTWORKINGDIRECTORY\xamarin-macios\tools\devops\automation\scripts\MaciosCI.psd1

    $gihubComments = New-GitHubCommentsObject -Org "xamarin" -Repo "xamarin-macios" -Token $Env:GITHUB_TOKEN -Hash $Env:GIT_HASH -Debug
    $sb = [System.Text.StringBuilder]::new()
    $sb.AppendLine("Reporting in from the Windows integration tests")
    $sb.AppendLine()
    $sb.AppendLine("Current status: $($Env:AGENT_JOBSTATUS)")
    $result = $gihubComments.NewCommentFromMessage("Test results", ":sparkles:", $sb.ToString())
  displayName: 'Add GitHub comment'
  env:
    CONTEXT: ${{ parameters.statusContext }}
    DEVICE_PREFIX: windows-integration-tests
    GITHUB_TOKEN: $(GitHub.Token)
    ACCESSTOKEN: $(System.AccessToken)
  condition: always()

- pwsh: |
    Import-Module $Env:SYSTEM_DEFAULTWORKINGDIRECTORY\xamarin-macios\tools\devops\automation\scripts\MaciosCI.psd1
    $vsts = New-VSTS -Org "devdiv" -Project "DevDiv" -Token $(DropsPAT)

    # get the pool and the agent objects and disable the bot
    $pool = $vsts.Pools.GetPool("$Env:MAC_AGENT_POOL")
    $agent = $vsts.Agents.GetAgent($pool, $Env:MAC_AGENT_NAME)
    $vsts.Agents.SetEnabled($pool, $agent, $True)
  displayName: 'Re-enabled macOS bot from pool'
  condition: always()
