# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

include ../shared.mk

# Build and run monotouch-test from the audio unit extension for this platform:
#    make build
#    make run
#
# Select the runtime, registrar and configuration using TEST_VARIATION (see
# tests/common/test-variations.csproj for the full list), e.g.:
#    make run TEST_VARIATION=coreclr
#    make run TEST_VARIATION='trimmable-static-registrar|release'
#
# Set TEST_FILTER to run a specific test instead of the full suite.
# Any arguments to 'dotnet build' can be set using the BUILD_PARAMETERS variable.
