using System;
using System.Linq;

using NUnit.Framework;
using Xamarin.Tests;

namespace GeneratorTests {
	[TestFixture ()]
	[Parallelizable (ParallelScope.All)]
	public class ProtocolTests : BGenBase {
#if !NET
		[Ignore ("This only applies to .NET")]
#endif
		[TestCase (Profile.MacCatalyst)]
		[TestCase (Profile.iOS)]
		public void OptionalMethod (Profile profile)
		{
			var bgen = BuildFile (profile, "tests/protocols.cs");

			var allTypeDefinitions = bgen.ApiAssembly.MainModule.GetTypes ().ToArray ();
			var allTypes = allTypeDefinitions.Select (v => v.FullName).ToArray ();
			Assert.That (allTypes, Does.Contain ("Protocols.RequiredProtocolCompatWithExtensions_Extensions"), "Compat extensions");

			Console.WriteLine ("Types:");
			var allTypeNames = allTypes.OrderBy (v => v).ToArray ();
			foreach (var t in allTypeNames)
				Console.WriteLine (t);

			var expectedTypes = new string [] {
				"<Module>",
				"api0.Messaging",
				"Protocols.IOptionalProtocol",
				"Protocols.IOptionalProtocolCompat",
				"Protocols.IRequiredProtocol",
				"Protocols.IRequiredProtocolCompat",
				"Protocols.IRequiredProtocolCompatWithExtensions",
				"Protocols.MyObject",
				"Protocols.MyObject2",
				"Protocols.OptionalProtocolCompat_Extensions",
				"Protocols.OptionalProtocolCompatWrapper",
				"Protocols.OptionalProtocolWrapper",
				"Protocols.RequiredProtocolCompatWithExtensions_Extensions",
				"Protocols.RequiredProtocolCompatWithExtensionsWrapper",
				"Protocols.RequiredProtocolCompatWrapper",
				"Protocols.RequiredProtocolWrapper",
			};
			CollectionAssert.AreEqual (expectedTypes, allTypeNames, "Types");



			Console.WriteLine ("Methods:");
			var allMethods = allTypeDefinitions.SelectMany (v => v.Methods).Select (v => v.ToString ()).OrderBy (v => v).ToArray ();
			foreach (var t in allMethods)
				Console.WriteLine (t);

			var expectedMethods = new string [] {
				"Foundation.NSObject Protocols.IOptionalProtocol::get_OptionalPropertyWeakSemantics()",
				"Foundation.NSObject Protocols.IOptionalProtocol::GetStaticOptionalPropertyWeakSemantics()",
				"Foundation.NSObject Protocols.IOptionalProtocolCompat::get_OptionalPropertyWeakSemantics()",
				"Foundation.NSObject Protocols.IOptionalProtocolCompat::GetStaticOptionalPropertyWeakSemantics()",
				"Foundation.NSObject Protocols.IRequiredProtocol::get_RequiredPropertyWeakSemantics()",
				"Foundation.NSObject Protocols.IRequiredProtocol::GetStaticRequiredPropertyWeakSemantics()",
				"Foundation.NSObject Protocols.IRequiredProtocolCompat::get_RequiredPropertyWeakSemantics()",
				"Foundation.NSObject Protocols.IRequiredProtocolCompat::GetStaticRequiredPropertyWeakSemantics()",
				"Foundation.NSObject Protocols.IRequiredProtocolCompatWithExtensions::get_RequiredPropertyWeakSemantics()",
				"Foundation.NSObject Protocols.IRequiredProtocolCompatWithExtensions::GetStaticRequiredPropertyWeakSemantics()",
				"Foundation.NSObject Protocols.MyObject::get_OptionalPropertyWeakSemantics()",
				"Foundation.NSObject Protocols.MyObject::get_RequiredPropertyWeakSemantics()",
				"Foundation.NSObject Protocols.MyObject::get_StaticOptionalPropertyWeakSemantics()",
				"Foundation.NSObject Protocols.MyObject::get_StaticRequiredPropertyWeakSemantics()",
				"Foundation.NSObject Protocols.MyObject2::get_OptionalPropertyWeakSemantics()",
				"Foundation.NSObject Protocols.MyObject2::get_RequiredPropertyWeakSemantics()",
				"Foundation.NSObject Protocols.MyObject2::get_StaticOptionalPropertyWeakSemantics()",
				"Foundation.NSObject Protocols.MyObject2::get_StaticRequiredPropertyWeakSemantics()",
				"Foundation.NSObject Protocols.OptionalProtocolCompat_Extensions::GetOptionalPropertyWeakSemantics(Protocols.IOptionalProtocolCompat)",
				"Foundation.NSObject Protocols.RequiredProtocolCompatWithExtensions_Extensions::GetRequiredPropertyWeakSemantics(Protocols.IRequiredProtocolCompatWithExtensions)",
				"Foundation.NSObject Protocols.RequiredProtocolCompatWithExtensionsWrapper::get_RequiredPropertyWeakSemantics()",
				"Foundation.NSObject Protocols.RequiredProtocolCompatWrapper::get_RequiredPropertyWeakSemantics()",
				"Foundation.NSObject Protocols.RequiredProtocolWrapper::get_RequiredPropertyWeakSemantics()",
				"ObjCRuntime.NativeHandle api0.Messaging::NativeHandle_objc_msgSend(System.IntPtr,System.IntPtr)",
				"ObjCRuntime.NativeHandle api0.Messaging::NativeHandle_objc_msgSendSuper(System.IntPtr,System.IntPtr)",
				"ObjCRuntime.NativeHandle Protocols.MyObject::get_ClassHandle()",
				"ObjCRuntime.NativeHandle Protocols.MyObject2::get_ClassHandle()",
				"System.Int32 api0.Messaging::int_objc_msgSend(System.IntPtr,System.IntPtr)",
				"System.Int32 api0.Messaging::int_objc_msgSendSuper(System.IntPtr,System.IntPtr)",
				"System.Int32 Protocols.IOptionalProtocol::get_InternalOptionalProperty()",
				"System.Int32 Protocols.IOptionalProtocol::get_OptionalProperty()",
				"System.Int32 Protocols.IOptionalProtocol::GetStaticOptionalProperty()",
				"System.Int32 Protocols.IOptionalProtocol::InternalOptionalMethod()",
				"System.Int32 Protocols.IOptionalProtocol::OptionalMethod()",
				"System.Int32 Protocols.IOptionalProtocol::StaticOptionalMethod()",
				"System.Int32 Protocols.IOptionalProtocolCompat::get_InternalOptionalProperty()",
				"System.Int32 Protocols.IOptionalProtocolCompat::get_OptionalProperty()",
				"System.Int32 Protocols.IOptionalProtocolCompat::GetStaticOptionalProperty()",
				"System.Int32 Protocols.IOptionalProtocolCompat::InternalOptionalMethod()",
				"System.Int32 Protocols.IOptionalProtocolCompat::OptionalMethod()",
				"System.Int32 Protocols.IOptionalProtocolCompat::StaticOptionalMethod()",
				"System.Int32 Protocols.IRequiredProtocol::get_InternalRequiredProperty()",
				"System.Int32 Protocols.IRequiredProtocol::get_RequiredProperty()",
				"System.Int32 Protocols.IRequiredProtocol::GetStaticRequiredProperty()",
				"System.Int32 Protocols.IRequiredProtocol::InternalRequiredMethod()",
				"System.Int32 Protocols.IRequiredProtocol::RequiredMethod()",
				"System.Int32 Protocols.IRequiredProtocol::StaticRequiredMethod()",
				"System.Int32 Protocols.IRequiredProtocolCompat::get_InternalRequiredProperty()",
				"System.Int32 Protocols.IRequiredProtocolCompat::get_RequiredProperty()",
				"System.Int32 Protocols.IRequiredProtocolCompat::GetStaticRequiredProperty()",
				"System.Int32 Protocols.IRequiredProtocolCompat::InternalRequiredMethod()",
				"System.Int32 Protocols.IRequiredProtocolCompat::RequiredMethod()",
				"System.Int32 Protocols.IRequiredProtocolCompat::StaticRequiredMethod()",
				"System.Int32 Protocols.IRequiredProtocolCompatWithExtensions::get_InternalRequiredProperty()",
				"System.Int32 Protocols.IRequiredProtocolCompatWithExtensions::get_RequiredProperty()",
				"System.Int32 Protocols.IRequiredProtocolCompatWithExtensions::GetStaticRequiredProperty()",
				"System.Int32 Protocols.IRequiredProtocolCompatWithExtensions::InternalRequiredMethod()",
				"System.Int32 Protocols.IRequiredProtocolCompatWithExtensions::RequiredMethod()",
				"System.Int32 Protocols.IRequiredProtocolCompatWithExtensions::StaticRequiredMethod()",
				"System.Int32 Protocols.MyObject::get_InternalOptionalProperty()",
				"System.Int32 Protocols.MyObject::get_InternalRequiredProperty()",
				"System.Int32 Protocols.MyObject::get_OptionalProperty()",
				"System.Int32 Protocols.MyObject::get_RequiredProperty()",
				"System.Int32 Protocols.MyObject::get_StaticOptionalProperty()",
				"System.Int32 Protocols.MyObject::get_StaticRequiredProperty()",
				"System.Int32 Protocols.MyObject::InternalOptionalMethod()",
				"System.Int32 Protocols.MyObject::InternalRequiredMethod()",
				"System.Int32 Protocols.MyObject::OptionalMethod()",
				"System.Int32 Protocols.MyObject::RequiredMethod()",
				"System.Int32 Protocols.MyObject::StaticOptionalMethod()",
				"System.Int32 Protocols.MyObject::StaticRequiredMethod()",
				"System.Int32 Protocols.MyObject2::get_InternalOptionalProperty()",
				"System.Int32 Protocols.MyObject2::get_InternalRequiredProperty()",
				"System.Int32 Protocols.MyObject2::get_OptionalProperty()",
				"System.Int32 Protocols.MyObject2::get_RequiredProperty()",
				"System.Int32 Protocols.MyObject2::get_StaticOptionalProperty()",
				"System.Int32 Protocols.MyObject2::get_StaticRequiredProperty()",
				"System.Int32 Protocols.MyObject2::InternalOptionalMethod()",
				"System.Int32 Protocols.MyObject2::InternalRequiredMethod()",
				"System.Int32 Protocols.MyObject2::OptionalMethod()",
				"System.Int32 Protocols.MyObject2::RequiredMethod()",
				"System.Int32 Protocols.MyObject2::StaticOptionalMethod()",
				"System.Int32 Protocols.MyObject2::StaticRequiredMethod()",
				"System.Int32 Protocols.OptionalProtocolCompat_Extensions::GetInternalOptionalProperty(Protocols.IOptionalProtocolCompat)",
				"System.Int32 Protocols.OptionalProtocolCompat_Extensions::GetOptionalProperty(Protocols.IOptionalProtocolCompat)",
				"System.Int32 Protocols.OptionalProtocolCompat_Extensions::InternalOptionalMethod(Protocols.IOptionalProtocolCompat)",
				"System.Int32 Protocols.OptionalProtocolCompat_Extensions::OptionalMethod(Protocols.IOptionalProtocolCompat)",
				"System.Int32 Protocols.RequiredProtocolCompatWithExtensions_Extensions::GetInternalRequiredProperty(Protocols.IRequiredProtocolCompatWithExtensions)",
				"System.Int32 Protocols.RequiredProtocolCompatWithExtensions_Extensions::GetRequiredProperty(Protocols.IRequiredProtocolCompatWithExtensions)",
				"System.Int32 Protocols.RequiredProtocolCompatWithExtensions_Extensions::InternalRequiredMethod(Protocols.IRequiredProtocolCompatWithExtensions)",
				"System.Int32 Protocols.RequiredProtocolCompatWithExtensions_Extensions::RequiredMethod(Protocols.IRequiredProtocolCompatWithExtensions)",
				"System.Int32 Protocols.RequiredProtocolCompatWithExtensionsWrapper::get_InternalRequiredProperty()",
				"System.Int32 Protocols.RequiredProtocolCompatWithExtensionsWrapper::get_RequiredProperty()",
				"System.Int32 Protocols.RequiredProtocolCompatWithExtensionsWrapper::InternalRequiredMethod()",
				"System.Int32 Protocols.RequiredProtocolCompatWithExtensionsWrapper::RequiredMethod()",
				"System.Int32 Protocols.RequiredProtocolCompatWrapper::get_InternalRequiredProperty()",
				"System.Int32 Protocols.RequiredProtocolCompatWrapper::get_RequiredProperty()",
				"System.Int32 Protocols.RequiredProtocolCompatWrapper::InternalRequiredMethod()",
				"System.Int32 Protocols.RequiredProtocolCompatWrapper::RequiredMethod()",
				"System.Int32 Protocols.RequiredProtocolWrapper::get_InternalRequiredProperty()",
				"System.Int32 Protocols.RequiredProtocolWrapper::get_RequiredProperty()",
				"System.Int32 Protocols.RequiredProtocolWrapper::InternalRequiredMethod()",
				"System.Int32 Protocols.RequiredProtocolWrapper::RequiredMethod()",
				"System.IntPtr api0.Messaging::IntPtr_objc_msgSend_IntPtr(System.IntPtr,System.IntPtr,System.IntPtr)",
				"System.IntPtr api0.Messaging::IntPtr_objc_msgSend(System.IntPtr,System.IntPtr)",
				"System.IntPtr api0.Messaging::IntPtr_objc_msgSendSuper_IntPtr(System.IntPtr,System.IntPtr,System.IntPtr)",
				"System.IntPtr api0.Messaging::IntPtr_objc_msgSendSuper(System.IntPtr,System.IntPtr)",
				"System.Void api0.Messaging::.cctor()",
				"System.Void api0.Messaging::void_objc_msgSend_int(System.IntPtr,System.IntPtr,System.Int32)",
				"System.Void api0.Messaging::void_objc_msgSend_NativeHandle(System.IntPtr,System.IntPtr,ObjCRuntime.NativeHandle)",
				"System.Void api0.Messaging::void_objc_msgSendSuper_int(System.IntPtr,System.IntPtr,System.Int32)",
				"System.Void api0.Messaging::void_objc_msgSendSuper_NativeHandle(System.IntPtr,System.IntPtr,ObjCRuntime.NativeHandle)",
				"System.Void Protocols.IOptionalProtocol::set_InternalOptionalProperty(System.Int32)",
				"System.Void Protocols.IOptionalProtocol::set_OptionalProperty(System.Int32)",
				"System.Void Protocols.IOptionalProtocol::set_OptionalPropertyWeakSemantics(Foundation.NSObject)",
				"System.Void Protocols.IOptionalProtocol::SetStaticOptionalProperty(System.Int32)",
				"System.Void Protocols.IOptionalProtocol::SetStaticOptionalPropertyWeakSemantics(Foundation.NSObject)",
				"System.Void Protocols.IOptionalProtocolCompat::set_InternalOptionalProperty(System.Int32)",
				"System.Void Protocols.IOptionalProtocolCompat::set_OptionalProperty(System.Int32)",
				"System.Void Protocols.IOptionalProtocolCompat::set_OptionalPropertyWeakSemantics(Foundation.NSObject)",
				"System.Void Protocols.IOptionalProtocolCompat::SetStaticOptionalProperty(System.Int32)",
				"System.Void Protocols.IOptionalProtocolCompat::SetStaticOptionalPropertyWeakSemantics(Foundation.NSObject)",
				"System.Void Protocols.IRequiredProtocol::set_InternalRequiredProperty(System.Int32)",
				"System.Void Protocols.IRequiredProtocol::set_RequiredProperty(System.Int32)",
				"System.Void Protocols.IRequiredProtocol::set_RequiredPropertyWeakSemantics(Foundation.NSObject)",
				"System.Void Protocols.IRequiredProtocol::SetStaticRequiredProperty(System.Int32)",
				"System.Void Protocols.IRequiredProtocol::SetStaticRequiredPropertyWeakSemantics(Foundation.NSObject)",
				"System.Void Protocols.IRequiredProtocolCompat::set_InternalRequiredProperty(System.Int32)",
				"System.Void Protocols.IRequiredProtocolCompat::set_RequiredProperty(System.Int32)",
				"System.Void Protocols.IRequiredProtocolCompat::set_RequiredPropertyWeakSemantics(Foundation.NSObject)",
				"System.Void Protocols.IRequiredProtocolCompat::SetStaticRequiredProperty(System.Int32)",
				"System.Void Protocols.IRequiredProtocolCompat::SetStaticRequiredPropertyWeakSemantics(Foundation.NSObject)",
				"System.Void Protocols.IRequiredProtocolCompatWithExtensions::set_InternalRequiredProperty(System.Int32)",
				"System.Void Protocols.IRequiredProtocolCompatWithExtensions::set_RequiredProperty(System.Int32)",
				"System.Void Protocols.IRequiredProtocolCompatWithExtensions::set_RequiredPropertyWeakSemantics(Foundation.NSObject)",
				"System.Void Protocols.IRequiredProtocolCompatWithExtensions::SetStaticRequiredProperty(System.Int32)",
				"System.Void Protocols.IRequiredProtocolCompatWithExtensions::SetStaticRequiredPropertyWeakSemantics(Foundation.NSObject)",
				"System.Void Protocols.MyObject::.cctor()",
				"System.Void Protocols.MyObject::.ctor()",
				"System.Void Protocols.MyObject::.ctor(Foundation.NSObjectFlag)",
				"System.Void Protocols.MyObject::.ctor(ObjCRuntime.NativeHandle)",
				"System.Void Protocols.MyObject::Dispose(System.Boolean)",
				"System.Void Protocols.MyObject::set_InternalOptionalProperty(System.Int32)",
				"System.Void Protocols.MyObject::set_InternalRequiredProperty(System.Int32)",
				"System.Void Protocols.MyObject::set_OptionalProperty(System.Int32)",
				"System.Void Protocols.MyObject::set_OptionalPropertyWeakSemantics(Foundation.NSObject)",
				"System.Void Protocols.MyObject::set_RequiredProperty(System.Int32)",
				"System.Void Protocols.MyObject::set_RequiredPropertyWeakSemantics(Foundation.NSObject)",
				"System.Void Protocols.MyObject::set_StaticOptionalProperty(System.Int32)",
				"System.Void Protocols.MyObject::set_StaticOptionalPropertyWeakSemantics(Foundation.NSObject)",
				"System.Void Protocols.MyObject::set_StaticRequiredProperty(System.Int32)",
				"System.Void Protocols.MyObject::set_StaticRequiredPropertyWeakSemantics(Foundation.NSObject)",
				"System.Void Protocols.MyObject2::.cctor()",
				"System.Void Protocols.MyObject2::.ctor()",
				"System.Void Protocols.MyObject2::.ctor(Foundation.NSObjectFlag)",
				"System.Void Protocols.MyObject2::.ctor(ObjCRuntime.NativeHandle)",
				"System.Void Protocols.MyObject2::Dispose(System.Boolean)",
				"System.Void Protocols.MyObject2::set_InternalOptionalProperty(System.Int32)",
				"System.Void Protocols.MyObject2::set_InternalRequiredProperty(System.Int32)",
				"System.Void Protocols.MyObject2::set_OptionalProperty(System.Int32)",
				"System.Void Protocols.MyObject2::set_OptionalPropertyWeakSemantics(Foundation.NSObject)",
				"System.Void Protocols.MyObject2::set_RequiredProperty(System.Int32)",
				"System.Void Protocols.MyObject2::set_RequiredPropertyWeakSemantics(Foundation.NSObject)",
				"System.Void Protocols.MyObject2::set_StaticOptionalProperty(System.Int32)",
				"System.Void Protocols.MyObject2::set_StaticOptionalPropertyWeakSemantics(Foundation.NSObject)",
				"System.Void Protocols.MyObject2::set_StaticRequiredProperty(System.Int32)",
				"System.Void Protocols.MyObject2::set_StaticRequiredPropertyWeakSemantics(Foundation.NSObject)",
				"System.Void Protocols.OptionalProtocolCompat_Extensions::SetInternalOptionalProperty(Protocols.IOptionalProtocolCompat,System.Int32)",
				"System.Void Protocols.OptionalProtocolCompat_Extensions::SetOptionalProperty(Protocols.IOptionalProtocolCompat,System.Int32)",
				"System.Void Protocols.OptionalProtocolCompat_Extensions::SetOptionalPropertyWeakSemantics(Protocols.IOptionalProtocolCompat,Foundation.NSObject)",
				"System.Void Protocols.OptionalProtocolCompatWrapper::.ctor(ObjCRuntime.NativeHandle,System.Boolean)",
				"System.Void Protocols.OptionalProtocolWrapper::.ctor(ObjCRuntime.NativeHandle,System.Boolean)",
				"System.Void Protocols.RequiredProtocolCompatWithExtensions_Extensions::SetInternalRequiredProperty(Protocols.IRequiredProtocolCompatWithExtensions,System.Int32)",
				"System.Void Protocols.RequiredProtocolCompatWithExtensions_Extensions::SetRequiredProperty(Protocols.IRequiredProtocolCompatWithExtensions,System.Int32)",
				"System.Void Protocols.RequiredProtocolCompatWithExtensions_Extensions::SetRequiredPropertyWeakSemantics(Protocols.IRequiredProtocolCompatWithExtensions,Foundation.NSObject)",
				"System.Void Protocols.RequiredProtocolCompatWithExtensionsWrapper::.ctor(ObjCRuntime.NativeHandle,System.Boolean)",
				"System.Void Protocols.RequiredProtocolCompatWithExtensionsWrapper::set_InternalRequiredProperty(System.Int32)",
				"System.Void Protocols.RequiredProtocolCompatWithExtensionsWrapper::set_RequiredProperty(System.Int32)",
				"System.Void Protocols.RequiredProtocolCompatWithExtensionsWrapper::set_RequiredPropertyWeakSemantics(Foundation.NSObject)",
				"System.Void Protocols.RequiredProtocolCompatWrapper::.ctor(ObjCRuntime.NativeHandle,System.Boolean)",
				"System.Void Protocols.RequiredProtocolCompatWrapper::set_InternalRequiredProperty(System.Int32)",
				"System.Void Protocols.RequiredProtocolCompatWrapper::set_RequiredProperty(System.Int32)",
				"System.Void Protocols.RequiredProtocolCompatWrapper::set_RequiredPropertyWeakSemantics(Foundation.NSObject)",
				"System.Void Protocols.RequiredProtocolWrapper::.ctor(ObjCRuntime.NativeHandle,System.Boolean)",
				"System.Void Protocols.RequiredProtocolWrapper::set_InternalRequiredProperty(System.Int32)",
				"System.Void Protocols.RequiredProtocolWrapper::set_RequiredProperty(System.Int32)",
				"System.Void Protocols.RequiredProtocolWrapper::set_RequiredPropertyWeakSemantics(Foundation.NSObject)",
			};
			CollectionAssert.AreEqual (expectedMethods, allMethods, "Types");


			Assert.Fail ("CWL");
		}
	}
}

