parameters:
# name of the pool that contains the iOS devices
- name: macPool
  type: string

- name: useImage
  type: boolean
  default: false

- name: stageName
  type: string

- name: displayName
  type: string

- name: statusContext
  type: string
  default: '10.16'

- name: keyringPass
  type: string

- name: enableDotnet
  type: boolean
  default: false

- name: demands
  type: object
  default: []

- name: isPR
  type: boolean

stages:
- stage: DebugStage
  displayName: Debug stage
  dependsOn:
  - build_packages

  jobs:
  - job: DebugJob
    displayName: 'Debug job'
    pool:
      vmImage: windows-latest
    variables:
      STAGE_DEPS: $[ convertToJson(stageDependencies) ]
      DEPS: $[ convertToJson(dependencies) ]
      JOB_CONDITION: $[ stageDependencies.build_packages.configure.outputs['decisions.RUN_MAC_TESTS'] ]

    steps:
    - bash:
        env -0 | sort -z | tr '\0' '\n' || true
      displayName: "Show Env"

    steps:
    - bash:
        env -0 | sort -z | tr '\0' '\n' || true
      displayName: "Show Env 2"
    condition: and(succeeded(), eq(stageDependencies.build_packages.configure.outputs['decisions.RUN_MAC_TESTS'], 'true'))

- stage: TestStage
  displayName: Test stage
  dependsOn:
  - build_packages
  condition: and(succeeded(), eq(stageDependencies.build_packages.configure.outputs['decisions.RUN_MAC_TESTS'], 'true'))

  jobs:
  - job: DebugJob
    displayName: 'Debug job'
    pool:
      vmImage: windows-latest
    variables:
      STAGE_DEPS: $[ convertToJson(stageDependencies) ]
      DEPS: $[ convertToJson(dependencies) ]
      JOB_CONDITION: $[ stageDependencies.build_packages.configure.outputs['decisions.RUN_MAC_TESTS'] ]

    steps:
    - bash:
        env -0 | sort -z | tr '\0' '\n' || true
      displayName: "Show Env"

- stage: ${{ parameters.stageName }}
  displayName: ${{ parameters.displayName }}
  dependsOn:
  - build_packages
  condition: and(succeeded(), eq(stageDependencies.build_packages.configure.outputs['decisions.RUN_MAC_TESTS'], 'true'))
  variables:
    GITHUB_FAILURE_COMMENT_FILE: $(System.DefaultWorkingDirectory)/github-comment-file.md

  jobs:
  - job: configure
    displayName: 'Configure build'
    pool:
      vmImage: windows-latest

    variables:
      isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
      isScheduled: $[eq(variables['Build.Reason'], 'Schedule')]
      STAGE_DEPS: $[ convertToJson(stageDependencies) ]
      DEPS: $[ convertToJson(dependencies) ]

    steps:
    - bash:
        env -0 | sort -z | tr '\0' '\n' || true

    - template: ../common/configure.yml
      parameters: 
        uploadArtifacts: false
        enableDotnet: ${{ parameters.enableDotnet }}

  - job: run_tests
    dependsOn:
    - configure
    displayName: 'macOS tests'
    timeoutInMinutes: 1000
    workspace:
      clean: all

    pool:
      ${{ if eq(parameters.useImage, false) }}:
        name: ${{ parameters.macPool }}
        demands: ${{ parameters.demands }}
      ${{ else }}:
        vmImage: ${{ parameters.macPool }}

    variables:
      PR_ID: $[ dependencies.configure.outputs['labels.pr_number'] ]
      GIT_HASH: $[ stageDependencies.build_packages.build.outputs['fix_commit.GIT_HASH'] ]

    steps:
    - template: build.yml
      parameters:
        isPR: ${{ parameters.isPR }}
        statusContext: ${{ parameters.statusContext }}
        keyringPass: ${{ parameters.keyringPass }} 
