// <auto-generated />

#nullable enable

using Foundation;
using ObjCBindings;
using ObjCRuntime;
using System;

namespace GameKit;

[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
public static partial class GKErrorExtensions
{

	[Field ("GKErrorDomain", "GameKit")]
	static $GLOBAL$Foundation.NSString? _domain;

	/// <summary>Returns the error domain associated with the GameKit.GKError value</summary>
	/// <param name="self">The enumeration value</param>
	/// <remarks>
	///   <para>See the <see cref="global::Foundation.NSError" /> for information on how to use the error domains when reporting errors.</para>
	/// </remarks>
	public static $GLOBAL$Foundation.NSString? GetDomain (this $GLOBAL$GameKit.GKError self)
	{
		if (_domain is null)
			_domain = $GLOBAL$ObjCRuntime.Dlfcn.GetStringConstant ($GLOBAL$ObjCRuntime.Libraries.GameKit.Handle, "GKErrorDomain");
		return _domain;
	}
}
