// <auto-generated />

#nullable enable

using Foundation;
using ObjCBindings;
using ObjCRuntime;
using System;

namespace AVFoundation;

/// <summary>
/// Extension methods for the <see cref="AVCaptureSystemPressureLevelExtensions" /> enumeration.
/// </summary>
[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
public static partial class AVCaptureSystemPressureLevelExtensions
{

	static IntPtr[] values = new IntPtr [5];

	[Field ("AVCaptureSystemPressureLevelNominal", "AVFoundation")]
	internal unsafe static IntPtr AVCaptureSystemPressureLevelNominal
	{
		get
		{
			fixed (IntPtr *storage = &values [0])
				return Dlfcn.CachePointer (Libraries.AVFoundation.Handle, "AVCaptureSystemPressureLevelNominal", storage);
		}
	}

	[Field ("AVCaptureSystemPressureLevelFair", "AVFoundation")]
	internal unsafe static IntPtr AVCaptureSystemPressureLevelFair
	{
		get
		{
			fixed (IntPtr *storage = &values [1])
				return Dlfcn.CachePointer (Libraries.AVFoundation.Handle, "AVCaptureSystemPressureLevelFair", storage);
		}
	}

	[Field ("AVCaptureSystemPressureLevelSerious", "AVFoundation")]
	internal unsafe static IntPtr AVCaptureSystemPressureLevelSerious
	{
		get
		{
			fixed (IntPtr *storage = &values [2])
				return Dlfcn.CachePointer (Libraries.AVFoundation.Handle, "AVCaptureSystemPressureLevelSerious", storage);
		}
	}

	[Field ("AVCaptureSystemPressureLevelCritical", "AVFoundation")]
	internal unsafe static IntPtr AVCaptureSystemPressureLevelCritical
	{
		get
		{
			fixed (IntPtr *storage = &values [3])
				return Dlfcn.CachePointer (Libraries.AVFoundation.Handle, "AVCaptureSystemPressureLevelCritical", storage);
		}
	}

	[Field ("AVCaptureSystemPressureLevelShutdown", "AVFoundation")]
	internal unsafe static IntPtr AVCaptureSystemPressureLevelShutdown
	{
		get
		{
			fixed (IntPtr *storage = &values [4])
				return Dlfcn.CachePointer (Libraries.AVFoundation.Handle, "AVCaptureSystemPressureLevelShutdown", storage);
		}
	}

	/// <summary>
	/// Retrieves the <see cref="global::Foundation.NSString" /> constant that describes <paramref name="self" />.
	/// </summary>
	/// <param name="self">The instance on which this method operates.</param>
	public static NSString? GetConstant (this AVCaptureSystemPressureLevel self)
	{
		IntPtr ptr = IntPtr.Zero;
		switch ((int) self)
		{
			case 0: // AVCaptureSystemPressureLevelNominal
				ptr = AVCaptureSystemPressureLevelNominal;
				break;
			case 1: // AVCaptureSystemPressureLevelFair
				ptr = AVCaptureSystemPressureLevelFair;
				break;
			case 2: // AVCaptureSystemPressureLevelSerious
				ptr = AVCaptureSystemPressureLevelSerious;
				break;
			case 3: // AVCaptureSystemPressureLevelCritical
				ptr = AVCaptureSystemPressureLevelCritical;
				break;
			case 4: // AVCaptureSystemPressureLevelShutdown
				ptr = AVCaptureSystemPressureLevelShutdown;
				break;
		}
		return (NSString?) Runtime.GetNSObject (ptr);
	}

	/// <summary>
	/// Retrieves the <see cref="AVCaptureSystemPressureLevelExtensions" /> value named by <paramref name="constant" />.
	/// </summary>
	/// <param name="constant">The name of the constant to retrieve.</param>
	public static AVCaptureSystemPressureLevel GetValue (NSString constant)
	{
		if (constant is null)
			throw new ArgumentNullException (nameof (constant));
		if (constant.IsEqualTo (AVCaptureSystemPressureLevelNominal))
			return AVCaptureSystemPressureLevel.Nominal;
		if (constant.IsEqualTo (AVCaptureSystemPressureLevelFair))
			return AVCaptureSystemPressureLevel.Fair;
		if (constant.IsEqualTo (AVCaptureSystemPressureLevelSerious))
			return AVCaptureSystemPressureLevel.Serious;
		if (constant.IsEqualTo (AVCaptureSystemPressureLevelCritical))
			return AVCaptureSystemPressureLevel.Critical;
		if (constant.IsEqualTo (AVCaptureSystemPressureLevelShutdown))
			return AVCaptureSystemPressureLevel.Shutdown;
		throw new NotSupportedException ($"The constant {constant} has no associated enum value on this platform.");
	}

	/// <summary>
	/// Retrieves the <see cref="AVCaptureSystemPressureLevelExtensions" /> value represented by the backing field value in <paramref name="handle" />.
	/// </summary>
	/// <param name="handle">The native handle with the name of the constant to retrieve.</param>
	public static AVCaptureSystemPressureLevel GetValue (NativeHandle handle)
	{
		using var str = Runtime.GetNSObject<NSString> (handle)!;
		return GetValue (str);
	}

	/// <summary>
	/// Retrieves the <see cref="AVCaptureSystemPressureLevelExtensions" /> value represented by the backing field value in <paramref name="handle" />.
	/// </summary>
	/// <param name="handle">The native handle with the name of the constant to retrieve.</param>
	public static AVCaptureSystemPressureLevel? GetNullableValue (NativeHandle handle)
	{
		using var str = Runtime.GetNSObject<NSString> (handle);
		if (str is null)
			return null;
		return GetValue (str);
	}

	/// <summary>
	/// Converts an array of <see cref="AVCaptureSystemPressureLevelExtensions" /> enum values into an array of their corresponding constants.
	/// </summary>
	/// <param name="values">The array of enum values to convert.</param>
	internal static NSString?[]? ToConstantArray (this AVCaptureSystemPressureLevel[]? values)
	{
		if (values is null)
			return null;
		var rv = new global::System.Collections.Generic.List<NSString?> ();
		for (var i = 0; i < values.Length; i++) {
			var value = values [i];
			rv.Add (value.GetConstant ());
		}
		return rv.ToArray ();
	}

	/// <summary>
	/// Converts an array of <see cref="NSString" /> values into an array of their corresponding enum values.
	/// </summary>
	/// <param name="values">The array if <see cref="NSString" /> values to convert.</param>
	internal static AVCaptureSystemPressureLevel[]? ToEnumArray (this NSString[]? values)
	{
		if (values is null)
			return null;
		var rv = new global::System.Collections.Generic.List<AVCaptureSystemPressureLevel> ();
		for (var i = 0; i < values.Length; i++) {
			var value = values [i];
			rv.Add (GetValue (value));
		}
		return rv.ToArray ();
	}
}
