// <auto-generated />

#nullable enable

using Foundation;
using ObjCBindings;
using ObjCRuntime;
using System;

namespace GameKit;

[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
public static partial class GKErrorExtensions
{

	[Field ("GKErrorDomain", "GameKit")]
	static Foundation.NSString? _domain;

	public static NSString? GetDomain (this GKError self)
	{
		if (_domain is null)
			_domain = Dlfcn.GetStringConstant (Libraries.GameKit.Handle, "GKErrorDomain");
		return _domain;
	}
}
