// <auto-generated />

#nullable enable

using Foundation;
using ObjCBindings;
using ObjCRuntime;
using System;

namespace GameKit;

[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
public static partial class GKCustomErrorExtensions
{

	[Field ("GKErrorDomain", "/path/to/customlibrary.framework")]
	static Foundation.NSString? _domain;

	public static NSString? GetDomain (this GKCustomError self)
	{
		if (_domain is null)
			_domain = Dlfcn.GetStringConstant (Libraries.customlibrary.Handle, "GKErrorDomain");
		return _domain;
	}
}
