// <auto-generated />

#nullable enable

using Foundation;
using ObjCBindings;
using ObjCRuntime;
using System;

namespace GameKit;

public partial class OuterClass
{
	public partial class InnerClass
	{
		[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
		public static partial class NestedGKErrorExtensions
		{

			[Field ("GKErrorDomain", "GameKit")]
			static global::Foundation.NSString? _domain;

			/// <summary>Returns the error domain associated with the GameKit.OuterClass.InnerClass.NestedGKError value</summary>
			/// <param name="self">The enumeration value</param>
			/// <remarks>
			///   <para>See the <see cref="global::Foundation.NSError" /> for information on how to use the error domains when reporting errors.</para>
			/// </remarks>
			public static global::Foundation.NSString? GetDomain (this global::GameKit.NestedGKError self)
			{
				if (_domain is null)
					_domain = global::ObjCRuntime.Dlfcn.GetStringConstant (global::ObjCRuntime.Libraries.GameKit.Handle, "GKErrorDomain");
				return _domain;
			}
		}
	}
}
