#!/bin/groovy

timestamps {
	node('felix-sierra') {
        stage('checkout') {
            options {
                options { checkoutToSubdirectory('xamarin-macios')
            }
            checkout scm

            sh('env')
            sh('pwd')
            sh('ls -la')
            sh('./jenkins/build-package.sh')
        }
    }
}
