TOP=../../..

include $(TOP)/Make.config

ifneq ($(DOTNET_PLATFORMS),)
SUBDIRS = \
	FrameworksInRuntimesNativeDirectory \
	DynamicLibrariesInRuntimesNativeDirectory \
	XCFrameworkWithStaticLibraryInRuntimesNativeDirectory \
	XCFrameworkWithSymlinks \

endif
