TOP=../../..
SUBDIRS = \
	FrameworksInRuntimesNativeDirectory \
	DynamicLibrariesInRuntimesNativeDirectory \
	XCFrameworkWithStaticLibraryInRuntimesNativeDirectory \
	XCFrameworkWithSymlinks \

include $(TOP)/Make.config
