using System.Collections.Generic;
namespace Cecil.Tests {
	public partial class HandleSafetyTest {
		static HashSet<string> knownFailuresHandleSafety = new HashSet<string> {
			"AddressBook.ABMultiValue`1/<>c.<.ctor>b__2_1`0 (T)",
			"AddressBook.ABMultiValueEntry`1.get_Identifier ()",
			"AddressBook.ABMultiValueEntry`1.get_Label ()",
			"AddressBook.ABMultiValueEntry`1.get_Value`0 ()",
			"AddressBook.ABMultiValueEntry`1.set_Label (Foundation.NSString)",
			"AddressBook.ABMultiValueEntry`1.set_Value`0 (T)",
			"AddressBook.ABPerson/<>c__95`1.<CreateDictionaryMultiValue>b__95_1`0 (T)",
			"AppKit.NSStringAttributes.Get (Foundation.NSString)",
			"AudioToolbox.MusicTrack.Dispose (System.Boolean)",
			"AudioUnit.AudioUnit.SetClassInfo (AudioUnit.ClassInfoDictionary, AudioUnit.AudioUnitScopeType, System.UInt32)",
			"AudioUnit.AUScheduledAudioFileRegion.GetAudioFileRegion ()",
			"AudioUnit.SamplerInstrumentData.ToStruct ()",
			"AVFoundation.AVCaptureReactionType_Extensions.GetSystemImage (AVFoundation.AVCaptureReactionType)",
			"CoreAnimation.CAGradientLayer.set_Colors (CoreGraphics.CGColor[])",
			"CoreFoundation.CFArray.Create (ObjCRuntime.INativeObject[])",
			"CoreFoundation.CFDataBuffer.get_Handle ()",
			"CoreFoundation.CFDictionary.FromObjectsAndKeys (ObjCRuntime.INativeObject[], ObjCRuntime.INativeObject[])",
			"CoreFoundation.CFMessagePort.CopyDescriptionProxy (System.IntPtr)",
			"CoreFoundation.CFMessagePort.MessagePortCallback (System.IntPtr, System.Int32, System.IntPtr, System.IntPtr)",
			"CoreFoundation.CFMessagePort.RetainProxy (System.IntPtr)",
			"CoreFoundation.CFMutableString.Transform (CoreFoundation.CFRange&, CoreFoundation.CFStringTransform, System.Boolean)",
			"CoreFoundation.CFMutableString.Transform (CoreFoundation.CFStringTransform, System.Boolean)",
			"CoreFoundation.CFNotificationCenter.AddObserver (System.String, ObjCRuntime.INativeObject, System.Action`2<System.String, Foundation.NSDictionary>, CoreFoundation.CFNotificationSuspensionBehavior)",
			"CoreFoundation.CFPreferences.SetAppValue (System.String, System.Object, Foundation.NSString)",
			"CoreFoundation.CFProxy.get_ProxyType ()",
			"CoreFoundation.CFSocketSignature..ctor (System.Net.Sockets.AddressFamily, System.Net.Sockets.SocketType, System.Net.Sockets.ProtocolType, CoreFoundation.CFSocketAddress)",
			"CoreGraphics.CGBitmapParameters.set_ColorSpace (CoreGraphics.CGColorSpace)",
			"CoreGraphics.CGColor.Create (CoreGraphics.CGConstantColor)",
			"CoreGraphics.CGColorSpace.CreateAcesCGLinear ()",
			"CoreGraphics.CGColorSpace.CreateAdobeRgb1988 ()",
			"CoreGraphics.CGColorSpace.CreateGenericCmyk ()",
			"CoreGraphics.CGColorSpace.CreateGenericGray ()",
			"CoreGraphics.CGColorSpace.CreateGenericGrayGamma2_2 ()",
			"CoreGraphics.CGColorSpace.CreateGenericRgb ()",
			"CoreGraphics.CGColorSpace.CreateGenericRgbLinear ()",
			"CoreGraphics.CGColorSpace.CreateGenericXyz ()",
			"CoreGraphics.CGColorSpace.CreateItuR_2020 ()",
			"CoreGraphics.CGColorSpace.CreateItuR_709 ()",
			"CoreGraphics.CGColorSpace.CreateRommRgb ()",
			"CoreGraphics.CGColorSpace.CreateSrgb ()",
			"CoreGraphics.CGPDFDocument.SetOutline (CoreGraphics.CGPDFOutlineOptions)",
			"CoreImage.CIAutoAdjustmentFilterOptions.ToDictionary ()",
			"CoreImage.CIImage.FromCGImage (CoreGraphics.CGImage, CoreGraphics.CGColorSpace)",
			"CoreImage.CISamplerOptions.ToDictionary ()",
			"CoreMedia.CMBlockBuffer.AppendMemoryBlock (System.IntPtr, System.UIntPtr, CoreMedia.CMCustomBlockAllocator, System.UIntPtr, System.UIntPtr, CoreMedia.CMBlockBufferFlags)",
			"CoreMedia.CMBlockBuffer.FromMemoryBlock (System.IntPtr, System.UIntPtr, CoreMedia.CMCustomBlockAllocator, System.UIntPtr, System.UIntPtr, CoreMedia.CMBlockBufferFlags, CoreMedia.CMBlockBufferError&)",
			"CoreMidi.MidiCIDeviceInfo..ctor (CoreMidi.MidiEndpoint, Foundation.NSData, Foundation.NSData, Foundation.NSData, Foundation.NSData)",
			"CoreMidi.MidiDevice.Add (System.String, System.Boolean, System.UIntPtr, System.UIntPtr, CoreMidi.MidiEntity)",
			"CoreMidi.MidiDeviceList.Add (CoreMidi.MidiDevice)",
			"CoreServices.FSEventStream..ctor (CoreServices.FSEventStreamCreateOptions)",
			"CoreServices.FSEventStream.EventsCallback (System.IntPtr, System.IntPtr, System.IntPtr, System.IntPtr, System.IntPtr, System.IntPtr)",
			"CoreText.Adapter.GetHandles`1 (System.Collections.Generic.IEnumerable`1<T>)",
			"CoreText.CTBaselineClassID.FromHandle (System.IntPtr)",
			"CoreText.CTFontCollection..ctor (CoreText.CTFontCollectionOptions)",
			"CoreText.CTFontCollection.GetMatchingFontDescriptors (CoreText.CTFontCollectionOptions)",
			"CoreText.CTFontCollectionOptionsExtensions.GetHandle (CoreText.CTFontCollectionOptions)",
			"CoreText.CTFontDescriptor.Create (CoreText.CTFontDescriptorAttributes)",
			"CoreText.CTFontFeatures.get_Exclusive ()",
			"CoreText.CTFontFeatures.set_Exclusive (System.Boolean)",
			"CoreText.CTFontFeatureSelectors.get_Default ()",
			"CoreText.CTFontFeatureSelectors.get_Setting ()",
			"CoreText.CTFontFeatureSelectors.set_Default (System.Boolean)",
			"CoreText.CTFontFeatureSelectors.set_Setting (System.Boolean)",
			"CoreText.CTFrameAttributesExtensions.GetHandle (CoreText.CTFrameAttributes)",
			"CoreText.CTFramesetter.SuggestFrameSize (Foundation.NSRange, CoreText.CTFrameAttributes, CoreGraphics.CGSize, Foundation.NSRange&)",
			"CoreText.CTParagraphStyleSettings.CreateValue (CoreText.CTParagraphStyleSpecifier, System.Collections.Generic.IEnumerable`1<CoreText.CTTextTab>)",
			"CoreText.CTParagraphStyleSpecifierIntPtrsValue.WriteValue (CoreText.CTParagraphStyleSettingValue[], System.Int32)",
			"CoreText.CTStringAttributes.get_AdaptiveImageProvider ()",
			"CoreText.CTStringAttributes.get_BackgroundColor ()",
			"CoreText.CTStringAttributes.get_BaselineClass ()",
			"CoreText.CTStringAttributes.get_Font ()",
			"CoreText.CTStringAttributes.get_ForegroundColor ()",
			"CoreText.CTStringAttributes.get_ForegroundColorFromContext ()",
			"CoreText.CTStringAttributes.get_GlyphInfo ()",
			"CoreText.CTStringAttributes.get_ParagraphStyle ()",
			"CoreText.CTStringAttributes.get_RunDelegate ()",
			"CoreText.CTStringAttributes.get_StrokeColor ()",
			"CoreText.CTStringAttributes.get_UnderlineColor ()",
			"CoreText.CTStringAttributes.get_VerticalForms ()",
			"CoreText.CTStringAttributes.set_ForegroundColorFromContext (System.Boolean)",
			"CoreText.CTStringAttributes.set_VerticalForms (System.Boolean)",
			"CoreText.CTStringAttributes.SetBaseline (CoreText.CTBaselineClass, System.Double, Foundation.NSString)",
			"CoreText.CTStringAttributes.SetWritingDirection (CoreText.CTWritingDirection[])",
			"CoreText.CTTextTab..ctor (CoreText.CTTextAlignment, System.Double, CoreText.CTTextTabOptions)",
			"CoreText.CTTextTabOptionsExtensions.GetHandle (CoreText.CTTextTabOptions)",
			"CoreText.CTTypesetter..ctor (Foundation.NSAttributedString, CoreText.CTTypesetterOptions)",
			"CoreText.CTTypesetterOptions.get_AllowUnboundedLayout ()",
			"CoreText.CTTypesetterOptions.get_DisableBidiProcessing ()",
			"CoreText.CTTypesetterOptions.set_AllowUnboundedLayout (System.Boolean)",
			"CoreText.CTTypesetterOptions.set_DisableBidiProcessing (System.Boolean)",
			"CoreText.CTTypesetterOptionsExtensions.GetHandle (CoreText.CTTypesetterOptions)",
			"CoreVideo.CVImageBuffer.GetCodePoint (CoreVideo.CVImageBufferColorPrimaries)",
			"CoreVideo.CVImageBuffer.GetCodePoint (CoreVideo.CVImageBufferTransferFunction)",
			"CoreVideo.CVImageBuffer.GetCodePoint (CoreVideo.CVImageBufferYCbCrMatrix)",
			"CoreVideo.CVPixelBuffer.Create (System.IntPtr, System.IntPtr, CoreVideo.CVPixelFormatType, System.Byte[], System.IntPtr, CoreVideo.CVPixelBufferAttributes, CoreVideo.CVReturn&)",
			"CoreVideo.CVPixelBuffer.Create (System.IntPtr, System.IntPtr, CoreVideo.CVPixelFormatType, System.Byte[][], System.IntPtr[], System.IntPtr[], System.IntPtr[], CoreVideo.CVPixelBufferAttributes, CoreVideo.CVReturn&)",
			"CoreVideo.CVPixelBufferPool.CreatePixelBuffer (CoreVideo.CVPixelBufferPoolAllocationSettings, CoreVideo.CVReturn&)",
			"Darwin.SystemLog/<Search>d__29.MoveNext ()",
			"Foundation.DictionaryContainer.SetArrayValue`1 (Foundation.NSString, T[], System.Func`2<T, ObjCRuntime.NativeHandle>)",
			"Foundation.DictionaryContainer.SetBooleanValue (Foundation.NSString, System.Nullable`1<System.Boolean>)",
			"Foundation.DictionaryContainer.SetNativeValue (Foundation.NSString, ObjCRuntime.INativeObject, System.Boolean)",
			"Foundation.DictionaryContainer.TryGetNativeValue (ObjCRuntime.NativeHandle, ObjCRuntime.NativeHandle&)",
			"Foundation.DictionaryContainerHelper.GetHandle (Foundation.DictionaryContainer)",
			"Foundation.NSArray.FromNativeObjectsImpl`1 (T[], System.IntPtr, System.Boolean)",
			"Foundation.NSArray.FromNSObjects (System.Collections.Generic.IList`1<Foundation.NSObject>)",
			"Foundation.NSArray.FromStrings (System.Collections.Generic.IReadOnlyList`1<System.String>)",
			"Foundation.NSArray.UnsafeGetItem (ObjCRuntime.NativeHandle, System.UIntPtr, System.Type)",
			"Foundation.NSArray.UnsafeGetItem`1 (ObjCRuntime.NativeHandle, System.UIntPtr)",
			"Foundation.NSArray`1.FromNSObjects`0 (System.Int32, TKey[])",
			"Foundation.NSDecimal.ToString ()",
			"Foundation.NSFastEnumerator`1.Fetch ()",
			"ImageIO.CGImageDestination.AddAuxiliaryDataInfo (ImageIO.CGImageAuxiliaryDataType, ImageIO.CGImageAuxiliaryDataInfo)",
			"ImageIO.CGImageDestinationOptions.set_DestinationBackgroundColor (CoreGraphics.CGColor)",
			"ImageIO.CGImageSource.CopyAuxiliaryDataInfo (System.UIntPtr, ImageIO.CGImageAuxiliaryDataType)",
			"NaturalLanguage.NLStrongDictionary.get_Item (Foundation.NSString)",
			"NaturalLanguage.NLVectorDictionary.get_Item (Foundation.NSString)",
			"NearbyInteraction.NIAlgorithmConvergenceStatusReasonValues.GetConvergenceStatusReason (NearbyInteraction.NIAlgorithmConvergenceStatusReason)",
			"ObjCRuntime.BackingField.Save`1 (T&, T)",
			"ObjCRuntime.BindAs.ConvertManagedArrayToNSArray2`2 (T[], method U *(T), method System.IntPtr *(U))",
			"ObjCRuntime.BindAs.xamarin_bool_to_nsnumber (System.Boolean)",
			"ObjCRuntime.BindAs.xamarin_byte_to_nsnumber (System.Byte)",
			"ObjCRuntime.BindAs.xamarin_double_to_nsnumber (System.Double)",
			"ObjCRuntime.BindAs.xamarin_float_to_nsnumber (System.Single)",
			"ObjCRuntime.BindAs.xamarin_int_to_nsnumber (System.Int32)",
			"ObjCRuntime.BindAs.xamarin_long_to_nsnumber (System.Int64)",
			"ObjCRuntime.BindAs.xamarin_nfloat_to_nsnumber (System.Runtime.InteropServices.NFloat)",
			"ObjCRuntime.BindAs.xamarin_nint_to_nsnumber (System.IntPtr)",
			"ObjCRuntime.BindAs.xamarin_nuint_to_nsnumber (System.UIntPtr)",
			"ObjCRuntime.BindAs.xamarin_nullable_bool_to_nsnumber (System.Nullable`1<System.Boolean>)",
			"ObjCRuntime.BindAs.xamarin_nullable_byte_to_nsnumber (System.Nullable`1<System.Byte>)",
			"ObjCRuntime.BindAs.xamarin_nullable_double_to_nsnumber (System.Nullable`1<System.Double>)",
			"ObjCRuntime.BindAs.xamarin_nullable_float_to_nsnumber (System.Nullable`1<System.Single>)",
			"ObjCRuntime.BindAs.xamarin_nullable_int_to_nsnumber (System.Nullable`1<System.Int32>)",
			"ObjCRuntime.BindAs.xamarin_nullable_long_to_nsnumber (System.Nullable`1<System.Int64>)",
			"ObjCRuntime.BindAs.xamarin_nullable_nfloat_to_nsnumber (System.Nullable`1<System.Runtime.InteropServices.NFloat>)",
			"ObjCRuntime.BindAs.xamarin_nullable_nint_to_nsnumber (System.Nullable`1<System.IntPtr>)",
			"ObjCRuntime.BindAs.xamarin_nullable_nuint_to_nsnumber (System.Nullable`1<System.UIntPtr>)",
			"ObjCRuntime.BindAs.xamarin_nullable_sbyte_to_nsnumber (System.Nullable`1<System.SByte>)",
			"ObjCRuntime.BindAs.xamarin_nullable_short_to_nsnumber (System.Nullable`1<System.Int16>)",
			"ObjCRuntime.BindAs.xamarin_nullable_uint_to_nsnumber (System.Nullable`1<System.UInt32>)",
			"ObjCRuntime.BindAs.xamarin_nullable_ulong_to_nsnumber (System.Nullable`1<System.UInt64>)",
			"ObjCRuntime.BindAs.xamarin_nullable_ushort_to_nsnumber (System.Nullable`1<System.UInt16>)",
			"ObjCRuntime.BindAs.xamarin_sbyte_to_nsnumber (System.SByte)",
			"ObjCRuntime.BindAs.xamarin_short_to_nsnumber (System.Int16)",
			"ObjCRuntime.BindAs.xamarin_uint_to_nsnumber (System.UInt32)",
			"ObjCRuntime.BindAs.xamarin_ulong_to_nsnumber (System.UInt64)",
			"ObjCRuntime.BindAs.xamarin_ushort_to_nsnumber (System.UInt16)",
			"ObjCRuntime.NativeObjectExtensions.GetHandle (ObjCRuntime.INativeObject)",
			"ObjCRuntime.NativeObjectExtensions.GetNonNullHandle (ObjCRuntime.INativeObject, System.String)",
			"ObjCRuntime.RegistrarHelper.INativeObject_managed_to_native (System.IntPtr, ObjCRuntime.INativeObject, ObjCRuntime.INativeObject, System.Boolean)",
			"ObjCRuntime.Runtime.ConvertSmartEnumToNSString (System.IntPtr)",
			"ObjCRuntime.Runtime.GetHandleForINativeObject (System.IntPtr)",
			"ObjCRuntime.Runtime.RetainAndAutoreleaseHandle (ObjCRuntime.INativeObject)",
			"ObjCRuntime.Runtime.RetainAndAutoreleaseNativeObject (ObjCRuntime.INativeObject)",
			"ObjCRuntime.Runtime.RetainAndAutoreleaseNSObject (Foundation.NSObject)",
			"ObjCRuntime.Runtime.RetainNativeObject (ObjCRuntime.INativeObject)",
			"ObjCRuntime.Runtime.RetainNSObject (Foundation.NSObject)",
			"ObjCRuntime.Runtime.UnwrapNSException (System.IntPtr)",
			"QuickLook.QLThumbnailImage.Create (Foundation.NSUrl, CoreGraphics.CGSize, System.Single, System.Boolean)",
			"ReplayKit.RPBroadcastConfiguration.set_VideoCompressionProperties (AVFoundation.AVVideoCodecSettings)",
			"SceneKit.SCNSkinner.ToNSArray (SceneKit.SCNMatrix4[])",
			"Security.SecIdentity.Import (System.Byte[], System.String)",
			"Security.SecKey.Create (Foundation.NSData, Security.SecKeyType, Security.SecKeyClass, System.Int32, Foundation.NSDictionary, Foundation.NSError&)",
			"Security.SecKey.CreateDecryptedData (Security.SecKeyAlgorithm, Foundation.NSData, Foundation.NSError&)",
			"Security.SecKey.CreateEncryptedData (Security.SecKeyAlgorithm, Foundation.NSData, Foundation.NSError&)",
			"Security.SecKey.CreateRandomKey (Security.SecKeyType, System.Int32, Foundation.NSDictionary, Foundation.NSError&)",
			"Security.SecKey.CreateSignature (Security.SecKeyAlgorithm, Foundation.NSData, Foundation.NSError&)",
			"Security.SecKey.GenerateKeyPair (Security.SecKeyType, System.Int32, Security.SecPublicPrivateKeyAttrs, Security.SecKey&, Security.SecKey&)",
			"Security.SecKey.GenerateKeyPair (Security.SecKeyType, System.Int32, Security.SecPublicPrivateKeyAttrs, Security.SecPublicPrivateKeyAttrs, Security.SecKey&, Security.SecKey&)",
			"Security.SecKey.GetKeyExchangeResult (Security.SecKeyAlgorithm, Security.SecKey, Foundation.NSDictionary, Foundation.NSError&)",
			"Security.SecKey.IsAlgorithmSupported (Security.SecKeyOperationType, Security.SecKeyAlgorithm)",
			"Security.SecKey.VerifySignature (Security.SecKeyAlgorithm, Foundation.NSData, Foundation.NSData, Foundation.NSError&)",
			"Security.SecKeyChain.Add (Security.SecRecord)",
			"Security.SecKeyChain.Remove (Security.SecRecord)",
			"Security.SecKeyChain.Update (Security.SecRecord, Security.SecRecord)",
			"Security.SecRecord.get_ApplicationTag ()",
			"Security.SecRecord.get_CanDecrypt ()",
			"Security.SecRecord.get_CanDerive ()",
			"Security.SecRecord.get_CanEncrypt ()",
			"Security.SecRecord.get_CanSign ()",
			"Security.SecRecord.get_CanUnwrap ()",
			"Security.SecRecord.get_CanVerify ()",
			"Security.SecRecord.get_CanWrap ()",
			"Security.SecRecord.get_EffectiveKeySize ()",
			"Security.SecRecord.get_IsPermanent ()",
			"Security.SecRecord.get_KeySizeInBits ()",
			"Security.SecRecord.get_KeyType ()",
			"Security.SecRecord.get_Label ()",
			"Security.SecRecord.get_TokenID ()",
			"Security.SecRecord.set_AccessControl (Security.SecAccessControl)",
			"Security.SecRecord.set_ApplicationTag (Foundation.NSData)",
			"Security.SecRecord.set_CanDecrypt (System.Boolean)",
			"Security.SecRecord.set_CanDerive (System.Boolean)",
			"Security.SecRecord.set_CanEncrypt (System.Boolean)",
			"Security.SecRecord.set_CanSign (System.Boolean)",
			"Security.SecRecord.set_CanUnwrap (System.Boolean)",
			"Security.SecRecord.set_CanVerify (System.Boolean)",
			"Security.SecRecord.set_CanWrap (System.Boolean)",
			"Security.SecRecord.set_EffectiveKeySize (System.Int32)",
			"Security.SecRecord.set_IsPermanent (System.Boolean)",
			"Security.SecRecord.set_KeySizeInBits (System.Int32)",
			"Security.SecRecord.set_KeyType (Security.SecKeyType)",
			"Security.SecRecord.set_Label (System.String)",
			"Security.SecRecord.set_TokenID (Security.SecTokenID)",
			"Security.SslContext.Bundle (Security.SecIdentity, System.Collections.Generic.IEnumerable`1<Security.SecCertificate>)",
			"System.Boolean ObjCRuntime.DisposableObject.op_Equality (ObjCRuntime.DisposableObject, ObjCRuntime.DisposableObject)",
			"System.Boolean ObjCRuntime.DisposableObject.op_Inequality (ObjCRuntime.DisposableObject, ObjCRuntime.DisposableObject)",
			"System.Boolean ObjCRuntime.NativeHandle.op_Equality (System.IntPtr, ObjCRuntime.NativeHandle)",
			"System.Boolean ObjCRuntime.NativeHandle.op_Inequality (ObjCRuntime.NativeHandle, ObjCRuntime.NativeHandle)",
			"System.Boolean ObjCRuntime.NativeHandle.op_Inequality (System.IntPtr, ObjCRuntime.NativeHandle)",
			"System.Boolean UIKit.UIAppearance.op_Equality (UIKit.UIAppearance, UIKit.UIAppearance)",
			"System.Boolean UIKit.UIFont.op_Equality (UIKit.UIFont, UIKit.UIFont)",
			"System.IntPtr ObjCRuntime.NativeHandle.op_Implicit (ObjCRuntime.NativeHandle)",
			"UIKit.UIAlertView..ctor (System.String, System.String, UIKit.IUIAlertViewDelegate, System.String, System.String[])",
			"UIKit.UIAppearance.Equals (System.Object)",
			"UIKit.UIContentSizeCategoryExtensions.Compare (UIKit.UIContentSizeCategory, UIKit.UIContentSizeCategory)",
			"UIKit.UIDragDropSessionExtensions/<>c__DisplayClass0_0`1.<LoadObjects>b__0 (Foundation.INSItemProviderReading[])",
			"UIKit.UIFontFeature.ObjCRuntime.INativeObject.get_Handle ()",
			"UIKit.UIPasteboard.set_Images (UIKit.UIImage[])",
			"UIKit.UIToolbar.SetItems (UIKit.UIBarButtonItem[], System.Boolean)",
			"VideoToolbox.VTCompressionSession.SetCompressionProperties (VideoToolbox.VTCompressionProperties)",
			"VideoToolbox.VTDecompressionSession.SetDecompressionProperties (VideoToolbox.VTDecompressionProperties)",
			"VideoToolbox.VTPixelRotationSession.SetRotationProperties (VideoToolbox.VTPixelRotationProperties)",
			"VideoToolbox.VTPixelTransferSession.SetTransferProperties (VideoToolbox.VTPixelTransferProperties)",
		};
	}
}
