parameters:
- name: buildStage
  type: string

- name: dependsOn
  type: object
  default: null

- name: isPR
  type: boolean

- name: repositoryAlias
  type: string
  default: self

- name: commit
  type: string
  default: HEAD

- name: pushNugets
  type: boolean
  default: true

- name: pushNugetsToMaestro
  type: boolean
  default: true

- name: stageDisplayNamePrefix
  type: string
  default: ''

- name: uploadPrefix
  type: string
  default: '$(MaciosUploadPrefix)'

stages:
- stage: prepare_release
  displayName: '${{ parameters.stageDisplayNamePrefix }}Prepare .NET Release'
  ${{ if parameters.dependsOn }}:
    dependsOn: ${{ parameters.dependsOn }}
    condition: and(
        or(
          eq(dependencies.${{ parameters.buildStage }}.result, 'Succeeded'),
          eq(dependencies.${{ parameters.buildStage }}.result, 'SucceededWithIssues')
        ),
        eq(${{ parameters.isPR }}, false)
      )
  ${{ else }}:
    condition: eq(${{ parameters.isPR }}, false)

  jobs:
  # Check - "xamarin-macios (Prepare Release Sign NuGets)"
  - template: sign-artifacts/jobs/v2.yml@yaml-templates
    parameters:
      use1ESTemplate: true
      uploadBinlogs: true
      uploadPrefix: ${{ parameters.uploadPrefix }}
      enabledCredScan: false
      checkoutType: ${{ parameters.repositoryAlias }}
      signedArtifactName: '${{ parameters.uploadPrefix }}nuget-signed'
      artifactName: '${{ parameters.uploadPrefix }}not-signed-package'
      signType: Real
      usePipelineArtifactTasks: true
      setupSteps:
      - template: tools/devops/automation/templates/common/checkout.yml@${{ parameters.repositoryAlias }}
        parameters:
          isPR: ${{ parameters.isPR }}
          repositoryAlias: ${{ parameters.repositoryAlias }}
          commit: ${{ parameters.commit }}

      - pwsh: |
            Write-Host "##vso[task.setvariable variable=DYLD_INSERT_LIBRARIES]"
        displayName: 'Disable CodeQL'
        name: disableCodeQLOnArm64

  # Check - "xamarin-macios (Prepare Release Convert NuGet to MSI)"
  - template: nuget-msi-convert/job/v4.yml@yaml-templates
    parameters:
      use1ESTemplate: true
      yamlResourceName: yaml-templates
      dependsOn: signing
      artifactName: '${{ parameters.uploadPrefix }}nuget-signed'
      propsArtifactName: ${{ parameters.uploadPrefix }}not-signed-package
      binlogsArtifactName: ${{ parameters.uploadPrefix }}nuget-msi-convert-binlogs
      signType: Real
      preConvertSteps:
      - pwsh: |
          New-Item "$(System.DefaultWorkingDirectory)/xamarin-macios/tools/devops/governance" -ItemType Directory -ea 0
          New-Item -Path "$(System.DefaultWorkingDirectory)/xamarin-macios/tools/devops/governance" -Name "CredScanSuppressions.json" -Value '{"tool":"Crendential Scanner", "supressions":[]}'
        displayName: Create credscan dummy ignore file

      postConvertSteps:
      - task: DownloadPipelineArtifact@2
        inputs:
          artifactName: '${{ parameters.uploadPrefix }}not-signed-package'
          downloadPath: $(Build.StagingDirectory)\sign-verify
          patterns: |
            **/SignVerifyIgnore.txt

      - task: MicroBuildCodesignVerify@3
        displayName: verify signed msi content
        inputs:
          TargetFolders: |
            $(Build.ArtifactStagingDirectory)\bin\manifests
            $(Build.ArtifactStagingDirectory)\bin\manifests-packs
            $(Build.ArtifactStagingDirectory)\bin\msi-nupkgs
          ExcludeSNVerify: true
          ApprovalListPathForCerts: $(Build.StagingDirectory)\sign-verify\SignVerifyIgnore.txt

  - ${{ if eq(parameters.pushNugets, true) }}:
    # Check - "xamarin-macios (Prepare Release Push NuGets)"
    - job: push_signed_nugets
      displayName: Push NuGets
      dependsOn: [signing, nuget_convert]
      condition: and(
          or(
            eq(dependencies.signing.result, 'Succeeded'), 
            eq(dependencies.signing.result, 'SucceededWithIssues')
          ),
          or(
            eq(dependencies.nuget_convert.result, 'Succeeded'), 
            eq(dependencies.nuget_convert.result, 'SucceededWithIssues')
          )
        )
      variables:
      - name: skipNugetSecurityAnalysis
        value: true
      - name: INCLUDE_DOTNET_IOS
        value: $[ stageDependencies.configure_build.configure.outputs['configure_platforms.INCLUDE_DOTNET_IOS'] ]
      - name: INCLUDE_DOTNET_MACCATALYST
        value: $[ stageDependencies.configure_build.configure.outputs['configure_platforms.INCLUDE_DOTNET_MACCATALYST'] ]
      - name: INCLUDE_DOTNET_MACOS
        value: $[ stageDependencies.configure_build.configure.outputs['configure_platforms.INCLUDE_DOTNET_MACOS'] ]
      - name: INCLUDE_DOTNET_TVOS
        value: $[ stageDependencies.configure_build.configure.outputs['configure_platforms.INCLUDE_DOTNET_TVOS'] ]
      pool:
        name: AzurePipelines-EO
        demands:
        - ImageOverride -equals 1ESPT-Windows2022
      steps:
      - pwsh: |
          New-Item "$(System.DefaultWorkingDirectory)/xamarin-macios/tools/devops/governance" -ItemType Directory -ea 0
          New-Item -Path "$(System.DefaultWorkingDirectory)/xamarin-macios/tools/devops/governance" -Name "CredScanSuppressions.json" -Value '{"tool":"Crendential Scanner", "supressions":[]}'
        displayName: Create credscan dummy ignore file

      - task: UseDotNet@2
        displayName: Install .NET 9.x
        inputs:
          version: 9.x
          includePreviewVersions: true

      - task: DownloadPipelineArtifact@2
        inputs:
          artifactName: DropMetadata-shipping-nugets
          downloadPath: $(Build.StagingDirectory)\metadata
        displayName: Download nugets drop metadata

      - powershell: |
          $jsonContent = Get-Content -Path "$(Build.StagingDirectory)\metadata\VSTSDrop.json" -Raw | ConvertFrom-Json
          $dropPrefix = $jsonContent.VstsDropBuildArtifact.VstsDropUrl -replace 'https://devdiv.artifacts.visualstudio.com/DefaultCollection/_apis/drop/drops/' -replace '/nugets'
          Write-Host "##vso[task.setvariable variable=ReleaseDropPrefix]$dropPrefix"
        displayName: Set variable ReleaseDropPrefix

      # Download nugets drop created by nuget-msi-convert/job/v4.yml and publish to maestro
      - task: ms-vscs-artifact.build-tasks.artifactDropDownloadTask-1.artifactDropDownloadTask@1
        displayName: Download $(ReleaseDropPrefix)/nugets
        inputs:
          dropServiceURI: https://devdiv.artifacts.visualstudio.com/DefaultCollection
          buildNumber: $(ReleaseDropPrefix)/nugets
          destinationPath: $(Build.StagingDirectory)\nuget-signed

      - script: make -C $(Build.SourcesDirectory)/dotnet setup-publish-bar-manifest
        displayName: make setup-publish-bar-manifest

      - pwsh: |
          gci env: | format-table -autosize -wrap
          Get-ChildItem -Name -Recurse -Path $(Build.StagingDirectory)
          $varMap = [ordered]@{ "INCLUDE_DOTNET_IOS" = "iOS"; "INCLUDE_DOTNET_MACCATALYST" = "MacCatalyst"; "INCLUDE_DOTNET_MACOS" = "macOS"; "INCLUDE_DOTNET_TVOS" = "tvOS" }
          foreach ($varName in $varMap.Keys) {
              if ([Environment]::GetEnvironmentVariable($varName)) {
                  Write-Host "Variable '$varName' was set, setting MaestroProjectPlatformName to '$($varMap[$varName])'"
                  Write-Host "##vso[task.setvariable variable=MaestroProjectPlatformName]$($varMap[$varName])"
                  exit 0;
              }
          }
        displayName: Set maestro project variable

      - task: AzureCLI@2
        displayName: generate and publish BAR manifest
        inputs:
          azureSubscription: "Darc: Maestro Production"
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: >-
            dotnet build $(Build.SourcesDirectory)\dotnet\package\Microsoft.$(MaestroProjectPlatformName).Ref\package.csproj
            -t:PushManifestToBuildAssetRegistry
            -p:NupkgPath=$(Build.StagingDirectory)\nuget-signed
            -p:PrereleaseIdentifier=$(PrereleaseIdentifier)
            -bl:$(Build.StagingDirectory)\maestro-binlogs\generate-bar-manifest.binlog
          workingDirectory: $(Build.SourcesDirectory)\..
        condition: and(succeeded(), eq('${{ parameters.pushNugetsToMaestro }}', 'true'))

      - task: AzureCLI@2
        inputs:
          azureSubscription: "Darc: Maestro Production"
          scriptType: pscore
          scriptLocation: inlineScript
          inlineScript: |
            $versionEndpoint = 'https://maestro.dot.net/api/assets/darc-version?api-version=2019-01-16'
            $darcVersion = $(Invoke-WebRequest -Uri $versionEndpoint -UseBasicParsing).Content
            $arcadeServicesSource = 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json'
            & dotnet tool update microsoft.dotnet.darc --version "$darcVersion" --add-source "$arcadeServicesSource" --tool-path $(Agent.ToolsDirectory)\darc -v n
            & $(Agent.ToolsDirectory)\darc\darc add-build-to-channel --default-channels --id $(BARBuildId) --ci --publishing-infra-version 3 --azdev-pat $(System.AccessToken)
          # We can't use the global.json located in the root of our repo, because makes it required to use the exact .NET version we're referencing in our eng/Versions.Details.xml file.
          # So in order to not use it, we set the working directory to the parent directory of xamarin-macios.
          workingDirectory: $(Build.SourcesDirectory)\..
        displayName: Add builds to default darc channel
        condition: and(succeeded(), eq('${{ parameters.pushNugetsToMaestro }}', 'true'))

      - task: 1ES.PublishPipelineArtifact@1
        displayName: 'Publish Artifact: maestro-binlogs'
        inputs:
          path: $(Build.StagingDirectory)\maestro-binlogs
          artifact: ${{ parameters.uploadPrefix }}maestro-binlogs-$(System.JobAttempt)
        condition: and(succeededOrFailed(), eq('${{ parameters.pushNugetsToMaestro }}', 'true'))
        continueOnError: true
