# Perform gihub cleaning steps

steps:
- checkout: self          # https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema#checkout
  clean: true             # Executes: git clean -ffdx && git reset --hard HEAD
  submodules: false
  persistCredentials: true
  path: s/xamarin-macios


- pwsh: |
    Import-Module $Env:SYSTEM_DEFAULTWORKINGDIRECTORY/tools/devops/automation/scripts/MaciosCI.psd1
    $comments = New-GitHubCommentsObject -Org "xamarin" -Repo "xamarin-macios" -Token $(GitHub.Token)

    $prId = "$(Build.SourceBranch)".Replace("refs/pull/", "").Replace("/merge", "")
    $prComments = $comments.GetCommentsForPR($prId)

    $botComments = [System.Collections.ArrayList]@()
    foreach ($c in $prComments) {
      if ($c.Author -eq "vs-mobiletools-engineering-service2") {
        if ($c.Body.Contains("[PR Build]") -or $c.Body.Contains("[CI Build]")) {
          $botComments.Add($c)
        }
      }
    }
    $comments.MinimizeComments($botComments)
  displayName: Clear past comments
