
# job that downloads the html report from the artifacts and uploads them into vsdrops.
parameters:

- name: testPrefix
  type: string 
  default: 'ios' # default context, since we started dealing with iOS devices. 

# did the provisioning work?
- name: provisioningFailed
  type: string 
  default: 'False'

steps:

- template: checkout.yml

- template: download-artifacts.yml 
  parameters:
    testPrefix: ${{ parameters.testPrefix }}

- task: ms-vscs-artifact.build-tasks.artifactDropTask-1.artifactDropTask@0
  displayName: 'Publish to Artifact Services Drop'
  inputs:
    dropServiceURI: 'https://devdiv.artifacts.visualstudio.com/DefaultCollection'
    dropMetadataContainerName: 'DropMetadata-${{ parameters.testPrefix }}'
    buildNumber: 'xamarin-macios/device-tests/$(Build.BuildNumber)/$(Build.BuildId)/${{ parameters.testPrefix }}'
    sourcePath: $(HTML_REPORT_PATH)
    detailedLog: true
    usePat: true 
