// <auto-generated />

#nullable enable

using AVFoundation;
using Foundation;
using ObjCBindings;
using ObjCRuntime;
using System.Runtime.Versioning;

namespace Microsoft.Macios.Generator.Tests.Protocols.Data;

[SupportedOSPlatform ("macos")]
[SupportedOSPlatform ("ios")]
[SupportedOSPlatform ("tvos")]
[SupportedOSPlatform ("maccatalyst13.1")]
[Protocol (Name = "AVAudioMixing", WrapperType = typeof (AVAudioMixingWrapper))]
[ProtocolMember (IsRequired = true, IsProperty = true, IsStatic = false, Name = "Volume", Selector = "volume", PropertyType = typeof (float), GetterSelector = "volume", SetterSelector = "setVolume:", ArgumentSemantic = ArgumentSemantic.None)]
[ProtocolMember (IsRequired = true, IsProperty = false, IsStatic = false, Name = "DestinationForMixer", Selector = "destinationForMixer:bus:", ReturnType = typeof (global::AVFoundation.AVAudioMixingDestination), ParameterType = new Type [] { typeof (global::AVFoundation.AVAudioNode), typeof (global::System.UIntPtr) }, ParameterByRef = new bool [] { false, false }, ParameterBlockProxy = new Type? [] { null, null })]
public partial interface IAVAudioMixing : INativeObject, IDisposable
{

	[DynamicDependency ("Volume")]
	[DynamicDependency ("DestinationForMixer(AVFoundation.AVAudioNode,System.UIntPtr)")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	static IAVAudioMixing ()
	{
		global::System.GC.KeepAlive (null);
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	internal static float _GetVolume (this IAVAudioMixing self)
	{
		float ret;
		ret = global::ObjCRuntime.Messaging.float_objc_msgSend (self.Handle, global::ObjCRuntime.Selector.GetHandle ("volume"));
		global::System.GC.KeepAlive (self);
		return ret;
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	internal static void _SetVolume (this IAVAudioMixing self, float value)
	{
		global::ObjCRuntime.Messaging.void_objc_msgSend_float (self.Handle, global::ObjCRuntime.Selector.GetHandle ("setVolume:"), value);
		global::System.GC.KeepAlive (self);
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[global::Foundation.RequiredMember]
	public virtual partial float Volume
	{
		[SupportedOSPlatform ("macos")]
		[SupportedOSPlatform ("ios")]
		[SupportedOSPlatform ("tvos")]
		[SupportedOSPlatform ("maccatalyst13.1")]
		get => _GetVolume (this);
		[SupportedOSPlatform ("macos")]
		[SupportedOSPlatform ("ios")]
		[SupportedOSPlatform ("tvos")]
		[SupportedOSPlatform ("maccatalyst13.1")]
		set => _SetVolume (this, value);
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	internal static global::AVFoundation.AVAudioMixingDestination? _DestinationForMixer (this global::Microsoft.Macios.Generator.Tests.Protocols.Data.IAVAudioMixing self, global::AVFoundation.AVAudioNode mixer, global::System.UIntPtr bus)
	{
		var mixer__handle__ = mixer!.GetNonNullHandle (nameof (mixer));
		global::AVFoundation.AVAudioMixingDestination? ret;
		ret = global::ObjCRuntime.Runtime.GetNSObject<global::AVFoundation.AVAudioMixingDestination> (global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend_NativeHandle_UIntPtr (self.Handle, global::ObjCRuntime.Selector.GetHandle ("destinationForMixer:bus:"), mixer__handle__, bus));
		global::System.GC.KeepAlive (self);
		global::System.GC.KeepAlive (mixer);
		return ret;
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[global::Foundation.RequiredMember]
	public virtual partial global::AVFoundation.AVAudioMixingDestination? DestinationForMixer (global::AVFoundation.AVAudioNode mixer, global::System.UIntPtr bus)
	{
		throw new global::Foundation.You_Should_Not_Call_base_In_This_Method ();
	}

}

internal unsafe sealed class AVAudioMixingWrapper : BaseWrapper, IAVAudioMixing
{

	[Preserve (Conditional = true)]
	public AVAudioMixingWrapper (NativeHandle handle, bool owns)
		: base (handle, owns)
	{
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Property> ("obstruction")]
	public float Obstruction
	{
		[SupportedOSPlatform ("macos")]
		[SupportedOSPlatform ("ios")]
		[SupportedOSPlatform ("tvos")]
		[SupportedOSPlatform ("maccatalyst13.1")]
		get
		{
			float ret;
			ret = global::ObjCRuntime.Messaging.float_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("obstruction"));
			global::System.GC.KeepAlive (this);
			return ret;
		}

		[SupportedOSPlatform ("macos")]
		[SupportedOSPlatform ("ios")]
		[SupportedOSPlatform ("tvos")]
		[SupportedOSPlatform ("maccatalyst13.1")]
		set
		{
			global::ObjCRuntime.Messaging.void_objc_msgSend_float (this.Handle, global::ObjCRuntime.Selector.GetHandle ("setObstruction:"), value);
			global::System.GC.KeepAlive (this);
		}
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Property> ("occlusion")]
	public float Occlusion
	{
		[SupportedOSPlatform ("macos")]
		[SupportedOSPlatform ("ios")]
		[SupportedOSPlatform ("tvos")]
		[SupportedOSPlatform ("maccatalyst13.1")]
		get
		{
			float ret;
			ret = global::ObjCRuntime.Messaging.float_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("occlusion"));
			global::System.GC.KeepAlive (this);
			return ret;
		}

		[SupportedOSPlatform ("macos")]
		[SupportedOSPlatform ("ios")]
		[SupportedOSPlatform ("tvos")]
		[SupportedOSPlatform ("maccatalyst13.1")]
		set
		{
			global::ObjCRuntime.Messaging.void_objc_msgSend_float (this.Handle, global::ObjCRuntime.Selector.GetHandle ("setOcclusion:"), value);
			global::System.GC.KeepAlive (this);
		}
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Property> ("pointSourceInHeadMode")]
	public global::AVFoundation.AVAudio3DMixingPointSourceInHeadMode PointSourceInHeadMode
	{
		[SupportedOSPlatform ("macos")]
		[SupportedOSPlatform ("ios")]
		[SupportedOSPlatform ("tvos")]
		[SupportedOSPlatform ("maccatalyst13.1")]
		get
		{
			global::AVFoundation.AVAudio3DMixingPointSourceInHeadMode ret;
			ret = (global::AVFoundation.AVAudio3DMixingPointSourceInHeadMode) (long) global::ObjCRuntime.Messaging.IntPtr_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("pointSourceInHeadMode"));
			global::System.GC.KeepAlive (this);
			return ret;
		}

		[SupportedOSPlatform ("macos")]
		[SupportedOSPlatform ("ios")]
		[SupportedOSPlatform ("tvos")]
		[SupportedOSPlatform ("maccatalyst13.1")]
		set
		{
			global::ObjCRuntime.Messaging.void_objc_msgSend_IntPtr (this.Handle, global::ObjCRuntime.Selector.GetHandle ("setPointSourceInHeadMode:"), (global::AVFoundation.AVAudio3DMixingPointSourceInHeadMode) (long) value);
			global::System.GC.KeepAlive (this);
		}
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Property> ("rate")]
	public float Rate
	{
		[SupportedOSPlatform ("macos")]
		[SupportedOSPlatform ("ios")]
		[SupportedOSPlatform ("tvos")]
		[SupportedOSPlatform ("maccatalyst13.1")]
		get
		{
			float ret;
			ret = global::ObjCRuntime.Messaging.float_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("rate"));
			global::System.GC.KeepAlive (this);
			return ret;
		}

		[SupportedOSPlatform ("macos")]
		[SupportedOSPlatform ("ios")]
		[SupportedOSPlatform ("tvos")]
		[SupportedOSPlatform ("maccatalyst13.1")]
		set
		{
			global::ObjCRuntime.Messaging.void_objc_msgSend_float (this.Handle, global::ObjCRuntime.Selector.GetHandle ("setRate:"), value);
			global::System.GC.KeepAlive (this);
		}
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Property> ("renderingAlgorithm")]
	public global::AVFoundation.AVAudio3DMixingRenderingAlgorithm RenderingAlgorithm
	{
		[SupportedOSPlatform ("macos")]
		[SupportedOSPlatform ("ios")]
		[SupportedOSPlatform ("tvos")]
		[SupportedOSPlatform ("maccatalyst13.1")]
		get
		{
			global::AVFoundation.AVAudio3DMixingRenderingAlgorithm ret;
			ret = (global::AVFoundation.AVAudio3DMixingRenderingAlgorithm) (long) global::ObjCRuntime.Messaging.IntPtr_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("renderingAlgorithm"));
			global::System.GC.KeepAlive (this);
			return ret;
		}

		[SupportedOSPlatform ("macos")]
		[SupportedOSPlatform ("ios")]
		[SupportedOSPlatform ("tvos")]
		[SupportedOSPlatform ("maccatalyst13.1")]
		set
		{
			global::ObjCRuntime.Messaging.void_objc_msgSend_IntPtr (this.Handle, global::ObjCRuntime.Selector.GetHandle ("setRenderingAlgorithm:"), (global::AVFoundation.AVAudio3DMixingRenderingAlgorithm) (long) value);
			global::System.GC.KeepAlive (this);
		}
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Property> ("reverbBlend")]
	public float ReverbBlend
	{
		[SupportedOSPlatform ("macos")]
		[SupportedOSPlatform ("ios")]
		[SupportedOSPlatform ("tvos")]
		[SupportedOSPlatform ("maccatalyst13.1")]
		get
		{
			float ret;
			ret = global::ObjCRuntime.Messaging.float_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("reverbBlend"));
			global::System.GC.KeepAlive (this);
			return ret;
		}

		[SupportedOSPlatform ("macos")]
		[SupportedOSPlatform ("ios")]
		[SupportedOSPlatform ("tvos")]
		[SupportedOSPlatform ("maccatalyst13.1")]
		set
		{
			global::ObjCRuntime.Messaging.void_objc_msgSend_float (this.Handle, global::ObjCRuntime.Selector.GetHandle ("setReverbBlend:"), value);
			global::System.GC.KeepAlive (this);
		}
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Property> ("sourceMode")]
	public global::AVFoundation.AVAudio3DMixingSourceMode SourceMode
	{
		[SupportedOSPlatform ("macos")]
		[SupportedOSPlatform ("ios")]
		[SupportedOSPlatform ("tvos")]
		[SupportedOSPlatform ("maccatalyst13.1")]
		get
		{
			global::AVFoundation.AVAudio3DMixingSourceMode ret;
			ret = (global::AVFoundation.AVAudio3DMixingSourceMode) (long) global::ObjCRuntime.Messaging.IntPtr_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("sourceMode"));
			global::System.GC.KeepAlive (this);
			return ret;
		}

		[SupportedOSPlatform ("macos")]
		[SupportedOSPlatform ("ios")]
		[SupportedOSPlatform ("tvos")]
		[SupportedOSPlatform ("maccatalyst13.1")]
		set
		{
			global::ObjCRuntime.Messaging.void_objc_msgSend_IntPtr (this.Handle, global::ObjCRuntime.Selector.GetHandle ("setSourceMode:"), (global::AVFoundation.AVAudio3DMixingSourceMode) (long) value);
			global::System.GC.KeepAlive (this);
		}
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Property> ("volume")]
	public float Volume
	{
		[SupportedOSPlatform ("macos")]
		[SupportedOSPlatform ("ios")]
		[SupportedOSPlatform ("tvos")]
		[SupportedOSPlatform ("maccatalyst13.1")]
		get
		{
			float ret;
			ret = global::ObjCRuntime.Messaging.float_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("volume"));
			global::System.GC.KeepAlive (this);
			return ret;
		}

		[SupportedOSPlatform ("macos")]
		[SupportedOSPlatform ("ios")]
		[SupportedOSPlatform ("tvos")]
		[SupportedOSPlatform ("maccatalyst13.1")]
		set
		{
			global::ObjCRuntime.Messaging.void_objc_msgSend_float (this.Handle, global::ObjCRuntime.Selector.GetHandle ("setVolume:"), value);
			global::System.GC.KeepAlive (this);
		}
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Method> ("destinationForMixer:bus:")]
	public global::AVFoundation.AVAudioMixingDestination? DestinationForMixer (global::AVFoundation.AVAudioNode mixer, global::System.UIntPtr bus)
	{
		var mixer__handle__ = mixer!.GetNonNullHandle (nameof (mixer));
		global::AVFoundation.AVAudioMixingDestination? ret;
		ret = global::ObjCRuntime.Runtime.GetNSObject<global::AVFoundation.AVAudioMixingDestination> (global::ObjCRuntime.Messaging.NativeHandle_objc_msgSend_NativeHandle_UIntPtr (this.Handle, global::ObjCRuntime.Selector.GetHandle ("destinationForMixer:bus:"), mixer__handle__, bus));
		global::System.GC.KeepAlive (this);
		global::System.GC.KeepAlive (mixer);
		return ret;
	}

}
