// <auto-generated />

#nullable enable

using Foundation;
using ObjCBindings;
using ObjCRuntime;
using System.Runtime.Versioning;

namespace Microsoft.Macios.Generator.Tests.Protocols.Data;

[SupportedOSPlatform ("macos")]
[SupportedOSPlatform ("ios")]
[SupportedOSPlatform ("tvos")]
[SupportedOSPlatform ("maccatalyst13.1")]
[Protocol (Name = "NSURLSessionDelegate", WrapperType = typeof (NSUrlSessionDelegateWrapper))]
[ProtocolMember (IsRequired = true, IsProperty = false, IsStatic = false, Name = "DidBecomeInvalid", Selector = "URLSession:didBecomeInvalidWithError:", ReturnType = typeof (void), ParameterType = new Type [] { typeof (global::Foundation.NSUrlSession), typeof (global::Foundation.NSError) }, ParameterByRef = new bool [] { false, false }, ParameterBlockProxy = new Type? [] { null, null })]
[ProtocolMember (IsRequired = true, IsProperty = false, IsStatic = false, Name = "DidFinishEventsForBackgroundSession", Selector = "URLSessionDidFinishEventsForBackgroundURLSession:", ReturnType = typeof (void), ParameterType = new Type [] { typeof (global::Foundation.NSUrlSession) }, ParameterByRef = new bool [] { false }, ParameterBlockProxy = new Type? [] { null })]
[ProtocolMember (IsRequired = true, IsProperty = false, IsStatic = false, Name = "DidReceiveChallenge", Selector = "URLSession:didReceiveChallenge:completionHandler:", ReturnType = typeof (void), ParameterType = new Type [] { typeof (global::Foundation.NSUrlSession), typeof (global::Foundation.NSUrlAuthenticationChallenge), typeof (global::.Action<global::Foundation.NSUrlSessionAuthChallengeDisposition, global::Foundation.NSUrlCredential>) }, ParameterByRef = new bool [] { false, false, false }, ParameterBlockProxy = new Type? [] { null, null, null })]
public partial interface INSUrlSessionDelegate : INativeObject, IDisposable
{

	[DynamicDependency ("DidBecomeInvalid(Foundation.NSUrlSession,Foundation.NSError)")]
	[DynamicDependency ("DidFinishEventsForBackgroundSession(Foundation.NSUrlSession)")]
	[DynamicDependency ("DidReceiveChallenge(Foundation.NSUrlSession,Foundation.NSUrlAuthenticationChallenge,.Action<global::Foundation.NSUrlSessionAuthChallengeDisposition, global::Foundation.NSUrlCredential>)")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	static INSUrlSessionDelegate ()
	{
		global::System.GC.KeepAlive (null);
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	internal static void _DidBecomeInvalid (this global::Microsoft.Macios.Generator.Tests.Protocols.Data.INSUrlSessionDelegate self, global::Foundation.NSUrlSession session, global::Foundation.NSError error)
	{
		var session__handle__ = session!.GetNonNullHandle (nameof (session));
		var error__handle__ = error!.GetNonNullHandle (nameof (error));
		global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle_NativeHandle (self.Handle, global::ObjCRuntime.Selector.GetHandle ("URLSession:didBecomeInvalidWithError:"), session__handle__, error__handle__);
		global::System.GC.KeepAlive (self);
		global::System.GC.KeepAlive (session);
		global::System.GC.KeepAlive (error);
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[global::Foundation.RequiredMember]
	public partial void DidBecomeInvalid (global::Foundation.NSUrlSession session, global::Foundation.NSError error)
	{
		throw new global::Foundation.You_Should_Not_Call_base_In_This_Method ();
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	internal static void _DidFinishEventsForBackgroundSession (this global::Microsoft.Macios.Generator.Tests.Protocols.Data.INSUrlSessionDelegate self, global::Foundation.NSUrlSession session)
	{
		var session__handle__ = session!.GetNonNullHandle (nameof (session));
		global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle (self.Handle, global::ObjCRuntime.Selector.GetHandle ("URLSessionDidFinishEventsForBackgroundURLSession:"), session__handle__);
		global::System.GC.KeepAlive (self);
		global::System.GC.KeepAlive (session);
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[global::Foundation.RequiredMember]
	public partial void DidFinishEventsForBackgroundSession (global::Foundation.NSUrlSession session)
	{
		throw new global::Foundation.You_Should_Not_Call_base_In_This_Method ();
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	internal static void _DidReceiveChallenge (this global::Microsoft.Macios.Generator.Tests.Protocols.Data.INSUrlSessionDelegate self, global::Foundation.NSUrlSession session, global::Foundation.NSUrlAuthenticationChallenge challenge, global::.Action<global::Foundation.NSUrlSessionAuthChallengeDisposition, global::Foundation.NSUrlCredential> completionHandler)
	{
		if (completionHandler is null)
			global::ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (completionHandler));
		var session__handle__ = session!.GetNonNullHandle (nameof (session));
		var challenge__handle__ = challenge!.GetNonNullHandle (nameof (challenge));
		global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle_NativeHandle_ (self.Handle, global::ObjCRuntime.Selector.GetHandle ("URLSession:didReceiveChallenge:completionHandler:"), session__handle__, challenge__handle__, completionHandler);
		global::System.GC.KeepAlive (self);
		global::System.GC.KeepAlive (session);
		global::System.GC.KeepAlive (challenge);
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[global::Foundation.RequiredMember]
	public partial void DidReceiveChallenge (global::Foundation.NSUrlSession session, global::Foundation.NSUrlAuthenticationChallenge challenge, global::.Action<global::Foundation.NSUrlSessionAuthChallengeDisposition, global::Foundation.NSUrlCredential> completionHandler)
	{
		throw new global::Foundation.You_Should_Not_Call_base_In_This_Method ();
	}

}

internal unsafe sealed class NSUrlSessionDelegateWrapper : BaseWrapper, INSUrlSessionDelegate
{

	[Preserve (Conditional = true)]
	public NSUrlSessionDelegateWrapper (NativeHandle handle, bool owns)
		: base (handle, owns)
	{
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Method> ("URLSession:didBecomeInvalidWithError:")]
	public void DidBecomeInvalid (global::Foundation.NSUrlSession session, global::Foundation.NSError error)
	{
		var session__handle__ = session!.GetNonNullHandle (nameof (session));
		var error__handle__ = error!.GetNonNullHandle (nameof (error));
		global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle_NativeHandle (this.Handle, global::ObjCRuntime.Selector.GetHandle ("URLSession:didBecomeInvalidWithError:"), session__handle__, error__handle__);
		global::System.GC.KeepAlive (this);
		global::System.GC.KeepAlive (session);
		global::System.GC.KeepAlive (error);
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Method> ("URLSessionDidFinishEventsForBackgroundURLSession:")]
	public void DidFinishEventsForBackgroundSession (global::Foundation.NSUrlSession session)
	{
		var session__handle__ = session!.GetNonNullHandle (nameof (session));
		global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle (this.Handle, global::ObjCRuntime.Selector.GetHandle ("URLSessionDidFinishEventsForBackgroundURLSession:"), session__handle__);
		global::System.GC.KeepAlive (this);
		global::System.GC.KeepAlive (session);
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Method> ("URLSession:didReceiveChallenge:completionHandler:")]
	public void DidReceiveChallenge (global::Foundation.NSUrlSession session, global::Foundation.NSUrlAuthenticationChallenge challenge, global::.Action<global::Foundation.NSUrlSessionAuthChallengeDisposition, global::Foundation.NSUrlCredential> completionHandler)
	{
		if (completionHandler is null)
			global::ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (completionHandler));
		var session__handle__ = session!.GetNonNullHandle (nameof (session));
		var challenge__handle__ = challenge!.GetNonNullHandle (nameof (challenge));
		global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle_NativeHandle_ (this.Handle, global::ObjCRuntime.Selector.GetHandle ("URLSession:didReceiveChallenge:completionHandler:"), session__handle__, challenge__handle__, completionHandler);
		global::System.GC.KeepAlive (this);
		global::System.GC.KeepAlive (session);
		global::System.GC.KeepAlive (challenge);
	}

}

[Register ("Microsoft_Macios_Generator_Tests_Protocols_Data_NSUrlSessionDelegate", false)]
[Model]
[SupportedOSPlatform ("macos")]
[SupportedOSPlatform ("ios")]
[SupportedOSPlatform ("tvos")]
[SupportedOSPlatform ("maccatalyst13.1")]
public unsafe abstract partial class NSUrlSessionDelegate : NSObject, INSUrlSessionDelegate
{
	/// <summary>Creates a new <see cref="NSUrlSessionDelegate" /> with default values.</summary>
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[DesignatedInitializer]
	[Export ("init")]
	public NSUrlSessionDelegate () : base (global::Foundation.NSObjectFlag.Empty)
	{
		if (IsDirectBinding)
			InitializeHandle (global::ObjCRuntime.Messaging.IntPtr_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("init")), "init");
		else
			InitializeHandle (global::ObjCRuntime.Messaging.IntPtr_objc_msgSendSuper (this.SuperHandle, global::ObjCRuntime.Selector.GetHandle ("init")), "init");
	}

	/// <summary>Constructor to call on derived classes to skip initialization and merely allocate the object.</summary>
	/// <param name="t">Unused sentinel value, pass NSObjectFlag.Empty.</param>
	/// <remarks>
	///     <para>
	///         This constructor should be called by derived classes when they completely construct the object in managed code and merely want the runtime to allocate and initialize the <see cref="Foundation.NSObject" />.
	///         This is required to implement the two-step initialization process that Objective-C uses, the first step is to perform the object allocation, the second step is to initialize the object.
	///         When developers invoke this constructor, they take advantage of a direct path that goes all the way up to <see cref="Foundation.NSObject" /> to merely allocate the object's memory and bind the Objective-C and C# objects together.
	///         The actual initialization of the object is up to the developer.
	///     </para>
	///     <para>
	///         This constructor is typically used by the binding generator to allocate the object, but prevent the actual initialization to take place.
	///         Once the allocation has taken place, the constructor has to initialize the object.
	///         With constructors generated by the binding generator this means that it manually invokes one of the "init" methods to initialize the object.
	///     </para>
	///     <para>It is the developer's responsibility to completely initialize the object if they chain up using this constructor chain.</para>
	///     <para>
	///         In general, if the developer's constructor invokes the corresponding base implementation, then it should also call an Objective-C init method.
	///         If this is not the case, developers should instead chain to the proper constructor in their class.
	///     </para>
	///     <para>
	///         The argument value is ignored and merely ensures that the only code that is executed is the construction phase is the basic <see cref="Foundation.NSObject" /> allocation and runtime type registration.
	///         Typically the chaining would look like this:
	///     </para>
	///     <example>
	///             <code lang="csharp lang-csharp"><![CDATA[
	/// //
	/// // The NSObjectFlag constructor merely allocates the object and registers the C# class with the Objective-C runtime if necessary.
	/// // No actual initXxx method is invoked, that is done later in the constructor
	/// //
	/// // This is taken from the iOS SDK's source code for the UIView class:
	/// //
	/// [Export ("initWithFrame:")]
	/// public UIView (System.Drawing.RectangleF frame) : base (NSObjectFlag.Empty)
	/// {
	///     // Invoke the init method now.
	///     var initWithFrame = new Selector ("initWithFrame:").Handle;
	///     if (IsDirectBinding) {
	///         Handle = ObjCRuntime.Messaging.IntPtr_objc_msgSend_CGRect (this.Handle, initWithFrame, frame);
	///     } else {
	///         Handle = ObjCRuntime.Messaging.IntPtr_objc_msgSendSuper_CGRect (this.SuperHandle, initWithFrame, frame);
	///     }
	/// }
	/// ]]></code>
	///     </example>
	/// </remarks>
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[EditorBrowsable (EditorBrowsableState.Advanced)]
	protected NSUrlSessionDelegate (global::Foundation.NSObjectFlag t) : base (t) {}

	/// <summary>A constructor used when creating managed representations of unmanaged objects. Called by the runtime.</summary>
	/// <param name="handle">Pointer (handle) to the unmanaged object.</param>
	/// <remarks>
	///     <para>
	///         This constructor is invoked by the runtime infrastructure (<see cref="ObjCRuntime.Runtime.GetNSObject(System.IntPtr)" />) to create a new managed representation for a pointer to an unmanaged Objective-C object.
	///         Developers should not invoke this method directly, instead they should call <see cref="ObjCRuntime.Runtime.GetNSObject(System.IntPtr)" /> as it will prevent two instances of a managed object pointing to the same native object.
	///     </para>
	/// </remarks>
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[EditorBrowsable (EditorBrowsableState.Advanced)]
	protected internal NSUrlSessionDelegate (global::ObjCRuntime.NativeHandle handle) : base (handle) {}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Method> ("URLSession:didBecomeInvalidWithError:")]
	public partial void DidBecomeInvalid (global::Foundation.NSUrlSession session, global::Foundation.NSError error)
	{
		throw new global::Foundation.ModelNotImplementedException ();
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Method> ("URLSessionDidFinishEventsForBackgroundURLSession:")]
	public partial void DidFinishEventsForBackgroundSession (global::Foundation.NSUrlSession session)
	{
		throw new global::Foundation.ModelNotImplementedException ();
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Method> ("URLSession:didReceiveChallenge:completionHandler:")]
	public partial void DidReceiveChallenge (global::Foundation.NSUrlSession session, global::Foundation.NSUrlAuthenticationChallenge challenge, global::.Action<global::Foundation.NSUrlSessionAuthChallengeDisposition, global::Foundation.NSUrlCredential> completionHandler)
	{
		throw new global::Foundation.ModelNotImplementedException ();
	}

}
