// <auto-generated />

#nullable enable

using Foundation;
using ObjCBindings;
using ObjCRuntime;
using System.Runtime.Versioning;

namespace Microsoft.Macios.Generator.Tests.Protocols.Data;

[SupportedOSPlatform ("macos")]
[SupportedOSPlatform ("ios")]
[SupportedOSPlatform ("tvos")]
[SupportedOSPlatform ("maccatalyst13.1")]
[Protocol (Name = "NSURLSessionDelegate", WrapperType = typeof (NSUrlSessionDelegateWrapper))]
[ProtocolMember (IsRequired = true, IsProperty = false, IsStatic = false, Name = "DidBecomeInvalid", Selector = "URLSession:didBecomeInvalidWithError:", ReturnType = typeof (void), ParameterType = new Type [] { typeof (global::Foundation.NSUrlSession), typeof (global::Foundation.NSError) }, ParameterByRef = new bool [] { false, false }, ParameterBlockProxy = new Type? [] { null, null })]
[ProtocolMember (IsRequired = true, IsProperty = false, IsStatic = false, Name = "DidFinishEventsForBackgroundSession", Selector = "URLSessionDidFinishEventsForBackgroundURLSession:", ReturnType = typeof (void), ParameterType = new Type [] { typeof (global::Foundation.NSUrlSession) }, ParameterByRef = new bool [] { false }, ParameterBlockProxy = new Type? [] { null })]
[ProtocolMember (IsRequired = true, IsProperty = false, IsStatic = false, Name = "DidReceiveChallenge", Selector = "URLSession:didReceiveChallenge:completionHandler:", ReturnType = typeof (void), ParameterType = new Type [] { typeof (global::Foundation.NSUrlSession), typeof (global::Foundation.NSUrlAuthenticationChallenge), typeof (global::.Action<global::Foundation.NSUrlSessionAuthChallengeDisposition, global::Foundation.NSUrlCredential>) }, ParameterByRef = new bool [] { false, false, false }, ParameterBlockProxy = new Type? [] { null, null, null })]
public partial interface INSUrlSessionDelegate : INativeObject, IDisposable
{

	[DynamicDependency ("DidBecomeInvalid(Foundation.NSUrlSession,Foundation.NSError)")]
	[DynamicDependency ("DidFinishEventsForBackgroundSession(Foundation.NSUrlSession)")]
	[DynamicDependency ("DidReceiveChallenge(Foundation.NSUrlSession,Foundation.NSUrlAuthenticationChallenge,.Action<global::Foundation.NSUrlSessionAuthChallengeDisposition, global::Foundation.NSUrlCredential>)")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	static INSUrlSessionDelegate ()
	{
		global::System.GC.KeepAlive (null);
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	internal static void _DidBecomeInvalid (this global::Microsoft.Macios.Generator.Tests.Protocols.Data.INSUrlSessionDelegate self, global::Foundation.NSUrlSession session, global::Foundation.NSError error)
	{
		var session__handle__ = session!.GetNonNullHandle (nameof (session));
		var error__handle__ = error!.GetNonNullHandle (nameof (error));
		global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle_NativeHandle (self.Handle, global::ObjCRuntime.Selector.GetHandle ("URLSession:didBecomeInvalidWithError:"), session__handle__, error__handle__);
		global::System.GC.KeepAlive (self);
		global::System.GC.KeepAlive (session);
		global::System.GC.KeepAlive (error);
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[global::Foundation.RequiredMember]
	public partial void DidBecomeInvalid (global::Foundation.NSUrlSession session, global::Foundation.NSError error)
	{
		throw new global::Foundation.You_Should_Not_Call_base_In_This_Method ();
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	internal static void _DidFinishEventsForBackgroundSession (this global::Microsoft.Macios.Generator.Tests.Protocols.Data.INSUrlSessionDelegate self, global::Foundation.NSUrlSession session)
	{
		var session__handle__ = session!.GetNonNullHandle (nameof (session));
		global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle (self.Handle, global::ObjCRuntime.Selector.GetHandle ("URLSessionDidFinishEventsForBackgroundURLSession:"), session__handle__);
		global::System.GC.KeepAlive (self);
		global::System.GC.KeepAlive (session);
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[global::Foundation.RequiredMember]
	public partial void DidFinishEventsForBackgroundSession (global::Foundation.NSUrlSession session)
	{
		throw new global::Foundation.You_Should_Not_Call_base_In_This_Method ();
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	internal static void _DidReceiveChallenge (this global::Microsoft.Macios.Generator.Tests.Protocols.Data.INSUrlSessionDelegate self, global::Foundation.NSUrlSession session, global::Foundation.NSUrlAuthenticationChallenge challenge, global::.Action<global::Foundation.NSUrlSessionAuthChallengeDisposition, global::Foundation.NSUrlCredential> completionHandler)
	{
		if (completionHandler is null)
			global::ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (completionHandler));
		var session__handle__ = session!.GetNonNullHandle (nameof (session));
		var challenge__handle__ = challenge!.GetNonNullHandle (nameof (challenge));
		global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle_NativeHandle_ (self.Handle, global::ObjCRuntime.Selector.GetHandle ("URLSession:didReceiveChallenge:completionHandler:"), session__handle__, challenge__handle__, completionHandler);
		global::System.GC.KeepAlive (self);
		global::System.GC.KeepAlive (session);
		global::System.GC.KeepAlive (challenge);
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[global::Foundation.RequiredMember]
	public partial void DidReceiveChallenge (global::Foundation.NSUrlSession session, global::Foundation.NSUrlAuthenticationChallenge challenge, global::.Action<global::Foundation.NSUrlSessionAuthChallengeDisposition, global::Foundation.NSUrlCredential> completionHandler)
	{
		throw new global::Foundation.You_Should_Not_Call_base_In_This_Method ();
	}

}

internal unsafe sealed class NSUrlSessionDelegateWrapper : BaseWrapper, INSUrlSessionDelegate
{

	[Preserve (Conditional = true)]
	public NSUrlSessionDelegateWrapper (NativeHandle handle, bool owns)
		: base (handle, owns)
	{
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Method> ("URLSession:didBecomeInvalidWithError:")]
	public void DidBecomeInvalid (global::Foundation.NSUrlSession session, global::Foundation.NSError error)
	{
		var session__handle__ = session!.GetNonNullHandle (nameof (session));
		var error__handle__ = error!.GetNonNullHandle (nameof (error));
		global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle_NativeHandle (this.Handle, global::ObjCRuntime.Selector.GetHandle ("URLSession:didBecomeInvalidWithError:"), session__handle__, error__handle__);
		global::System.GC.KeepAlive (this);
		global::System.GC.KeepAlive (session);
		global::System.GC.KeepAlive (error);
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Method> ("URLSessionDidFinishEventsForBackgroundURLSession:")]
	public void DidFinishEventsForBackgroundSession (global::Foundation.NSUrlSession session)
	{
		var session__handle__ = session!.GetNonNullHandle (nameof (session));
		global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle (this.Handle, global::ObjCRuntime.Selector.GetHandle ("URLSessionDidFinishEventsForBackgroundURLSession:"), session__handle__);
		global::System.GC.KeepAlive (this);
		global::System.GC.KeepAlive (session);
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Method> ("URLSession:didReceiveChallenge:completionHandler:")]
	public void DidReceiveChallenge (global::Foundation.NSUrlSession session, global::Foundation.NSUrlAuthenticationChallenge challenge, global::.Action<global::Foundation.NSUrlSessionAuthChallengeDisposition, global::Foundation.NSUrlCredential> completionHandler)
	{
		if (completionHandler is null)
			global::ObjCRuntime.ThrowHelper.ThrowArgumentNullException (nameof (completionHandler));
		var session__handle__ = session!.GetNonNullHandle (nameof (session));
		var challenge__handle__ = challenge!.GetNonNullHandle (nameof (challenge));
		global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle_NativeHandle_ (this.Handle, global::ObjCRuntime.Selector.GetHandle ("URLSession:didReceiveChallenge:completionHandler:"), session__handle__, challenge__handle__, completionHandler);
		global::System.GC.KeepAlive (this);
		global::System.GC.KeepAlive (session);
		global::System.GC.KeepAlive (challenge);
	}

}
