// <auto-generated />

#nullable enable

using AVFoundation;
using Foundation;
using ObjCBindings;
using ObjCRuntime;
using System.Runtime.Versioning;

namespace Microsoft.Macios.Generator.Tests.Protocols.Data;

[SupportedOSPlatform ("macos")]
[SupportedOSPlatform ("ios")]
[SupportedOSPlatform ("tvos")]
[SupportedOSPlatform ("maccatalyst13.1")]
[Protocol (Name = "AVAudioPlayerDelegate", WrapperType = typeof (AVAudioPlayerDelegateWrapper))]
[ProtocolMember (IsRequired = true, IsProperty = false, IsStatic = false, Name = "BeginInterruption", Selector = "audioPlayerBeginInterruption:", ReturnType = typeof (void), ParameterType = new Type [] { typeof (global::AVFoundation.AVAudioPlayer) }, ParameterByRef = new bool [] { false }, ParameterBlockProxy = new Type? [] { null })]
[ProtocolMember (IsRequired = true, IsProperty = false, IsStatic = false, Name = "DecoderError", Selector = "audioPlayerDecodeErrorDidOccur:error:", ReturnType = typeof (void), ParameterType = new Type [] { typeof (global::AVFoundation.AVAudioPlayer), typeof (global::Foundation.NSError) }, ParameterByRef = new bool [] { false, false }, ParameterBlockProxy = new Type? [] { null, null })]
[ProtocolMember (IsRequired = true, IsProperty = false, IsStatic = false, Name = "EndInterruption", Selector = "audioPlayerBeginInterruption:", ReturnType = typeof (void), ParameterType = new Type [] { typeof (global::AVFoundation.AVAudioPlayer) }, ParameterByRef = new bool [] { false }, ParameterBlockProxy = new Type? [] { null })]
[ProtocolMember (IsRequired = true, IsProperty = false, IsStatic = false, Name = "EndInterruption", Selector = "audioPlayerEndInterruption:withOptions:", ReturnType = typeof (void), ParameterType = new Type [] { typeof (global::AVFoundation.AVAudioPlayer), typeof (global::AVFoundation.AVAudioSessionInterruptionOptions) }, ParameterByRef = new bool [] { false, false }, ParameterBlockProxy = new Type? [] { null, null })]
[ProtocolMember (IsRequired = true, IsProperty = false, IsStatic = false, Name = "FinishedPlaying", Selector = "audioPlayerDidFinishPlaying:successfully:", ReturnType = typeof (void), ParameterType = new Type [] { typeof (global::AVFoundation.AVAudioPlayer), typeof (bool) }, ParameterByRef = new bool [] { false, false }, ParameterBlockProxy = new Type? [] { null, null })]
public partial interface IAVAudioPlayerDelegate : INativeObject, IDisposable
{

	[DynamicDependency ("BeginInterruption(AVFoundation.AVAudioPlayer)")]
	[DynamicDependency ("DecoderError(AVFoundation.AVAudioPlayer,Foundation.NSError?)")]
	[DynamicDependency ("EndInterruption(AVFoundation.AVAudioPlayer)")]
	[DynamicDependency ("EndInterruption(AVFoundation.AVAudioPlayer,AVFoundation.AVAudioSessionInterruptionOptions)")]
	[DynamicDependency ("FinishedPlaying(AVFoundation.AVAudioPlayer,bool)")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	static IAVAudioPlayerDelegate ()
	{
		global::System.GC.KeepAlive (null);
	}

	[UnsupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	internal static void _BeginInterruption (this global::Microsoft.Macios.Generator.Tests.Protocols.Data.IAVAudioPlayerDelegate self, global::AVFoundation.AVAudioPlayer player)
	{
		var player__handle__ = player!.GetNonNullHandle (nameof (player));
		global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle (self.Handle, global::ObjCRuntime.Selector.GetHandle ("audioPlayerBeginInterruption:"), player__handle__);
		global::System.GC.KeepAlive (self);
		global::System.GC.KeepAlive (player);
	}

	[UnsupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[global::Foundation.RequiredMember]
	public virtual partial void BeginInterruption (global::AVFoundation.AVAudioPlayer player)
	{
		throw new global::Foundation.You_Should_Not_Call_base_In_This_Method ();
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	internal static void _DecoderError (this global::Microsoft.Macios.Generator.Tests.Protocols.Data.IAVAudioPlayerDelegate self, global::AVFoundation.AVAudioPlayer player, global::Foundation.NSError? error)
	{
		var player__handle__ = player!.GetNonNullHandle (nameof (player));
		var error__handle__ = error?.GetHandle ();
		global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle_NativeHandle (self.Handle, global::ObjCRuntime.Selector.GetHandle ("audioPlayerDecodeErrorDidOccur:error:"), player__handle__, error__handle__);
		global::System.GC.KeepAlive (self);
		global::System.GC.KeepAlive (player);
		global::System.GC.KeepAlive (error);
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[global::Foundation.RequiredMember]
	public virtual partial void DecoderError (global::AVFoundation.AVAudioPlayer player, global::Foundation.NSError? error)
	{
		throw new global::Foundation.You_Should_Not_Call_base_In_This_Method ();
	}

	[UnsupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	internal static void _EndInterruption (this global::Microsoft.Macios.Generator.Tests.Protocols.Data.IAVAudioPlayerDelegate self, global::AVFoundation.AVAudioPlayer player)
	{
		var player__handle__ = player!.GetNonNullHandle (nameof (player));
		global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle (self.Handle, global::ObjCRuntime.Selector.GetHandle ("audioPlayerBeginInterruption:"), player__handle__);
		global::System.GC.KeepAlive (self);
		global::System.GC.KeepAlive (player);
	}

	[UnsupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[global::Foundation.RequiredMember]
	public virtual partial void EndInterruption (global::AVFoundation.AVAudioPlayer player)
	{
		throw new global::Foundation.You_Should_Not_Call_base_In_This_Method ();
	}

	[UnsupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	internal static void _EndInterruption (this global::Microsoft.Macios.Generator.Tests.Protocols.Data.IAVAudioPlayerDelegate self, global::AVFoundation.AVAudioPlayer player, global::AVFoundation.AVAudioSessionInterruptionOptions flags)
	{
		var player__handle__ = player!.GetNonNullHandle (nameof (player));
		global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle_UIntPtr (self.Handle, global::ObjCRuntime.Selector.GetHandle ("audioPlayerEndInterruption:withOptions:"), player__handle__, (global::AVFoundation.AVAudioSessionInterruptionOptions) (ulong) flags);
		global::System.GC.KeepAlive (self);
		global::System.GC.KeepAlive (player);
	}

	[UnsupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[global::Foundation.RequiredMember]
	public virtual partial void EndInterruption (global::AVFoundation.AVAudioPlayer player, global::AVFoundation.AVAudioSessionInterruptionOptions flags)
	{
		throw new global::Foundation.You_Should_Not_Call_base_In_This_Method ();
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	internal static void _FinishedPlaying (this global::Microsoft.Macios.Generator.Tests.Protocols.Data.IAVAudioPlayerDelegate self, global::AVFoundation.AVAudioPlayer player, bool flag)
	{
		var player__handle__ = player!.GetNonNullHandle (nameof (player));
		global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle_bool (self.Handle, global::ObjCRuntime.Selector.GetHandle ("audioPlayerDidFinishPlaying:successfully:"), player__handle__, flag ? (byte) 1 : (byte) 0);
		global::System.GC.KeepAlive (self);
		global::System.GC.KeepAlive (player);
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[global::Foundation.RequiredMember]
	public virtual partial void FinishedPlaying (global::AVFoundation.AVAudioPlayer player, bool flag)
	{
		throw new global::Foundation.You_Should_Not_Call_base_In_This_Method ();
	}

}

internal unsafe sealed class AVAudioPlayerDelegateWrapper : BaseWrapper, IAVAudioPlayerDelegate
{

	[Preserve (Conditional = true)]
	public AVAudioPlayerDelegateWrapper (NativeHandle handle, bool owns)
		: base (handle, owns)
	{
	}

	[UnsupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Method> ("audioPlayerBeginInterruption:")]
	public void BeginInterruption (global::AVFoundation.AVAudioPlayer player)
	{
		var player__handle__ = player!.GetNonNullHandle (nameof (player));
		global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle (this.Handle, global::ObjCRuntime.Selector.GetHandle ("audioPlayerBeginInterruption:"), player__handle__);
		global::System.GC.KeepAlive (this);
		global::System.GC.KeepAlive (player);
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Method> ("audioPlayerDecodeErrorDidOccur:error:")]
	public void DecoderError (global::AVFoundation.AVAudioPlayer player, global::Foundation.NSError? error)
	{
		var player__handle__ = player!.GetNonNullHandle (nameof (player));
		var error__handle__ = error?.GetHandle ();
		global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle_NativeHandle (this.Handle, global::ObjCRuntime.Selector.GetHandle ("audioPlayerDecodeErrorDidOccur:error:"), player__handle__, error__handle__);
		global::System.GC.KeepAlive (this);
		global::System.GC.KeepAlive (player);
		global::System.GC.KeepAlive (error);
	}

	[UnsupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Method> ("audioPlayerBeginInterruption:")]
	public void EndInterruption (global::AVFoundation.AVAudioPlayer player)
	{
		var player__handle__ = player!.GetNonNullHandle (nameof (player));
		global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle (this.Handle, global::ObjCRuntime.Selector.GetHandle ("audioPlayerBeginInterruption:"), player__handle__);
		global::System.GC.KeepAlive (this);
		global::System.GC.KeepAlive (player);
	}

	[UnsupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Method> ("audioPlayerEndInterruption:withOptions:")]
	public void EndInterruption (global::AVFoundation.AVAudioPlayer player, global::AVFoundation.AVAudioSessionInterruptionOptions flags)
	{
		var player__handle__ = player!.GetNonNullHandle (nameof (player));
		global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle_UIntPtr (this.Handle, global::ObjCRuntime.Selector.GetHandle ("audioPlayerEndInterruption:withOptions:"), player__handle__, (global::AVFoundation.AVAudioSessionInterruptionOptions) (ulong) flags);
		global::System.GC.KeepAlive (this);
		global::System.GC.KeepAlive (player);
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Method> ("audioPlayerDidFinishPlaying:successfully:")]
	public void FinishedPlaying (global::AVFoundation.AVAudioPlayer player, bool flag)
	{
		var player__handle__ = player!.GetNonNullHandle (nameof (player));
		global::ObjCRuntime.Messaging.void_objc_msgSend_NativeHandle_bool (this.Handle, global::ObjCRuntime.Selector.GetHandle ("audioPlayerDidFinishPlaying:successfully:"), player__handle__, flag ? (byte) 1 : (byte) 0);
		global::System.GC.KeepAlive (this);
		global::System.GC.KeepAlive (player);
	}

}

[Register ("Microsoft_Macios_Generator_Tests_Protocols_Data_AVAudioPlayerDelegate", false)]
[Model]
[SupportedOSPlatform ("macos")]
[SupportedOSPlatform ("ios")]
[SupportedOSPlatform ("tvos")]
[SupportedOSPlatform ("maccatalyst13.1")]
public unsafe abstract partial class AVAudioPlayerDelegate : NSObject, IAVAudioPlayerDelegate
{
	/// <summary>Creates a new <see cref="AVAudioPlayerDelegate" /> with default values.</summary>
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[DesignatedInitializer]
	[Export ("init")]
	public AVAudioPlayerDelegate () : base (global::Foundation.NSObjectFlag.Empty)
	{
		if (IsDirectBinding)
			InitializeHandle (global::ObjCRuntime.Messaging.IntPtr_objc_msgSend (this.Handle, global::ObjCRuntime.Selector.GetHandle ("init")), "init");
		else
			InitializeHandle (global::ObjCRuntime.Messaging.IntPtr_objc_msgSendSuper (this.SuperHandle, global::ObjCRuntime.Selector.GetHandle ("init")), "init");
	}

	/// <summary>Constructor to call on derived classes to skip initialization and merely allocate the object.</summary>
	/// <param name="t">Unused sentinel value, pass NSObjectFlag.Empty.</param>
	/// <remarks>
	///     <para>
	///         This constructor should be called by derived classes when they completely construct the object in managed code and merely want the runtime to allocate and initialize the <see cref="Foundation.NSObject" />.
	///         This is required to implement the two-step initialization process that Objective-C uses, the first step is to perform the object allocation, the second step is to initialize the object.
	///         When developers invoke this constructor, they take advantage of a direct path that goes all the way up to <see cref="Foundation.NSObject" /> to merely allocate the object's memory and bind the Objective-C and C# objects together.
	///         The actual initialization of the object is up to the developer.
	///     </para>
	///     <para>
	///         This constructor is typically used by the binding generator to allocate the object, but prevent the actual initialization to take place.
	///         Once the allocation has taken place, the constructor has to initialize the object.
	///         With constructors generated by the binding generator this means that it manually invokes one of the "init" methods to initialize the object.
	///     </para>
	///     <para>It is the developer's responsibility to completely initialize the object if they chain up using this constructor chain.</para>
	///     <para>
	///         In general, if the developer's constructor invokes the corresponding base implementation, then it should also call an Objective-C init method.
	///         If this is not the case, developers should instead chain to the proper constructor in their class.
	///     </para>
	///     <para>
	///         The argument value is ignored and merely ensures that the only code that is executed is the construction phase is the basic <see cref="Foundation.NSObject" /> allocation and runtime type registration.
	///         Typically the chaining would look like this:
	///     </para>
	///     <example>
	///             <code lang="csharp lang-csharp"><![CDATA[
	/// //
	/// // The NSObjectFlag constructor merely allocates the object and registers the C# class with the Objective-C runtime if necessary.
	/// // No actual initXxx method is invoked, that is done later in the constructor
	/// //
	/// // This is taken from the iOS SDK's source code for the UIView class:
	/// //
	/// [Export ("initWithFrame:")]
	/// public UIView (System.Drawing.RectangleF frame) : base (NSObjectFlag.Empty)
	/// {
	///     // Invoke the init method now.
	///     var initWithFrame = new Selector ("initWithFrame:").Handle;
	///     if (IsDirectBinding) {
	///         Handle = ObjCRuntime.Messaging.IntPtr_objc_msgSend_CGRect (this.Handle, initWithFrame, frame);
	///     } else {
	///         Handle = ObjCRuntime.Messaging.IntPtr_objc_msgSendSuper_CGRect (this.SuperHandle, initWithFrame, frame);
	///     }
	/// }
	/// ]]></code>
	///     </example>
	/// </remarks>
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[EditorBrowsable (EditorBrowsableState.Advanced)]
	protected AVAudioPlayerDelegate (global::Foundation.NSObjectFlag t) : base (t) {}

	/// <summary>A constructor used when creating managed representations of unmanaged objects. Called by the runtime.</summary>
	/// <param name="handle">Pointer (handle) to the unmanaged object.</param>
	/// <remarks>
	///     <para>
	///         This constructor is invoked by the runtime infrastructure (<see cref="ObjCRuntime.Runtime.GetNSObject(System.IntPtr)" />) to create a new managed representation for a pointer to an unmanaged Objective-C object.
	///         Developers should not invoke this method directly, instead they should call <see cref="ObjCRuntime.Runtime.GetNSObject(System.IntPtr)" /> as it will prevent two instances of a managed object pointing to the same native object.
	///     </para>
	/// </remarks>
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[EditorBrowsable (EditorBrowsableState.Advanced)]
	protected internal AVAudioPlayerDelegate (global::ObjCRuntime.NativeHandle handle) : base (handle) {}

	[UnsupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Method> ("audioPlayerBeginInterruption:")]
	public virtual partial void BeginInterruption (global::AVFoundation.AVAudioPlayer player)
	{
		throw new global::Foundation.ModelNotImplementedException ();
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Method> ("audioPlayerDecodeErrorDidOccur:error:")]
	public virtual partial void DecoderError (global::AVFoundation.AVAudioPlayer player, global::Foundation.NSError? error)
	{
		throw new global::Foundation.ModelNotImplementedException ();
	}

	[UnsupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Method> ("audioPlayerBeginInterruption:")]
	public virtual partial void EndInterruption (global::AVFoundation.AVAudioPlayer player)
	{
		throw new global::Foundation.ModelNotImplementedException ();
	}

	[UnsupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Method> ("audioPlayerEndInterruption:withOptions:")]
	public virtual partial void EndInterruption (global::AVFoundation.AVAudioPlayer player, global::AVFoundation.AVAudioSessionInterruptionOptions flags)
	{
		throw new global::Foundation.ModelNotImplementedException ();
	}

	[SupportedOSPlatform ("macos")]
	[SupportedOSPlatform ("ios")]
	[SupportedOSPlatform ("tvos")]
	[SupportedOSPlatform ("maccatalyst13.1")]
	[BindingImpl (BindingImplOptions.GeneratedCode | BindingImplOptions.Optimizable)]
	[Export<Method> ("audioPlayerDidFinishPlaying:successfully:")]
	public virtual partial void FinishedPlaying (global::AVFoundation.AVAudioPlayer player, bool flag)
	{
		throw new global::Foundation.ModelNotImplementedException ();
	}

}
