# pipeline to run after a ci build that will execute the apiscan and other governance tests
trigger: none
pr: none

# we cannot use a template in a pipeline context
resources:
  pipelines:
    - pipeline: macios
      source: \Xamarin\Mac-iOS\ci pipelines\xamarin-macios-ci
      trigger:
        stages:
          - build_packages

extends:
  template: templates/pipelines/run-api-scan.yml
  parameters:
    isPR: false
