# Pipeline that will calculate the api diff on a pr commit.

trigger: none
pr: none

resources:
  pipelines:
    - pipeline: macios
      source: \Xamarin\Mac-iOS\pr pipelines\xamarin-macios-pr
      trigger:
        stages:
          - configure_build

extends:
  template: templates/pipelines/api-diff-pipeline.yml
  parameters:
    isPR: true
