# Pipeline that will calculate the api diff on a ci commit.

trigger: none
pr: none

# we cannot use a template in a pipeline context
resources:
  pipelines:
    - pipeline: macios
      source: \Xamarin\Mac-iOS\ci pipelines\xamarin-macios-ci
      trigger:
        stages:
          - configure_build

extends:
  template: templates/pipelines/api-diff-pipeline.yml
  parameters:
    isPR: false
