# Pipeline that will calculate the api diff on a ci commit.

trigger:
  branches:
    include:
      - '*'
    exclude:
      - refs/heads/locfiles/*
      - refs/heads/dev/*
      - refs/heads/darc-*
      - refs/heads/backport-pr-*
  paths:
    exclude:
      - .github
      - docs
      - CODEOWNERS
      - ISSUE_TEMPLATE.md
      - LICENSE
      - NOTICE.txt
      - SECURITY.MD
      - README.md
      - src/README.md
      - tools/mtouch/README.md
      - msbuild/Xamarin.Localization.MSBuild/README.md

extends:
  template: templates/pipelines/api-diff-pipeline.yml
  parameters:
    isPR: false
