# YAML pipeline for post build operations. 
# This pipeline will execute the tests for the CI as soon as the workloads have been complited.

trigger: none
pr: none


# we cannot use a template in a pipeline context
resources:
  pipelines:
    - pipeline: macios
      source: xamarin-macios-ci
      trigger:
        stages:
          - build_packages
          - build_macos_tests

extends:
  template: templates/pipelines/run-tests-pipeline.yml
  parameters:
    isPR: false
