<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net$(BundledNETCoreAppTargetFrameworkVersion)-maccatalyst</TargetFramework>
    <OutputType>Library</OutputType>
    <IsAppExtension>true</IsAppExtension>
    <DefineConstants>$(DefineConstants);APP_EXTENSION</DefineConstants>
    <AssemblyName>AppExtension</AssemblyName>
    <RootNamespace>monotouchtestappextension</RootNamespace>
    <IncludeMonoTouchAppDelegate>false</IncludeMonoTouchAppDelegate>
  </PropertyGroup>

  <Import Project="..\..\..\..\shared.csproj" />

  <ItemGroup>
    <Compile Include="..\..\AudioUnitTestExtension.cs">
      <Link>AudioUnitTestExtension.cs</Link>
    </Compile>
  </ItemGroup>
</Project>
