name: Get Localization Translations
on:
  push:
    branches:
    - "lego/*"

jobs:
  pull-request:
    name: '[Localization PR to main]'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout

    - uses: repo-sync/pull-request@v2
      name: pull-request
      with:
        destination_branch: "main"
        pr_title: "[Localization] Pulling New Localization Translations"
        pr_body: "Automated PR. Bring new translated changes in the lcl files for OneLocBuild to create translated resx files."
        pr_label: "not-notes-worthy"
        pr_milestone: "Future"
        pr_allow_empty: false
        github_token: ${{ secrets.GITHUB_TOKEN }}
