<?xml version="1.0" encoding="utf-8"?>
<!-- This file contains the logic shared by all the platform-specific AppExtension.csproj projects. -->
<Project>
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <IsAppExtension>true</IsAppExtension>
    <AssemblyName>monotouchtest</AssemblyName>
    <RootNamespace>monotouchtestappextension</RootNamespace>
    <ApplicationId>com.xamarin.monotouch-test.AudioUnitExtension</ApplicationId>
    <ApplicationVersion>1</ApplicationVersion>
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
  </PropertyGroup>

  <Import Project="$(MSBuildThisFileDirectory)..\..\shared.csproj" />

  <ItemGroup>
    <!-- The Info.plist values that are common to all platforms. Everything else is either an MSBuild property or computed by the SDK. -->
    <PartialAppManifest Include="$(MSBuildThisFileDirectory)AppExtension-Info.plist" />
  </ItemGroup>

  <!-- On desktop the audio unit extension must be sandboxed. On mobile there's no app sandbox entitlement. -->
  <ItemGroup Condition="'$(SdkIsDesktop)' == 'true'">
    <CustomEntitlements Include="com.apple.security.app-sandbox" Type="boolean" Value="true" />
    <CustomEntitlements Include="com.apple.security.files.user-selected.read-only" Type="boolean" Value="true" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="$(MSBuildThisFileDirectory)AudioUnitTestExtension.cs">
      <Link>AudioUnitTestExtension.cs</Link>
    </Compile>
  </ItemGroup>

  <ItemGroup Condition="$(TargetFramework.EndsWith('-macos'))">
    <Compile Include="$(RootTestsDirectory)\common\Configuration.cs">
      <Link>Configuration.cs</Link>
    </Compile>
    <Compile Include="$(RootTestsDirectory)\common\ConfigurationNUnit.cs">
      <Link>ConfigurationNUnit.cs</Link>
    </Compile>
    <Compile Include="$(RootTestsDirectory)\common\ExecutionHelper.cs">
      <Link>ExecutionHelper.cs</Link>
    </Compile>
    <Compile Include="$(RootTestsDirectory)\common\PlatformInfo.cs">
      <Link>PlatformInfo.cs</Link>
    </Compile>
    <Compile Include="$(RootTestsDirectory)\common\Profile.cs">
      <Link>Extensions.cs</Link>
    </Compile>
    <Compile Include="$(RootTestsDirectory)\mtouch\Cache.cs">
      <Link>Cache.cs</Link>
    </Compile>
    <Compile Include="$(RootTestsDirectory)\..\tools\common\Execution.cs">
      <Link>Execution.cs</Link>
    </Compile>
    <Compile Include="$(RootTestsDirectory)\..\tools\common\OSPlatformAttributeExtensions.cs">
      <Link>OSPlatformAttributeExtensions.cs</Link>
    </Compile>
    <Compile Include="$(RootTestsDirectory)\..\tools\common\TargetFramework.cs">
      <Link>TargetFramework.cs</Link>
    </Compile>
    <Compile Include="$(RootTestsDirectory)\..\tools\common\StringUtils.cs">
      <Link>StringUtils.cs</Link>
    </Compile>
  </ItemGroup>
</Project>
