# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

TOP=../../../../..
DOTNET_PLATFORMS=macOS MacCatalyst
DOTNET_DESKTOP_PLATFORMS=$(DOTNET_PLATFORMS)

include $(TOP)/tests/common/shared-dotnet-test.mk

TESTNAME=monotouch-test-audio-unit-extension
