# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

TOP=../../../../..
DOTNET_PLATFORMS=macOS MacCatalyst iOS tvOS
DOTNET_DESKTOP_PLATFORMS=macOS MacCatalyst

include $(TOP)/tests/common/shared-dotnet-test.mk

TESTNAME=monotouch-test-audio-unit-extension
